<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Distributeurs de lubrifiants industriels ExxonMobil |  Mobil&trade;Industrial Lubricants</title><meta name="keywords" content="Avec Mobil&trade; Industrial Lubricants, il est facile de trouver un distributeur de lubrifiants. Trouvez un distributeur Mobil Industrial Lubricants maintenant."><meta name="description" content="ExxonMobil dispose d&rsquo;un solide réseau mondial de distributeurs agréés qui répondent à des exigences rigoureuses, notamment en termes de qualité, de manipulation des produits et de formation."><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="10/4/2014 10:51:39 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/distributorlocator_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1>Distributeurs officiels de lubrifiants industriels ExxonMobil</h1><p>Nous disposons d&rsquo;un solide réseau mondial de distributeurs agréés qui répondent à des exigences rigoureuses en termes de qualité, de manipulation des produits, de formation et de représentation de la marque. Nous travaillons en étroite collaboration avec eux pour veiller à ce que vous puissiez tirer le meilleur de nos lubrifiants indsutriels.</p><p>Grâce à notre localisateur de distributeurs Mobil&trade; ci-dessous, vous pouvez trouver le distributeur le plus proche de chez vous. Pour acheter des lubrifiants ExxonMobil pour l&rsquo;Aviation, veuillez consulter notre site web: <a href="http://www.exxonmobil.com/lubes/exxonmobil/emal/pages/wheretobuy/wheretobuy.html">Lubrifiants ExxonMobil pour l&rsquo;Aviation</a> (EN) vous y trouverez l&rsquo;un de nos distributeurs agréés dans votre pays. Pour toute question relative à un problème de lubrification ou à l&rsquo;amélioration de la productivité de vos équipements, contactez notre <a title="" href="contactus_technical-help-desks.aspx">Service d&rsquo;Assistance Technique.</a></p><p> 
                                <iframe src="http://www.distributorlocator.exxonmobil.com/gdl/gdllaunch.aspx?culture=fr-FR" width="680" height="650" frameborder="0"></iframe></p></div><div class="mc1column"><div class="item clrfix"><span class="freedate right"></span><h3></h3></div></div><%if(File.Exists(Server.MapPath("distributorlocator2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="distributorlocator2.aspx">2</a></li><li><a href="distributorlocator2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>