
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Le concept &ldquo; Advancing Productivity &rdquo;  &ndash;  Solutions en faveur du développement durable | Mobil&trade; Industrial Lubricants &ndash;  Lubrifiants industriels  Mobil&trade;</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="Advancing productivity, productivité, fiabilité des équipements, respect de l&rsquo;environnement, solutions en faveur du développement durable, engagement en faveur du développement durable, solutions lubrification, lubrifiants industriels Mobil"/><meta name="description" content="Le concept &ldquo; Advancing Productivity &rdquo;  décrit notre engagement à proposer à nos clients des solutions prenant en compte le développement durable. Ces solutions s&rsquo;appuient sur des lubrifiants hautes performances, des services associés à la lubrification et sur notre expertise industrielle."/><meta name="date" content="03-2015"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/Imports/js/xom.js"></script>
						<script type="text/javascript" src="/Imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="10/13/2015 1:38:59 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/lubricationsolutions_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Advancing Productivity" src="/IND/English/Images/150x150_top-productivity.jpg" longdesc="" border="0" alt="Advancing Productivity"></div><p xmlns=""><b><span style=" font-size: x-large; line-height: 24px;">Le concept &ldquo; Advancing Productivity &rdquo;</span>&nbsp;<br>
Des solutions durables de lubrification pour vos usines</b></p><p xmlns="">Dans le monde entier, pour de nombreuses industries, améliorer la productivité est un objectif prioritaire. Cela suffit pour beaucoup de fournisseurs de lubrifiants, mais pas pour les équipes dédiées aux lubrifiants industriels Mobil&trade;&nbsp;: nous comprenons que vos attentes vont aujourd&rsquo;hui bien au-delà de cette exigence, et que la réussite de vos entreprises passe aussi par l&rsquo;intégration du développement durable dans vos opérations.</p><p xmlns="">Car vous êtes focalisés non seulement sur la <i>Productivité</i>, mais aussi sur la <i>Sécurité</i>, de façon à ce que personne ne soit victime d&rsquo;un accident du travail dans votre entreprise. Enfin, vous avez également mis l&rsquo;accent sur des objectifs contribuant à la <i>Protection de l&rsquo;Environnement</i>, afin de minimiser l&rsquo;impact environnemental de vos activités.</p><p xmlns="">Cette approche &nbsp;couvrant 3 domaines essentiels pour le caractère durable de vos activités opérationnelles est intégrée dans notre offre globale : c&rsquo;est ce que nous appelons le concept <b>"Advancing Productivity".</b></p><p xmlns="">Les trois principes clés du concept &rdquo;Advancing Productivity &ldquo; &nbsp;sont en parfaite adéquation avec nos engagements pris en faveur du développement durable, à savoir un équilibre entre croissance économique, développement social &nbsp;et protection de l&rsquo;environnement de façon à ce que les générations futures ne soient pas pénalisées par les comportements d&rsquo;aujourd&rsquo;hui. En résumé, le concept &ldquo; Advancing Productivity &rdquo; s&rsquo;intègre facilement dans le cadre des actions prises en faveur du développement durable déjà en vigueur dans votre entreprise.</p><p xmlns="">Nous avons créé ce concept &ldquo; Advancing Productivity &rdquo; pour qu&rsquo;il soit au service de votre entreprise et de ses objectifs, vous apportant des solutions concrètes, efficaces et durables en termes de lubrification comme de support technique. Ces solutions peuvent vous apporter des avantages dans trois domaines essentiels:</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial safety helmet, eye glasses and ear bud protection" src="/IND/English/Images/industrial-safety-helmet-eye-glasses-ear-protection.jpg" longdesc="" border="0" alt="Industrial safety helmet, eye glasses and ear bud protection"></div><p xmlns=""><b>Sécurité</b><br>
La fiabilité accrue des équipements et la longue durée de vie en service des lubrifiants peuvent contribuer à limiter les risques potentiels pris par les opérateurs, ainsi que les éventuelles fuites ou nappes d&rsquo;huiles répandues sur le sol. Si le contact direct occasionné par les interventions sur les équipements est réduit, du fait d&rsquo;intervalles de vidange augmentés et d&rsquo;une fiabilité accrue, la nécessité et la fréquence de maintenance est moindre et le risque d&rsquo;accident s&rsquo;en trouve d&rsquo;autant réduit.</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial environmental care with two hands holding the world" src="/IND/English/Images/industrial-environmental-care-two-hands-world.jpg" longdesc="" border="0" alt="Industrial environmental care with two hands holding the world"></div><p xmlns=""><b>Respect de l&rsquo;environnement</b><br>
Nos lubrifiants à la pointe de la technologie peuvent apporter des avantages en termes d&rsquo;efficacité énergétique, d&rsquo;où la possibilité d&rsquo;une moindre consommation d&rsquo;énergie et la réduction potentielle des émissions de gaz à effet de serre.<br>
De plus, bon nombre de ces lubrifiants à la pointe du progrès<br>
permettent d&rsquo;envisager un allongement des intervalles de vidange, d&rsquo;où un moindre volume d&rsquo;huile usée à gérer annuellement. Enfin, nos lubrifiants, huiles ou graisses, apportent aux équipements une durée de vie optimisée, réduisant ainsi potentiellement leur fréquence de renouvellement et donc les quantités de composants mécaniques usagés à éliminer, ainsi que les quantités de déchets associés, générés par les opérations de maintenance et de remplacement. &nbsp;&nbsp;</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial productivity with equipment gears" src="/IND/English/Images/industrial-productivity-equipment-gears.jpg" longdesc="" border="0" alt="Industrial productivity with equipment gears"></div><p xmlns=""><b>Productivité</b><br>
Une disponibilité accrue des équipements favorise de fait leur efficacité opérationnelle et leur productivité. In fine, cela contribue aussi à renforcer la compétitivité des entreprises industrielles, via une réduction potentielle des coûts de production, de maintenance et de remplacement des équipements.</p><p xmlns=""><br>
Notre priorité est de vous aider à atteindre vos propres objectifs en termes de sécurité, de respect de l&rsquo;environnement et de productivité, ceci grâce à nos innovantes solutions de lubrification. Ceci est le c&#339;ur même du concept que nous appelons &ldquo; Advancing Productivity &rdquo;. Et c&rsquo;est aussi de cette manière, avec cette vision élargie de notre offre, que nous pouvons aider vos entreprises industrielles à atteindre avec succès leurs divers objectifs, en étant un véritable partenaire de leur réussite.</p><div class="imgns left"><img xmlns="" title="Advancing productivity brochure front cover thumbnail " src="/IND/English/Images/advancing-productivity-brochure-thumbnail.jpg" longdesc="" border="0" alt="Advancing productivity brochure front cover thumbnail "></div><p xmlns=""><a title="This link will open a new window." target="_new" href="/IND/French/files/advancing_productivity_brochure.pdf">Advancing Productivity brochure&nbsp;<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></p><p xmlns="">Découvrez comment nous pouvons contribuer à améliorer la&nbsp;<br>
sécurité, le respect de l&rsquo;environnement et la productivité.</p><p xmlns=""><br>
&nbsp;</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>