
				<%@ Page Language="C#"%>
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
				<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Mobil Serv Lubricant Analysis &ndash; Solutions pour la lubrification et les  analyses d&rsquo;huile | Mobil Industrial Lubricants &ndash; Lubrifiants industriels Mobil</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="mobil servSM, mobil lubricants, mobil servSM lubricant analysis, mobil, industrie, industriel, ingénieurs support technique terrain, inspection de moteur, analyse d&rsquo;huile"/><meta name="description" content="Mobil ServSM apporte des solutions innovantes, à la pointe du progrès, et propose une gamme complète de services techniques liés à la lubrification tels que, par exemple, des analyses d&rsquo;huile ou des inspections de moteur. L&rsquo;ensemble est le résultat de  150 ans d&rsquo;expertise en lubrification."/><meta name="date" content="01-2016"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/imports/js/xom.js"></script>
						<script type="text/javascript" src="/imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="3/19/2017 10:16:24 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/lubricationsolutions_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Mobil Serv Lubricant Analysis" src="Images/article_150x150_mobil-serv.jpg" longdesc="" border="0" alt="Mobil Serv Lubricant Analysis"></div><p xmlns=""> &nbsp;<b><span style=" font-size: x-large;">Les solutions pour la &nbsp;lubrification apportées par Mobil Serv<sup>SM</sup></span></b></p><p xmlns="">S&rsquo;appuyant sur 150 ans d&rsquo;expertise en lubrification, notre gamme complète de services techniques est devenue une référence mondiale. Que ce soit dans l&rsquo;industrie, les travaux publics, les mines et carrières ou bien encore les transports, elle aide nos clients à optimiser leurs programmes de maintenance et la disponibilité de leurs équipements. Afin de démontrer notre engagement continu à &nbsp;fournir cette gamme exceptionnelle de services liés à la lubrification, nous avons décidé de les regrouper, au niveau mondial, sous une nouvelle marque &ndash; Mobil Serv<sup>SM</sup>.</p><p xmlns="">Nos services ont ainsi été conçus comme une offre complémentaire à la fourniture &nbsp;de nos lubrifiants de marque Mobil&trade;. Cette combinaison nous permet de vous proposer des solutions opérationnelles capables de vous apporter un réel avantage concurrentiel et une grande valeur ajoutée, afin de vous aider in fine à atteindre vos principaux objectifs en termes de :</p><p xmlns=""><br>
&nbsp;</p><div class="imgns left"><img xmlns="" title="Industrial safety helmet, eye glasses and ear bud protection" src="Images/industrial-safety-helmet-eye-glasses-ear-protection.jpg" longdesc="" border="0" alt="Industrial safety helmet, eye glasses and ear bud protection"></div><p xmlns=""><b>Sécurité </b>- en réduisant le nombre d&rsquo;interactions entre les opérateurs et les équipements</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial environmental care with two hands holding the world" src="Images/industrial-environmental-care-two-hands-world.jpg" longdesc="" border="0" alt="Industrial environmental care with two hands holding the world"></div><p xmlns=""><b>Respect de l&rsquo;environnement* </b>- en apportant des avantages en termes d&rsquo;amélioration de l&rsquo;efficacité énergétique, et en fournissant des lubrifiants ayant une très longue durée de vie en service, ce qui va contribuer à diminuer le volume annuel &nbsp;d&rsquo;huile usée.</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial productivity with equipment gears" src="Images/industrial-productivity-equipment-gears.jpg" longdesc="" border="0" alt="Industrial productivity with equipment gears"></div><p xmlns=""><b>Productivité </b>- en contribuant à améliorer la fiabilité des équipements, ce qui favorise un accroissement de la production et une réduction des coûts opérationnels&nbsp;</p><p xmlns=""></p><p xmlns="">Notre réseau mondial d&rsquo;ingénieurs de support technique terrain est hautement qualifié et bénéficie de formations régulières. Il possède non seulement une grande connaissance de la lubrification et des applications, mais aussi des évolutions, tendances et perspectives à venir dans les domaines concernés. Cet avantage significatif s&rsquo;appuie sur plusieurs décennies d&rsquo;expérience de support technique terrain, et sur plus d&rsquo;un siècle de relations avec les constructeurs d&rsquo;équipements. Ainsi, Mobil Serv<sup>SM</sup> peut aider à améliorer votre efficacité opérationnelle en vous apportant :</p><ul xmlns=""><li>Des recommandations relatives aux lubrifiants, à leur application, et à l&rsquo;optimisation de leur utilisation.</li><li>Une assistance professionnelle à la compréhension et la résolution des problèmes de lubrification.</li><li>Des solutions innovantes de lubrification, s&rsquo;appuyant sur les meilleures pratiques recensées dans le monde entier.</li><li>Des rapports documentant de façon concrète les économies apportées par nos solutions&nbsp;de lubrification à votre entreprise.</li></ul><p xmlns=""><br>
&nbsp;</p><p xmlns="">Notre nouvelle marque Mobil Serv<sup>SM</sup> &nbsp;comprend :</p><p xmlns="">&nbsp;</p><p xmlns=""><b><a title="This link will open a new window." target="_new" href="https://mobilserv.mobil.com/fr/">Mobil Serv </a><i><a title="This link will open a new window." target="_new" href="https://mobilserv.mobil.com/fr/">Lubricant Analysis</a></i></b><i><a title="This link will open a new window." target="_new" href="https://mobilserv.mobil.com/fr/"></a></i>&ndash; cette offre remplace Signum<sup>SM</sup> Oil Analysis, en apportant de &nbsp;nombreuses fonctionnalités et avantages complémentaires.</p><p xmlns="">&nbsp;</p><p xmlns=""><b>Mobil Serv <i>Advanced Analytics</i></b> &ndash; cette offre vient compléter notre nouveau programme de suivi analytique des huiles en service. Elle contient des tests et des &nbsp;tableaux d&rsquo;analyses très élaborés, afin de pouvoir résoudre des problèmes de lubrification complexes, évaluer la compatibilité entre deux lubrifiants ou bien encore comparer les performances respectives de plusieurs produits. Par ailleurs, Mobil Serv<sup>SM</sup> Advanced Analytics &nbsp;&nbsp;peut aussi être utilisée dans le cadre d&rsquo;une investigation ou expertise effectuée suite à une casse de matériel.</p><p xmlns="">&nbsp;</p><p xmlns=""><b>Mobil Serv <i>Engineering Services</i></b> &ndash; cette offre inclut une gamme complète de services techniques, bien connue de nos clients. Elle va des conseils et recommandations en matière de lubrification jusqu&rsquo;aux inspections de moteurs ou de réducteurs, en passant par des audits de sites.</p><p xmlns="">&nbsp;</p><p xmlns="">Restez à l&rsquo;écoute, dans les prochains mois, &nbsp;des communications à venir au sujet de Mobil Serv<sup>SM</sup>, notre nouvelle gamme d&rsquo;offres de services liés à la lubrification. Les équipes de ventes Mobil et notre réseau de distributeurs restent, comme toujours, à votre écoute et sont disponibles pour répondre à tous vos besoins en matière de lubrification ou pour vous aider à résoudre vos défis les plus ardus.</p><p xmlns="">&nbsp;</p><p xmlns=""><span style=" font-size: xx-small;">*Découvrez sur <a title="" target="" href="default.aspx">mobilindustrial.fr</a> comment certains lubrifiants Mobil peuvent contribuer, grâce à leurs caractéristiques, à réduire l&rsquo;impact environnemental. Les avantages effectivement constatés dépendent du produit sélectionné, des conditions de fonctionnement et des applications.</span> &nbsp;</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>