
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>L'expérience de l'industrie |  Mobil&trade; Industrial Lubricants </title><meta name="keywords" content="experts industriels, des experts de l'industrie pétrolière, les experts de lubrifiants industriels, experts pétroliers"/><meta name="description" content="Mobil&trade; Industrial Lubricants vous propose une huile de technologie avancée pour tirer le meilleur de vos machines. Découvrez comment notre expérience en lubrification dépasse toutes les attentes."/><meta name="date" content="10-2013"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:55:16 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/ourbusiness_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Industry Expertise" src="/IND/English/Images/article_150x150_productivity-expertise.jpg" longdesc="" border="0" alt="Industry Expertise"></div><p xmlns=""><span style=" font-size: x-large;"><b>Experts en lubrification et</b></span></p><p xmlns=""><span style=" font-size: x-large;"><b>huile industrielle</b></span><br><br>
&nbsp;Qu&rsquo;il s&rsquo;agisse d&rsquo;alimentation, de transport de marchandises ou de matériaux de construction, notre civilisation dépend en grande partie de la qualité de produits manufacturés &mdash; pour satisfaire les exigences liées à leur fabrication, les industriels s&rsquo;appuient presque exclusivement sur des machines de production. Il est essentiel de doter ces machines de lubrifiants de qualité si l&rsquo;on souhaite les voir fonctionner durablement avec un rendement optimal.</p><p xmlns="">Mobil&trade; Industrial Lubricants conçoit des lubrifiants hautes performances et peut vous aider à tirer le meilleur de vos équipements.</p><p xmlns="">Depuis 1914, nous travaillons conjointement avec les plus grands constructeurs d&rsquo;équipements au monde également connus sous le nom d&rsquo;OEMs (Original Equipment Manufacturers) et ce, dans le but :</p><ul xmlns=""><li>D&rsquo;obtenir des informations sur les tendances du marché et leur impact sur les lubrifiants de demain</li><li>D&rsquo;obtenir des informations sur le design des circuits de lubrification</li><li>De participer à la résolution de problèmes techniques</li></ul><p xmlns="">On retrouve les fruits de ce travail commun avec les constructeurs d&rsquo;équipements dans la formulation de nos lubrifiants.</p><p xmlns="">Nos équipes d&rsquo;Ingénieurs Lubrifiants (FES) assistent nos clients dans l&rsquo;implantation de programmes destinés à rationaliser les pratiques de maintenance. Plus spécifiquement, ils s&rsquo;efforcent quotidiennement de les aider à améliorer leur compétitivité et à réaliser leurs objectifs en :</p><ul xmlns=""><li>Augmentant la durée de vie des machines de production</li><li>Réduisant les arrêts principalement les arrêts non programmés</li><li>Augmenter les périodicités de vidange</li><li>Limiter les rejets</li></ul><p xmlns=""><br>
&nbsp;</p><p xmlns="">&nbsp;</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>