
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Mobil DTE&trade; 732 M - Mitsubishi huile turbine | lubrifiants industriels Mobil &trade; de marque</title><meta name="keywords" content="Mobil DTE 732, Mobil DTE 732 M, Mitsubishi turbine, l'huile de turbine, Mitsubishi vapeur et turbines à gaz, les turbines à gaz de l'arbre, multi turbines à gaz de l'arbre"/><meta name="description" content="Mobil DTE 732 M&trade; huile de turbine offre une protection optimale pour poids lourds, non-orientés, gaz à arbre unique et des turbines à vapeur ainsi que des turbines à gaz multi-arbre."/><meta name="date" content="06/2014"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="12/18/2014 8:11:39 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Mobil DTE 732 M" src="/IND/English/Images/article_150x150_mobil-dte-732-m.jpg" longdesc="" border="0" alt="Mobil DTE 732 M"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobil DTE&trade; 732 M</b></span></p><p xmlns=""><b><span style=" font-size: large;">Un nouveau standard au service de la<br>
productivité</span></b></p><p xmlns="">L&rsquo;huile turbine Mobil DTE 732 M est la dernière-née de la gamme des huiles turbines Mobil DTE&trade; 700. Elle apporte une protection optimale aux turbines à gaz à arbres multiples, sans engrenages, ainsi qu&rsquo;aux turbines à gaz et turbines à vapeur, à arbre simple et sans engrenages, fonctionnant en service intensif.</p><p xmlns="">Huile de haute qualité, Mobil DTE 732 M est approuvée MSO4-MA-CLOO5, ce qui signifie qu&rsquo;elle satisfait ou dépasse le niveau d&rsquo;exigences techniques le plus élevé demandé par Mitsubishi Heavy Industries (MHI).</p><p xmlns="">Pour pouvoir bénéficier de cette approbation, l&rsquo;huile turbine Mobil DTE 732 M a démontré qu&rsquo;elle contribuait à réduire la formation de boues (lors du test « MHI dry TOST ») et qu&rsquo;elle possédait également une remarquable aptitude à limiter la formation de dépôts. Cette spécification autorise l&rsquo;emploi de Mobil DTE 732 M sur les turbines à gaz ou à vapeur Mitsubishi, conçues pour une très longue durée de vie et fonctionnant à haute température, dans des conditions sévères de service.</p><p xmlns=""><br><b>Une disponibilité mondiale</b><br>
L&rsquo;huile turbine Mobil DTE 732 M est disponible au niveau mondial, d&rsquo;où l&rsquo;assurance pour les utilisateurs de pouvoir bénéficier d&rsquo;une fiabilité dans leurs approvisionnements, ceci avec une intégrité et une continuité produit respectées. Par ailleurs, elle est aussi compatible en service avec l&rsquo;huile Mobil DTE 732. Avec sa remarquable résistance à l&rsquo;oxydation et son excellente stabilité thermique, l&rsquo;huile &nbsp;Mobil DTE 732 M est conçue pour posséder une très longue durée de vie en service et pour contribuer à la longévité des turbines qu&rsquo;elle lubrifie. C&rsquo;est un produit qui bénéficie pour sa formulation d&rsquo;une technologie de nouvelle génération, dont l&rsquo;un des avantages se traduit pour l&rsquo;utilisateur par une grande propreté des turbines et de leurs composants.</p><p xmlns="">Les huiles turbines Mobil DTE&trade; sont au service des professionnels de la production énergétique, les accompagnant depuis plus de 50 ans dans le monde entier.</p><p xmlns=""><a title="This link will open a new window." target="_new" href="/IND/English/Files/steam-gas-turbine-oil-mobil-dte-732-m.pdf">Fiche Marketing &nbsp;Mobil DTE&trade; 732 M (en Anglais)<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>