
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Graisses industrielles : Mobilux&trade; série EP 111 | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Graisse hautes performances, Mobilux, Mobilux série EP 111, accouplements d&rsquo;engrenages, lubrification d&rsquo;accouplements, huile minérale lourde, graisse au lithium, graisse d&rsquo;hydroxystéarate "/><meta name="description" content="Formulée à partir d&rsquo;une huile de base minérale lourde et visqueuse, Mobilux&trade; série EP 111 est une graisse d&rsquo;hydroxystéarate de lithium apportant performance et protection excellentes à de nombreuses industries."/><meta name="date" content="10/2013"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:55:19 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Lubrifiant Mobilux&trade; série EP 111 dans des accouplements d&rsquo;engrenages" src="/IND/English/Images/article_150x150_mobil-ep-111.jpg" longdesc="" border="0" alt="Lubrifiant Mobilux&trade; série EP 111 dans des accouplements d&rsquo;engrenages"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobilux&trade; EP 111</b></span></p><p xmlns=""><span style=" font-size: large;"><b>Graisse hautes performances</b></span><br><br>
Mobilux EP 111 est une graisse hautes performances destinée à la lubrification des accouplements AGMA CG-3. Elle est spécialement conçue pour contribuer à la protection des équipements contre l&rsquo;usure, même dans les accouplements à dentures à faible vitesse lourdement chargés et désalignés.</p><p xmlns="">Formulée à partir d&rsquo;une huile de base minérale visqueuse très lourde, Mobilux EP 111 est une graisse hydroxysté au lithium pouvant offrir performances et protection optimales à un large éventail d&rsquo;industries. Elle s&rsquo;est forgée une réputation remarquable grâce à la fiabilité de ses performances et est devenue la graisse de choix pour de nombreux utilisateurs.</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>