
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Industrie minière : Mobilgrease XHP&trade; 681 Mine | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Mobilgrease XHP, Mobilgrease XHP 681 Mine, Série Mobilgrease mine, graisse au lithium complexe, industrie minière, lubrifiants Mobilgrease, graisse de lubrification"/><meta name="description" content="Mobilgrease XHP&trade; 681 Mine est le produit phare de la gamme Mobilgrease&trade; spécialisée dans la lubrification des équipements  utilisés dans les secteurs des travaux publics et des mines et fonctionnant dans un environnement difficile"/><meta name="date" content="10/2013"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="7/27/2014 5:53:09 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Graisse spécialisée pour les matériels non routier utilisés dans l&rsquo;industrie minière" src="/IND/English/Images/article_150x150_mobil-xhp-681.jpg" longdesc="" border="0" alt="Graisse spécialisée pour les matériels non routier utilisés dans l&rsquo;industrie minière"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobilgrease XHP&trade; 681 Mine</b></span></p><p xmlns=""><span style=" font-size: large;"><b>Graisse spécialisée pour la lubrification des équipements utilisés dans l&rsquo;industrie minière</b></span><br><br>
Mobilgrease XHP 681 Mine est un produit phare de la gamme de produits Mobilgrease&trade;, qui a acquis une réputation d&rsquo;innovation de pointe et d&rsquo;excellence sur le plan des performances.</p><p xmlns="">Formulées à partir de la technologie de pointe au lithium complexe, les Mobilgrease XHP 681 Mine utilisent &nbsp;une viscosité d&rsquo;huile de base ISO VG 680 et des capacités renforcées de polymère pour fournir une résistance à l&rsquo;eau et une stabilité au cisaillement en milieu humide pour un graissage réussi des équipements utilisés dans les secteurs des travaux publics et des mines, fonctionnant dans un environnement difficile.</p><p xmlns=""><b>Longue durée de vie en service</b><br>
Les graisses Mobilgrease XHP 681 ont des capacités de résistance remarquables et de longue durée de vie en service, notamment une excellente résistance au délavage par l&rsquo;eau, à la pulvérisation d&rsquo;eau, et sont compatibles avec les matériaux d&rsquo;étanchéité classiques. A l&rsquo;instar de tous les lubrifiants Mobilgrease, elles bénéficient du soutien de notre équipe d&rsquo;appui technique à l&rsquo;échelle mondiale.</p><p xmlns=""><a title="This link will open a new window." target="_new" href="/IND/English/files/mobilgrease-xhp-mine-series.pdf">Mobilgrease XHP&trade; : fiche argumentaire<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</p><p xmlns=""><a title="This link will open a new window." target="_new" href="/IND/English/files/mining-industry-machinery-efficiency-brochure.pdf">Brochure "Lubrifiants Mobil&trade; pour les mines et carrières"<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>