
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="fr" lang="fr"><head><title>Avantages des lubrifiants synthétiques | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Mobil SHC lubrifiants, les avantages de l'huile synthétique, les avantages d'huile synthétique, une huile synthétique industrielle"/><meta name="description" content="Renseignez-vous sur les avantages de l'utilisation d'huile synthétique sur votre équipement industriel. Obtenez plus d'informations sur les lubrifiants Mobil SHC&trade; sur MobilIndustrial.com."/><meta name="date" content="10-2013"/><meta name="language" content="fr"/><meta http-equiv="Content-Language" content="fr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:54:13 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=fr">Fiche technique produits (FTP)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Fiche de données de sécurité (FDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Lubrifiants Synthétiques Mobil SHC " src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Lubrifiants Synthétiques Mobil SHC "><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Points de vente<br><a title="" target="" href="distributorlocator.aspx">Trouvez le distributeur le plus proche de chez vous</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/ind/english/productselector.aspx"><img xmlns="" title="Productivité " src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Productivité "><p xmlns=""><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx"></a></p><p xmlns="">Guide de sélection de produits Looble<sup>SM</sup>(EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trouvez les lubrifiants les plus appropriés à vos applications industrielles</a></p></a></div></div></div><div id="mainContent"><br/><a href="/IND/French/Images/benefits-of-synthetics.swf"><img title="3" src="/IND/French/Images/benefits-of-synthetics.jpg" longdesc="2" alt="1"/></a><script xmlns="" type="text/javascript" language="JavaScript">
						var so = new SWFObject("/IND/French/Images/benefits-of-synthetics.swf",	//Flash movie name
						"photoviewer", 		// ID for generated object/embed
						"100%", 					// width
						"280", 					// height
						"9"); 					// minimum version of Flash required						
						so.addParam("wmode", "window");
						so.addParam("allowfullscreen", "true");
						so.addVariable("imagepath", "/IND/French/Images/benefits-of-synthetics.jpg");
						so.addParam("menu", "False");
						flashReplace = so.write("mainContent");  //replace div contents with Flash (IF version is ok).
			 		</script><p xmlns=""><br><span style=" font-size: x-large;"><b>Les avantages des lubrifiants synthétiques</b></span></p><p xmlns=""><span style=" font-size: medium;"><b>Les lubrifiants Mobil SHC&trade; comparés aux huiles minérales : les avantages sont flagrants !</b></span></p><div class="img150 right"><img xmlns="" title="Mobil SHC Benefits" src="/IND/English/Images/150x207_mobilshc_benefits.jpg" longdesc="" border="0" alt="Mobil SHC Benefits"></div><p xmlns="">Mobil SHC a été conçu pour vous offrir des avantages qu&rsquo;aucun lubrifiant minéral ne peut vous apporter. Dans des conditions de service sévères, comme des températures extrêmes, des fortes charges, des pressions élevées, un service nécessitant des arrêts et des redémarrages des machines fréquents, la nécessité d&rsquo;une plage de températures étendue ou encore un service comportant des risques de pollution, Mobil SHC apporte une sécurité accrue dans l&rsquo;utilisation de vos engrenages, compresseurs ou roulements.</p><p xmlns="">Par exemple, la température limite d&rsquo;utilisation de Mobil SHC peut atteindre 50°C &nbsp;plus élevée que la température limite d&rsquo;utilisation d&rsquo;une minérale de haute qualité. En raison d&rsquo;une excellente stabilité thermique et d&rsquo;une résistance à l&rsquo;oxydation incomparable, on observe une moindre formation de dépôts malgré des périodicités de vidange plus longues.</p><p xmlns="">Mobil SHC est également approprié aux applications à basse température, là où les minérales ne peuvent plus être employées car trop visqueuses. Son indice de viscosité élevé lui permet de bien s&rsquo;écouler à très basse température, ce qui permet la formation presque instantanée d&rsquo;un film lubrifiant. Ainsi &nbsp;Mobil SHC &nbsp;apporte une excellente protection contre l&rsquo;usure même aux températures les plus basses.</p><p xmlns="">Tous ces avantages convergent vers un seul objectif : celui d&rsquo;améliorer le rendement énergétique. Comparées aux huiles et aux graisses minérales, les synthétiques favorisent la formation d&rsquo;un film protecteur plus épais en service, ce qui réduit le contact métal sur métal ainsi que les consommations d&rsquo;énergie. En outre, la résistance au mouvement des pièces mécaniques dans l&rsquo;huile est gourmande en énergie : lors des démarrages à froid, les synthétiques disposent d&rsquo;une viscosité plus faible pour le même grade ISO et ont donc besoin de moins d&rsquo;énergie que les huiles et les graisses minérales. Mobil SHC est dotée d&rsquo;un coefficient de traction plus faible et se comporte mieux sous pressions élevées.</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>