<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Mobil&trade; Industrial Lubricants: schémas en fonction de votre secteur d'activité</title><meta name="keywords" content="Schémas, schémas industriels, schémas industriels Mobil&trade;, schémas lubrifiants industriels Mobil&trade;"><meta name="description" content="Choisissez le schéma détaillé de votre secteur d'activité et découvrez les produits Mobil&trade; recommandés ainsi que leurs avantages potentiels en fonction du type d&rsquo;application."><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 6:01:45 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/technicalresources_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><span style=" font-size: x-large;"><b>Schémas</b></span></p><p>Choisissez le schéma détaillé en fonction de votre secteur d'activité.</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3><p><b>Énergie</b><br><a title="" href="yourindustry_energy_coal.aspx">centrale à charbon</a><br><a title="" href="yourindustry_energy_gasengine_heatschematic.aspx">usine de production d&rsquo;énergie par cogénération</a><br><a title="" href="yourindustry_energy_gasengine_gasschematic.aspx">usine de &nbsp;production d&rsquo;énergie par compression de gaz naturel</a><br><a title="" href="yourindustry_energy_gasengine_bioschematic.aspx">usine de production d&rsquo;électricité à partir du biogaz</a><br><a title="" href="yourindustry_energy_gasturbines_schematic.aspx">centrale de &nbsp;production d&rsquo;énergie par turbines à gaz/à vapeur<br></a><a title="" href="yourindustry_energy_nuclear_schematic.aspx">centrale nucléaire</a><br><a title="" href="yourindustry_energy_oilandgas_fpsoschematic.aspx">Navire FPSO</a><br><a title="" href="yourindustry_energy_oilandgas_offshoreschematic.aspx">plate-forme de forage offshore</a><br><a title="" href="yourindustry_energy_oilandgas_onshoreschematic.aspx">plate-forme de forage onshore</a><br><a title="" href="yourindustry_energy_wind_schematic.aspx">éoliennes<br></a>&nbsp;</p><p><b>Pâte à papier et papeterie</b><br><a title="" href="yourindustry_pulpandpaper_plant_schematic.aspx">usine de pâte à papier et papeterie</a></p></div><div class="item right"><h3></h3><p><b>Agroalimentaire</b><br><a title="" href="yourindustry_manufacturing_food_bakery_schematic.aspx">boulangerie</a><br><a title="" href="yourindustry_manufacturing_food_dairy_schematic.aspx">usines de transformation des produits laitiers</a><br><a title="" href="yourindustry_manufacturing_food_meat_schematic.aspx">usine de transformation de la viande</a><br>
&nbsp;</p><p><b>Fabrication</b><br><a title="" href="yourindustry_manufacturing_machining_schematic.aspx">usine de machine de précision</a><br><a title="" href="yourindustry_manufacturing_plastics_schematic.aspx">usine de fabrication et de transformation des matières plastiques</a><br>
&nbsp;</p></div></div><p></p></div><%if(File.Exists(Server.MapPath("technicalresources_schematics2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="technicalresources_schematics2.aspx">2</a></li><li><a href="technicalresources_schematics2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>