
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants pour les industries de la sidérurgie | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Industrie sidérurgique, industrie sidérurgie, industrie métallurgie, industrie métal, graisses industrielles, lubrifiants industriels, équipements industriels, machines industrie, Lubrifiants industriels Mobil, Mobil industrial lubricants"><meta name="description" content="Pour l&rsquo;industrie sidérurgique, vous pouvez compter sur Mobil&trade; Industrial Lubricants pour augmenter la disponibilité de vos équipements et limiter les risques d&rsquo;arrêts non programmés."><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/12/2015 5:13:56 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="feature_680x220_primarymetals_fr_link.html"--></p><p><span style=" font-size: x-large;"><b>Industries de la sidérurgie et de la métallurgie :</b></span></p><p><span style=" font-size: x-large;"><b>pour une productivité à toute épreuve</b></span></p><p><b><span style=" font-size: large;">Solutions et services pour la sidérurgie / métallurgie</span></b></p><p>Le secteur des industries sidérurgiques et métallurgiques est confronté à des défis uniques. Les exigences en termes de productivité des machines n&rsquo;ont jamais été aussi fortes qu&rsquo;aujourd&rsquo;hui. Ainsi, pour rester aussi efficaces et profitables que possible, vos équipements ont besoin de lubrifiants leur permettant d&rsquo;atteindre un niveau exceptionnel de productivité et des performances remarquables dans les environnements les plus difficiles, notamment dans des conditions de températures et charges élevées. Vous pouvez compter sur Mobil&trade; Industrial Lubricants pour optimiser la disponibilité de vos équipements et limiter les risques d&rsquo;arrêts non programmés.</p><p><b>Pour aider à optimiser l'efficacité énergétique</b><br>
Nous partageons les mêmes valeurs quant à l&rsquo;importance de répondre aux exigences de l&rsquo;industrie métallurgique de manière efficace et durable. C&rsquo;est pourquoi la plupart des lubrifiants Mobil&trade; peuvent contribuer aux économies d&rsquo;énergie et à la préservation des ressources grâce à des propriétés exclusives favorisant :<br>
&bull; l&rsquo;efficacité énergétique<br>
&bull; l&rsquo;allongement des intervalles de vidange<br>
&bull; la longévité des équipements</p><p>Notre gamme complète de lubrifiants synthétiques hautes performances pour le secteur de la sidérurgie comprend:*<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; 600</a></b> huiles d&rsquo;engrenage et de circulation de nouvelle génération, favorisant les économies d&rsquo;énergie **<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC&trade; Gear</a></b> huiles pour engrenages de nouvelle génération, permettant l&rsquo;amélioration du rendement énergétique**<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-rarus-shc-1020-series.aspx">Mobil Rarus SHC&trade; 1020</a></b> huiles pour compresseurs d&rsquo;air<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-polyrex-series.aspx">Mobil SHC Polyrex&trade;</a> &nbsp;</b>graisses hautes performances pour roulements<br>
&bull; <b><a title="" href="products_greases_mobilith-shc-grease-series.aspx">Mobilith SHC&trade;</a> &nbsp;</b>graisses synthétiques pour roulements, conçues pour résister aux temperatures élevées<br>
&bull; <b>Mobil Centaur&trade; XHP</b> graisses au sulfonate de calcium recommandées pour les équipements des acieries et les laminoirs<br>
&bull; <b>Mobilgrease XHP&trade;&nbsp;</b>graisses multi-usages au lithium complexe<br>
&bull; <b>Mobil Vacuoline&trade; 100</b> huiles pour paliers lisses dans les systèmes de circulation hydrodynamiques (paliers de cylindres d&rsquo;appui des laminoirs)<br>
&bull; <b>Mobil Vacuoline&trade; 500</b> huiles de circulation conçues pour résister aux conditions de service les plus sévères et destinées à la lubrification des blocs finisseurs de trains à fils (système No-Twist® Rod Mills)</p><p><b>Pour vous offrir toute l&rsquo;expertise de l&rsquo;industrie</b><br>
Conçues pour les équipements du secteur de la sidérurgie et du travail du métal en général, approuvées par la plupart des industriels, nos huiles et graisses satisfont ou dépassent les exigences des constructeurs. Minutieusement testées avant leur mise en place sur le marché, les lubrifiants industriels Mobil répondent à des normes de qualité internationales et sont conformes aux réglementations rigoureuses d&rsquo;ExxonMobil, en termes de fabrication, de service à la clientèle, d&rsquo;analyses, de sécurité, de santé et de respect de l&rsquo;environnement</p><p><b>Pour vous apporter le support technique et client dont vous avez besoin</b><br>
Nos services innovants sont à votre disposition pour vous fournir toute l&rsquo;assistance nécessaire en cas de besoin. &dagger;</p><p><b>Le Support Technique ExxonMobil </b>&ndash; Une assistance technique par téléphone ou messagerie électronique délivrée par nos experts en lubrification qui apportent conseils et réponses à vos questions.</p><p><b>Des Forces de ventes spécialisées</b> &ndash; Un réseau de professionnels de l&rsquo;industrie sidérurgique formés et aptes à prodiguer des conseils sur site dans le but d&rsquo;optimiser la productivité de vos équipements.</p><p><b>Une équipe d&rsquo;Ingénieurs Lubrifiants (FES)</b>&ndash; Une assistance technique proposée par des professionnels de la lubrification dans le but d&rsquo;optimiser les performances des lubrifiants en service, de résoudre les problèmes techniques, d&rsquo;auditer et de prodiguer des conseils et recommandations afin d&rsquo;aider à améliorer la longévité et le rendement de vos machines de production.</p><p><b>Un programme de suivi analytique des huiles en service: Signum<sup>SM</sup></b>&ndash; Il s&rsquo;agit d&rsquo;un suivi des équipements et de leurs lubrifiants afin d&rsquo;améliorer la durée de vie et la fiabilité des machines, tout en réduisant leurs coûts de fonctionnement. Spécifiquement conçu pour suivre l&rsquo;évolution des caractéristiques des charges d&rsquo;huile en service, le programme Signum vous apporte les éléments nécessaires pour mieux connaitre l&rsquo;évolution de l&rsquo;état de vos équipements et lubrifiants.</p><p>Ainsi, vous pouvez compter sur la technologie de pointe et sur l&rsquo;expertise des lubrifiants industriels Mobil pour aider vos machines à produire davantage, plus vite mais aussi mieux, avec de meilleurs rendements énergétiques et une plus grande disponibilité en service de vos équipements.</p><p><span style=" font-size: x-small;">* Les équipements ainsi que les conditions d&rsquo;utilisation sont susceptibles de varier. Veuillez vous référer au manuel des constructeurs.&nbsp;<br>
** Le rendement énergétique se rapporte uniquement aux performances du fluide comparé aux huiles conventionnelles ExxonMobil. Les résultats relatifs au rendement énergétique ont été obtenus à la suite de tests conduits dans le respect des standards et protocoles en vigueur dans l&rsquo;industrie.&nbsp;<br>
&dagger; La disponibilité de ces services dépendent de la zone géographique dans laquelle vous vous situez. Pour plus d&rsquo;informations, veuillez consulter votre distributeur local ExxonMobil.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Schéma du frittage dans l&rsquo;industrie sidérurgique" title="Schéma du frittage dans l&rsquo;industrie sidérurgique" longdesc="" src="/IND/English/Images/teaser_60x60_hot_side_plant_schematic.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelmaterialhandling.pdf">haut fourneau / coulée continue<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Découvrez comment optimiser la productivité de vos équipements de coulée continue</p><p></p></div><div class="item right"><img alt="Schéma du frittage dans l&rsquo;industrie sidérurgique" title="Schéma du frittage dans l&rsquo;industrie sidérurgique" longdesc="" src="/IND/English/Images/teaser_60x60_handling_plant_schematic.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelhotside.pdf">préparation des matières premières<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
Découvrez comment maintenir vos équipements au meilleur de leur forme</p><p></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img alt="Schéma du laminage à froid dans l&rsquo;industrie sidérurgique" title="Schéma du laminage à froid dans l&rsquo;industrie sidérurgique" longdesc="" src="/IND/English/Images/teaser_60x60_forming_plant_schematic.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelmaterialhandling.pdf">laminage<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Découvrez comment optimiser la productivité de vos laminoirs</p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3></div><div class="item right"><h3></h3></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_primarymetals2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_primarymetals2.aspx">2</a></li><li><a href="yourindustry_primarymetals2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>