<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels pour la Fabrication |  Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Lubrifiants Mobil, lubrifiants industriels, l'industrie manufacturière, l'industrie alimentaire et des boissons, l'industrie des matières plastiques, usinage de précision, Mobil industrielle, lubrifiants Mobil industriels"><meta name="description" content="Grâce à Mobil&trade; Industrial Lubricants, stimulez la productivité et l&rsquo;efficacité de vos usines, qu&rsquo;il s&rsquo;agisse d&rsquo;agroalimentaire, de plasturgie ou de machines-outils"><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:54:56 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Usine de fabrication" src="/IND/English/Images/article_150x150_plant_productivity.jpg" longdesc="" border="0" alt="Usine de fabrication"></div><h1><b><span style=" font-size: x-large;">Une productivité qui atteint des sommets</span></b></h1><p><span style=" font-size: large;"><b>Des performances prouvées dans la fabrication d&rsquo;équipements</b></span><br><span style=" font-size: large;"><b>Pour que vos usines atteignent leur niveau de performance optimal&nbsp;</b></span></p><p>Quelle que soit votre production, votre parc de machines est primordial pour votre profitabilité. La défaillance d&rsquo;une ou plusieurs machines peut ralentir votre production et affecter inévitablement votre compétitivité.</p><p>Nous vous proposons une gamme de produits de technologie avancée ainsi qu&rsquo;un panel de services et de programmes innovants initiés par des ingénieurs et des commerciaux hautement qualifiés dont le but est de vous aider à réduire vos coûts d&rsquo;exploitation et à maintenir votre parc de machines à son niveau de performances optimal.<br>
Grâce à Mobil&trade; Industrial Lubricants, stimulez la productivité et l&rsquo;efficacité de vos usines, qu&rsquo;il s&rsquo;agisse d&rsquo;agroalimentaire, de fabrication de pièces plastiques, de machines-outils ou autre.</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Agroalimentaire" src="/IND/English/Images/teaser_90x90_food_and_beverage.jpg" longdesc="" border="0" alt="Agroalimentaire"><h3><a title="" href="yourindustry_manufacturing_food.aspx">industrie agroalimentaire</a></h3><p>Nos lubrifiants vous aident à relever les défis propres à cette industrie.<br><a title="" href="yourindustry_manufacturing_food.aspx">En savoir plus &gt;</a></p><p></p></div><div class="item right"><img title="Plasturgie" src="/IND/English/Images/teaser_90x90_plastics.jpg" longdesc="" border="0" alt="Plasturgie"><h3><a title="" href="yourindustry_manufacturing_plastics.aspx">plastiques</a></h3><p>Grâce à Mobil&trade; Industrial Lubricants, vous pouvez stimuler votre production dans l&rsquo;industrie plastique.<br><a title="" href="yourindustry_manufacturing_plastics.aspx">En savoir plus &gt;</a></p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Usinage" src="/IND/English/Images/teaser_90x90_machine.jpg" longdesc="" border="0" alt="Usinage"><h3><a title="" href="yourindustry_manufacturing_machining.aspx">machines-outils</a></h3><p>Nous proposons des solutions et des services innovants pour les machines-outils de précision.<br><a title="" href="yourindustry_manufacturing_machining.aspx">En savoir plus &gt;</a></p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_manufacturing2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_manufacturing2.aspx">2</a></li><li><a href="yourindustry_manufacturing2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>