<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels pour la Transformation |  Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Lubrifiants Mobil, lubrifiants industriels, usine de transformation, de machines de traitement, lubrifiants Mobil, lubrifiant industriel pour l'usine de traitement"><meta name="description" content="Lubrifiants industriels pour la Transformation |  Mobil&trade; Industrial Lubricants"><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:54:14 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Usines de transformation" src="/IND/English/Images/article_150x150_industry_process.jpg" longdesc="" border="0" alt="Usines de transformation"></div><h1><span style=" font-size: x-large;"><b>Stimulez les performances de</b></span>&nbsp;<span style=" font-size: x-large;"><b>vos usines de transformation</b></span></h1><p><span style=" font-size: large;"><b>Conduisez vos sites de production vers des sommets</b></span>&nbsp;</p><p>Quel qu&rsquo;en soit le type d&rsquo;usine de transformation, nous proposons des lubrifiants de technologie avancée associés à des programmes et des services innovants. Nos équipes d&rsquo;Ingénieurs Lubrifiants sont à votre disposition pour vous aider à choisir les lubrifiants Mobil&trade; Industrial Lubricants adaptés à vos machines et à vos conditions de service, et à améliorer votre productivité.</p><p><br><b>Chimie</b><br>
L&rsquo;industrie chimique est une industrie riche en équipements. Nous savons comment atteindre un niveau de performances optimal en tirant le meilleur parti de vos machines de production. Pour améliorer la productivité, nous vous proposons une vaste gamme de lubrifiants minéraux et synthétiques sans équivalent sur le marché qui pourront protéger efficacement vos compresseurs, accouplements, pompes ainsi que tout autre équipement vital pour la bonne marche de vos usines.</p><p><b>Cimenteries et carrières</b><br>
Les cimenteries et les carrières doivent faire face à des conditions de fonctionnement particulièrement difficiles. Vous pouvez compter sur les gammes de graisses et d'huiles Mobil pour une excelllente protection des organes fortement sollicités et soumis à des températures extrêmes.</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Industrie chimique : tableau de graissage" src="/IND/English/Images/teaser_60x60_chemical_reference_chart.jpg" longdesc="" border="0" alt="Industrie chimique : tableau de graissage"><h3></h3><p><a target="_new" href="/IND/English/files/st_chemical.pdf">Industrie chimique : tableau de graissage<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
Trouvez le lubrifiant industriel adapté à vos besoins<br></p></div><div class="item right"><img title="Cimenterie : tableau de graissage" src="/IND/English/Images/teaser_60x60_cement_reference_chart.jpg" longdesc="" border="0" alt="Cimenterie : tableau de graissage"><h3></h3><p><a target="_new" href="/IND/English/files/st_cement.pdf">cimenterie: tableau de graissage<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
Découvrez les lubrifiants les mieux adaptés à vos machines<br></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_process2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_process2.aspx">2</a></li><li><a href="yourindustry_process2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>