
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels pour turbines à gaz &ndash; Secteur de l&rsquo;énergie | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Moteur à turbine à gaz, rendement de la turbine, l'usine de turbine de puissance, lubrifiants industriels, lubrifiants haute performance"><meta name="description" content="Lubrifiants industriels pour turbines à gaz &ndash; Secteur de l&rsquo;énergie | Mobil&trade; Industrial Lubricants"><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/9/2015 10:06:39 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="feature_680x220_turbines_fr_link.html"--></p><p><span style=" font-size: x-large;"><b>Une productivité qui atteint les sommets</b></span></p><p><span style=" font-size: large;"><b>Stimulez la productivité de vos sites de production pour que vos turbines atteignent leur niveau de performance optimal<br></b></span><br>
Augmentez la productivité de vos sites de production et l&rsquo;efficacité de vos turbines en améliorant la fiabilité et la disponibilité des turbines, grâce à Mobil&trade; Industrial Lubricants. Formulées dans le but d&rsquo;optimiser la production d&rsquo;énergie, ces lubrifiants synthétiques de technologie avancée s&rsquo;appuient sur une expertise, vieille de plus d&rsquo;un siècle, dans le domaine de la lubrification des turbines à gaz. les lubrifiants Mobil&trade; font beaucoup plus que de leur permettre de fonctionner, ils leur permettent de se surpasser.</p><p>Nous mettons à votre disposition une gamme étendue de lubrifiants spécialement formulés pour répondre aux besoins les plus spécifiques. Qu&rsquo;il s&rsquo;agisse d&rsquo;huiles turbines classiques, élaborées dans le but de permettre un fonctionnement sans failles et une longue durée de vie, ou de lubrifiants et graisses synthétiques de dernière génération, conçus pour répondre aux sollicitations extrêmes, les huiles et les graisses Mobil vous aident à maintenir vos sites de production au meilleur de leur forme.</p><p><b>Approuvés par les constructeurs et testés sur le terrain.</b><br>
Testées sur le terrain avant leur mise sur le marché, les huiles et les graisses Mobil Industrial Lubricants sont approuvées par les constructeurs d&rsquo;équipements. Par exemple, <a title="" href="products_mobil-dte-800-series.aspx">Mobil DTE&trade; 800</a>, le lubrifiant de synthèse haut de gamme pour turbines, a été spécialement formulé pour les turbines à cycle combiné. La nouvelle gamme des&nbsp;<br><a title="" href="products_mobil-dte-700-series.aspx">Mobil DTE&trade; 700</a> satisfait ou va au-delà des spécifications relatives aux turbines à gaz et à vapeur de 17 constructeurs et utilisateurs.</p><p><b>Notre Programme Turbines* facilite votre travail.</b><br>
Ce Programme innovant vous aide à préparer le circuit de lubrification de votre turbine et de la charge d&rsquo;huile dans le but de fiabiliser les opérations de révision générale ou de mise en service et de permettre un démarrage des installations en temps et heure. Nous pouvons mettre à votre disposition, afin de vous aider à respecter les recommandations du constructeur et de mettre le suivi en place dès la mise en route de l&rsquo;installation, un Programme complet qui comprend la préconisation du lubrifiant, la préparation de la charge d&rsquo;huile et du circuit de lubrification ainsi que plusieurs autres services.</p><p>Mettons nos forces en commun dans le cadre de notre programme de lubrifiants Mobil pour turbines industrielles pour mettre en place produits et services. Tirez le meilleur parti de notre technologie de pointe et de notre expertise inégalée dans l&rsquo;industrie pour stimuler la productivité de vos installations.</p><p><span style=" font-size: x-small;">*La disponibilité de ce service dépend de la zone géographique. Pour plus d&rsquo;informations, consultez votre interlocuteur local ExxonMobil.</span></p><p><a target="_new" href="http://www.youtube.com/watch?v=Z4MWDrFPkx4">Mobil SHC&trade; et l'histoire d'un succès : Mobil SHC&trade; 824 protège une turbine à gaz Solar pendant plus de 90 000 heures de service</a> (EN)</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Turbines à gaz ou à vapeur" title="Turbines à gaz ou à vapeur" longdesc="" src="/IND/English/Images/teaser_60x60-explore-the-gas-and-steam-turbine-power-plant.jpg" border="0"></img><h3><a title="" href="yourindustry_energy_gasturbines_schematic.aspx">en savoir plus sur les turbines à gaz ou à vapeur</a></h3><p>Visite guidée<br></p></div><div class="item right"><img alt="Brochure sur les turbines à gaz ou à vapeur" title="Brochure sur les turbines à gaz ou à vapeur" longdesc="" src="/IND/English/Images/teaser_60x60-gas-turbine-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/br_gas_turbine_fr.pdf">brochure sur les turbines à gaz<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Découvrez comment nous pouvons protéger les turbines de votre usine<br><br>
&nbsp;</p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Schéma d&rsquo;une turbine à gaz" title="Schéma d&rsquo;une turbine à gaz" longdesc="" src="/IND/English/Images/teaser_60x60-gas-turbine-schematic.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/schm_gas_turbine_fr.pdf">schéma d&rsquo;une turbine à gaz<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Stimulez la productivité de votre usine<br></p></div><div class="item right"><img alt="Mobil DTE&trade; 700 : fiche argumentaire" title="Mobil DTE&trade; 700 : fiche argumentaire" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-dte-700-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/ss_dte_700_fr.pdf">Mobil DTE&trade; 700 : fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Découvrez ce que notre huile turbine haut de gamme peut vous apporter<br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Mobil DTE&trade; 800 : fiche argumentaire" title="Mobil DTE&trade; 800 : fiche argumentaire" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-dte-800-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/ss_dte_800_fr.pdf">Mobil DTE&trade; 800 : fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Protection optimale des turbines à gaz ou à vapeur<br></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_energy_gasturbines2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_energy_gasturbines2.aspx">2</a></li><li><a href="yourindustry_energy_gasturbines2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>