<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels pour centrales nucléaires &ndash; Secteur de l&rsquo;énergie|  Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="L'énergie nucléaire, l'industrie de l'énergie nucléaire, centrale nucléaire, centrale nucléaire, Mobil DTE 700, huile de haute performance, Mobil DTE"><meta name="description" content="Augmentez la productivité de votre centrale nucléaire grâce à la large gamme d&rsquo;huiles et de graisses de technologie avancée Mobil&trade; Industrial Lubricants."><meta name="date" content="02/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:54:31 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="feature_680x220_nuclear_fr_link.html"--></p><p><span style=" font-size: x-large;"><b>Une productivité plus élevée</b></span></p><p><span style=" font-size: large;"><b>Une performance éprouvée pour l&rsquo;énergie nucléiare<br></b></span><br>
Forte d&rsquo;une expertise, vieille de plus d&rsquo;un siècle, dans le domaine de l&rsquo;industrie, notre large gamme d'huiles et de graisses spécialement formulées et de technologie avancée Mobil&trade; Industrial Lubricants peut vous aider à augmenter la productivité de votre centrale nucléaire en améliorant la fiabilité et la disponibilité des équipements. Grâce aux huiles classiques, élaborées dans le but de permettre un fonctionnement sans failles et une longue durée de service, et aux lubrifiants synthétiques de dernière génération, conçus pour répondre aux sollicitations extrêmes, nous pouvons vous aider à maintenir vos centrales nucléaires à un niveau de performance élevé.</p><p>Formulés dans le but d&rsquo;optimiser la production d&rsquo;énergie, ces lubrifiants de technologie avancée s&rsquo;appuient sur une expertise, vieille de plus d&rsquo;un siècle, dans le domaine de la lubrification ainsi que sur une équipe d&rsquo;ingénieurs et de commerciaux dont le but est de vous aider quotidiennement à réduire vos coûts d&rsquo;exploitation.</p><p><b>Approuvés par les constructeurs d&rsquo;équipements et testés sur le terrain.</b><br>
Testés sur le terrain avant leur mise sur le marché, nos lubrifiants bénéficient de nombreuses approbations constructeurs. Par exemple, la nouvelle gamme des <a title="" href="products_mobil-dte-700-series.aspx">Mobil DTE&trade; 700</a> répond ou est supérieure aux specifications relatives aux turbines à gaz et à vapeur de 17 constructeurs et utilisateurs et disposent d&rsquo;un niveau de performances très supérieur aux technologies de génération antérieure.</p><p><b>Notre expertise facilite votre travail.</b><br>
Nous sommes non seulement en mesure de vous proposer une gamme complète de lubrifiants adaptés à l&rsquo;industrie du nucléaire mais également de mettre en place un programme d&rsquo;analyse d&rsquo;huile complet destiné à vous aider à réaliser vos objectifs de maintenance. Le but que nous nous sommes fixés, des évaluations des conditions de vos charges d&rsquo;huile en passant par les propositions d&rsquo;actions correctives au soutien en cas de pannes, est de vous aider à maintenir un niveau de performances fiable. Nous pouvons également vous aider à choisir les lubrifiants les plus adaptés pour vous permettre de renforcer votre programme de maintenance et la fiabilité de vos équipements.</p><p>Mettons nos forces en commun pour mettre en place des produits et services pour vous aider à réduire vos coûts d&rsquo;exploitation et à stimuler vos installations.</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Lubrifiants pour centrales nucléaires" src="/IND/English/Images/teaser_60x60-explore-the-nuclear-power-plant.jpg" longdesc="" border="0" alt="Lubrifiants pour centrales nucléaires"><h3><a title="" href="yourindustry_energy_nuclear_schematic.aspx">centrale nucléaire</a></h3><p>Visite guidée<br></p></div><div class="item right"><img title="Schéma d&rsquo;une centrale nucléaire" src="/IND/English/Images/teaser_60x60-nuclear-plant-schematic.jpg" longdesc="" border="0" alt="Schéma d&rsquo;une centrale nucléaire"><h3><a target="_new" href="/IND/English/files/schm_nuclear.pdf">schéma d&rsquo;une centrale nucléaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Découvrez comment nos lubrifiants sont adaptés à vos besoins<br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Mobil DTE&trade; 700: huile pour turbine à vapeur dans le secteur nucléaire" src="/IND/English/Images/teaser_60x60-mobil-dte-700-fact-sheet.jpg" longdesc="" border="0" alt="Mobil DTE&trade; 700: huile pour turbine à vapeur dans le secteur nucléaire"><h3><a target="_new" href="/IND/French/files/ss_dte_700_fr.pdf">Mobil DTE&trade; 700: fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Découvrez ce que notre huile turbine hautes performances peut faire pour vous<br></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_energy_nuclear2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_energy_nuclear2.aspx">2</a></li><li><a href="yourindustry_energy_nuclear2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>