<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Papeteries et production de pâte à papier | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="papeteries, industrie du papier, productivité des us"><meta name="description" content="Les lubrifiants synthétiques pour machines à papier Mobil SHC&trade; sont des huiles hautes performances, conçues pour satisfaire un large éventail d&rsquo;applications de l&rsquo;industrie papetière."><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 6:01:52 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="feature_680x220_pulpandpaper_fr_link.html"--></p><p><span style=" font-size: x-large;"><b>Au service de la productivité en papeterie</b></span></p><p><span style=" font-size: large;"><b>Lubrifiants synthétiques Mobil SHC&trade; pour machines à papier</b></span></p><p>Que l&rsquo;on produise du papier journal, du papier glacé, du carton ondulé ou de la pâte à papier, la disponibilité des équipements est vitale si l&rsquo;on veut augmenter la productivité. Vos machines doivent produire en continu, et elles peuvent être soumises à des contraintes importantes dans l&rsquo;industrie papetière comme des vitesses de plus de 2 000 m/min et des températures de vapeur supérieures à 200°C (392°F).<br><br>
Notre gamme complète de lubrifiants synthétiques (huiles de circulation Mobil SHC&trade; PM et graisses Mobilith SHC&trade; PM) est conçue pour apporter une bonne lubrification des machines de production de pâte et papier, malgré les conditions de service très sévères rencontrées au sein de cette industrie, et pour couvrir un large éventail d&rsquo;applications en papeterie. Leurs formulations sont à la pointe de la technologie et bénéficient de notre grande expertise de la lubrification. Ces produits synthétiques favorisent une disponibilité accrue des équipements, ce qui peut réduire les arrêts non programmés. Ils ont été élaborés pour contribuer à un allongement significatif de la durée de vie des charges d&rsquo;huile en service, par rapport à celle des lubrifiants classiques d&rsquo;origine minérale.</p><p>En outre, nous disposons d&rsquo;une gamme complete de lubrifiants minéraux et synthétiques haut de gamme pour les machines de production de papiers. Qu&rsquo;ils soient utilisés dans des circuits hydrauliques, dans des compresseurs ou sur des engrenages, ils ont tous été formulés pour répondre aux diverses contraintes de fonctionnements rencontrées dans l&rsquo;industrie du papier et de la pâte à papier.*</p><p>&bull; <b>Mobil SHC PM </b>huiles synthétiques très hautes performances. Application principale sur les circulations, en sécherie et sur les calandres.<br>
&bull; <b>Mobil DTE&trade; PM </b>huiles minérales de haute qualité pour machines à papier. Application principale sur les circulations, en partie humide et en sécherie.<br>
&bull; <b>Mobil DTE Excel&trade; </b>huiles hydrauliques et circulation. Hautes performances. Propriétés anti-usure. Applications sur calandres et en section presse.<br>
&bull; <b><a title="" href="products_mobil-shc_mobilith-shc-pm-series.aspx">Mobilith SHC PM</a> &nbsp;</b>graisses synthétiques très hautes performances pour machines à papier. Applications sur les roulements rencontrés en partie humide et en sécherie.<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC&trade; Gear</a> &nbsp;</b>huiles synthétiques très hautes performances pour réducteurs. Haute protection des engrenages, des roulements et des joints d&rsquo;étanchéité.<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; 600</a> &nbsp;</b>huiles circulation et engrenages, possédant de très hautes performances. Large gamme d&rsquo;applications, même extrêmement sévères.<br>
&bull; <b>Mobilgear SHC&trade; </b>huiles synthétiques dotées de très hautes performances, pour réducteurs et engrenages. Propriétés extrême-pression (EP).<br>
&bull; <b><a title="" href="products_mobilgear-600-xp-series.aspx">Mobilgear&trade; 600 XP</a></b> huiles hautes performances pour réducteurs. Haute protection des engrenages, des roulements et des joints d&rsquo;étanchéité.<br>
&bull; <b><a title="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel&trade;</a></b> huiles hydrauliques anti-usure et à haut indice de viscosité. Excellente résistance au cisaillement.<br>
&bull; <b><a title="" href="products_mobil-dte-20-series.aspx">Mobil DTE&trade; 20</a></b> huiles hydrauliques anti-usure de très haute qualité.</p><p><span style=" font-size: x-small;">* Les équipements et les modalités de fonctionnement varient, s'il vous plaît se référer au manuel constructeur équipement pour les recommandations de lubrification préférés.</span></p><p><b>Des lubrifiants qui bénéficient d&rsquo;une grande expertise industrielle et de nombreuses approbations constructeurs</b><br>
Nos experts lubrifiants travaillent en étroite collaboration avec les utilisateurs industriels et avec les principaux constructeurs d&rsquo;équipements. Il résulte de cette collaboration une grande connaissance des besoins, actuels ou à venir, des professionnels en termes de lubrifiants, ce qui contribue également au développement de nos produits. Les lubrifiants synthétiques Mobil SHC sont notamment connus des industriels pour leurs performances en termes de fiabilité, et reconnus par les principaux constructeurs pour la protection optimale qu&rsquo;ils apportent à leurs équipements.</p><p><b>Etre digne de votre confiance, c&rsquo;est mettre à votre disposition le support technique dont vous avez besoin.</b><br>
Nos différents supports techniques, pour que vous ne soyez jamais seuls.**</p><p><b>Le Support Technique ExxonMobil</b> &ndash; Une assistance technique par téléphone ou messagerie électronique délivrée par nos experts en lubrification qui apportent conseils et réponses à vos questions.</p><p><b>Des Forces de ventes spécialisées</b> &ndash; Un réseau de professionnels de la lubrification formés et aptes à prodiguer des conseils sur site dans le but d&rsquo;optimiser la productivité de vos équipements.</p><p><b>Une équipe d&rsquo;Ingénieurs Lubrifiants (FES)</b>&ndash; Une assistance technique proposée par des professionnels de la lubrification dans le but d&rsquo;optimiser les performances des lubrifiants en service, de résoudre les problèmes techniques, d&rsquo;auditer et de prodiguer des conseils et recommandations afin d&rsquo;aider à améliorer la longévité et le rendement de vos machines de production.</p><p><b>Un programme de suivi analytique des huiles en service: Signum<sup>SM</sup></b>&ndash; Il s&rsquo;agit d&rsquo;un suivi des équipements et de leurs lubrifiants afin d&rsquo;améliorer la durée de vie et la fiabilité des machines, tout en réduisant leurs coûts de fonctionnement. Spécifiquement conçu pour suivre l&rsquo;évolution des caractéristiques des charges d&rsquo;huile en service, le programme Signum&#8480; vous apporte les éléments nécessaires pour mieux connaitre l&rsquo;évolution de l&rsquo;état de vos équipements et lubrifiants.</p><p><span style=" font-size: x-small;">**La disponibilité de ces différents niveaux de service peut varier en fonction de la région dans laquelle vous vous situez. Pour plus d&rsquo;informations, veuillez contacter votre interlocuteur Mobil&trade; habituel.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="production de pâte à papier" src="/IND/English/Images/teaser_60x60_explore_pulp_and_paper_plant.jpg" longdesc="" border="0" alt="production de pâte à papier"><h3></h3><p><a title="" href="yourindustry_pulpandpaper_plant_schematic.aspx">production de pâte à papier</a>&nbsp;<br>
Apprenez à améliorer la productivité de votre usine production de pâte à papier</p><p></p></div><div class="item right"><img title="Mobil SHC PM : fiche argumentaire&nbsp;" src="/IND/English/Images/teaser_60x60_mobilSCH_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobil SHC PM : fiche argumentaire&nbsp;"><h3></h3><p><a target="_new" href="/IND/English/files/ss_shc_pm.pdf">Mobil SHC&trade; PM : fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Découvrez lubrifiants qui aident à protéger les machines à papier<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;industrielle</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Papeterie" src="/IND/English/Images/teaser_60x60_pulp_and_paper_brochure.jpg" longdesc="" border="0" alt="Papeterie"><h3></h3><p><a target="_new" href="/IND/English/files/br_pulp_and_paper.pdf">brochure : production du papier et de la pâte à papier<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Découvrez comment nous pouvons vous aider à garder votre plante en pleine<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;forme</p><p></p></div><div class="item right"><img title="Mobil DTE&trade; PM : fiche argumentaire&nbsp;" src="/IND/English/Images/teaser_60x60_mobilDTE_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobil DTE&trade; PM : fiche argumentaire&nbsp;"><h3></h3><p><a target="_new" href="/IND/English/files/ss_dte_pm.pdf">Mobil DTE&trade; PM : fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Renseignez-vous sur les lubrifiants conçus pour les systèmes de circulation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;de la machine à papier</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Mobilith SHC&trade; PM : fiche argumentaire" src="/IND/English/Images/teaser_60x60_mobilithSHC_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobilith SHC&trade; PM : fiche argumentaire"><h3></h3><p><a target="_new" href="/IND/English/files/ss_mobilith_shc_pm.pdf">Mobilith SHC&trade; PM : fiche argumentaire<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Découvrez comment notre graisses aident à atteindre des performances de<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;pointe</p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_pulpandpaper2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_pulpandpaper2.aspx">2</a></li><li><a href="yourindustry_pulpandpaper2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>