
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels pour moteurs gaz &ndash; Secteur de l&rsquo;énergie|  Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Moteurs à gaz naturel, des lubrifiants de haute performance, Mobil Pegasus, Mobil SHC Pegasus, Mobil Pegasus Series, moteur essence, lubrifiants Mobil, Mobil Pegasus huiles"><meta name="description" content="La gamme Mobil Pegasus&trade; est dotée d&rsquo;une technologie avancée qui permet d&rsquo;optimiser le rendement de vos moteurs gaz et de réduire les coûts de maintenance"><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/9/2015 10:06:37 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="feature_680x220_gasengine_fr_link.html"--></p><p><span style=" font-size: x-large;"><b>Obtenez une amélioration significative des</b></span></p><p><span style=" font-size: x-large;"><b>performances de vos moteurs à gaz</b></span></p><p><span style=" font-size: large;"><b>Conçus pour fonctionner &ndash; Et s&rsquo;ils pouvaient se surpasser ?<br></b></span><br>
ExxonMobil met à votre disposition une gamme de lubrifiants de haute technologie, spécialement formulés pour répondre aux besoins d&rsquo;un panel étendu de moteurs fonctionnant au gaz naturel, y compris les dernières générations de moteurs fixes. Depuis plus de 40 ans, <a title="" href="products_mobil-shc_mobil-shc-pegasus-series.aspx">Mobil Pegasus&trade;</a> met à votre disposition une gamme de lubrifiants de technologie avancée qui peuvent optimiser le rendement des moteurs gaz et réduire les coûts de maintenance.</p><p><a title="" href="products_mobil-pegasus-1005.aspx">Mobil Pegasus&trade; 1005</a>, la dernière génération de la gamme Pegasus formulée et testée sur un grand nombre de moteurs à gaz et sur une très large plage de conditions de fonctionnement, perpétue cette tradition. Résultats : Mobil Pegasus 1005 est conçue pour durer, pour permettre un allongement de la durée de vie des équipements et des intervalles de vidange, tout en réduisant les coûts de maintenance et le nombre d&rsquo;arrêts non programmés. Mobil Pegasus 1005 peut vous permettre de doubler voire tripler les intervalles de vidange.</p><p>Pionnière des huiles pour moteurs à gaz alliant durabilité et efficacité énergétique, Mobil SHC Pegasus a été formulé pour une protection optimale des moteurs à gaz. Elle contient un additif « efficacité carburant » intégré, qui peut également contribuer à réduire les émissions de CO2.</p><p>La gamme de lubrifiants Mobil Pegasus est conçue pour s&rsquo;adapter &nbsp;à tous les types de gaz rencontrés dans les installations de production d&rsquo;énergie.</p><p><b>Approuvés par les constructeurs d&rsquo;équipements et testés sur le terrain.</b><br>
En plus des tests laboratoire et des essais mécaniques, les huiles Mobil Pegasus sont testées sur le terrain avant leur mise sur le marché et approuvées par les constructeurs d&rsquo;équipements. Par exemple, Mobil Pegasus 1005 a été testé sur plus de 40 000 heures sur des moteurs à gaz Caterpillar, Deutz, GE Jenbacher et Waukesha un peu partout à travers le monde. Les essais d&rsquo;augmentation des périodicités de vidange ont montré son étonnante capacité à durer.</p><p>Faites confiance à Mobil&trade; Industrial Lubricants pour vous aider à protéger vos moteurs à gaz.</p><p><a target="_new" href="http://www.youtube.com/watch?v=f5iZUdrs5YA">Mobil SHC&trade; et l'histoire d'un succès : Mobil SHC&trade; Pegasus&trade; protège un moteur Caterpillar pendant plus de 16 000 heures de service</a> (EN)</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Installation de cogénération &nbsp;pour moteurs à gaz: lubrifiants &nbsp;en fonction de &nbsp;l&rsquo;application" title="Installation de cogénération &nbsp;pour moteurs à gaz: lubrifiants &nbsp;en fonction de &nbsp;l&rsquo;application" longdesc="" src="/IND/English/Images/teaser_60x60-explore-the-combined-heat-and-power-plant.jpg" border="0"></img><h3><a title="" href="yourindustry_energy_gasengine_heatschematic.aspx">installation de cogénération</a></h3><p>Découvrez comment nos lubrifiants peuvent vous aider<br></p></div><div class="item right"><img alt="Natural gas engine compression plant lubricants by application" title="Natural gas engine compression plant lubricants by application" longdesc="" src="/IND/English/Images/teaser_60x60-explore-the-natural-gas-compression-plant.jpg" border="0"></img><h3><a title="" href="yourindustry_energy_gasengine_gasschematic.aspx">installation de compression du gaz naturel</a></h3><p>Découvrez comment nous pouvons stimuler votre productivité<br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Biogaz pour moteurs à gaz : lubrifiants en fonction de l&rsquo;application" title="Biogaz pour moteurs à gaz : lubrifiants en fonction de l&rsquo;application" longdesc="" src="/IND/English/Images/teaser_60x60-explore-the-bio-gas-electricity-generation-facility.jpg" border="0"></img><h3><a title="" href="yourindustry_energy_gasengine_bioschematic.aspx">usine de production d&rsquo;électricité à partir du bio-gaz</a></h3><p>Découvrez comment nos lubrifiants sont adaptés à vos besoins<br><br>
&nbsp;</p></div><div class="item right"><img alt="Brochure sur l&rsquo;expertise et l&rsquo;efficacité d&rsquo;une installation de production de moteurs à gaz" title="Brochure sur l&rsquo;expertise et l&rsquo;efficacité d&rsquo;une installation de production de moteurs à gaz" longdesc="" src="/IND/English/Images/teaser_60x60-gas-engine-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/br_gas_engine_fr.pdf">brochure sur les moteurs à gaz<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Maintenez vos moteurs à gaz en bon état de marche<br><br>
&nbsp;</p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Schéma d&rsquo;une installation de cogénération" title="Schéma d&rsquo;une installation de cogénération" longdesc="" src="/IND/English/Images/teaser_60x60-combined-heat-and-power-plant-schematic.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/schm_gas_engine_chp_fr.pdf">schéma d&rsquo;une installation de cogénération<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Visite guidée<br><br>
&nbsp;</p></div><div class="item right"><img alt="Installation de compression de gaz naturel : lubrifiants en fonction de &nbsp;l&rsquo;application" title="Installation de compression de gaz naturel : lubrifiants en fonction de &nbsp;l&rsquo;application" longdesc="" src="/IND/English/Images/teaser_60x60-natural-gas-compression-plant-schematic.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/schm_gas_engine_ngcp_fr.pdf">schéma d&rsquo;un plan de compression du gaz naturel<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Voyez comment nos lubrifiants sont adaptés à votre système<br><br>
&nbsp;</p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Diagramme moteurs à gaz et production d&rsquo;électricité" title="Diagramme moteurs à gaz et production d&rsquo;électricité" longdesc="" src="/IND/English/Images/teaser_60x60-bio-gas-electricity-generation-facility-schematic.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/schm_gas_engine_landfill_fr.pdf">usine de production d&rsquo;électricité à partir du bio-gaz<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Découvrez comment nos lubrifiants sont adaptés à vos besoins<br><br>
&nbsp;</p></div><div class="item right"><img alt="Mobil Pegasus&trade; 1005 : fiche descriptive" title="Mobil Pegasus&trade; 1005 : fiche descriptive" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-pegasus-1005-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/French/files/ss_peg_1005_fr.pdf">Mobil Pegasus&trade; 1005 : fiche descriptive<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Schéma d&rsquo;une installation de compression du gaz naturel<br>
&nbsp;</p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_energy_gasengine2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_energy_gasengine2.aspx">2</a></li><li><a href="yourindustry_energy_gasengine2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>