<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="fr" lang="fr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrifiants industriels en fonction de votre Secteur d&rsquo;activité| Mobil&trade;Industrial Lubricants</title><meta name="keywords" content="Lubrifiants Mobil, lubrifiants industriels, lubrifiants industriels, lubrifiants industriels, machines industrielles, industriels Mobil, Mobil lubrifiants industriels"><meta name="description" content="Les lubrifiants industriels Mobil&trade; ont été conçus pour vous permettre d&rsquo;assurer le bon fonctionnement de vos machines, tout en augmentant la fiabilité et la productivité de vos équipements."><meta name="date" content="10/2013"><meta name="language" content="fr"><meta http-equiv="Content-Language" content="fr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:54:10 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Industrial lubricants factory with Pegasus wings" src="/IND/English/Images/article_150x150_Flying-Industry.jpg" longdesc="" border="0" alt="Industrial lubricants factory with Pegasus wings"></div><h1><b><span style=" font-size: large;">Pourquoi se contenter de peu quand il est possible d&rsquo;avoir le meilleur ?</span></b></h1><p>Notre expérience en lubrification industrielle de plus d&rsquo;un siècle nous a permis d&rsquo;acquérir une expertise et un savoir faire incomparable dans tous les secteurs de l&rsquo;industrie. Les lubrifiants Mobil&trade; ont été conçus pour vous aider à :</p><ul><li>augmenter la fiabilité de vos équipements</li><li>améliorer la sécurité des travailleurs</li><li>réduire les coûts d&rsquo;exploitation</li><li>prolonger la durée de vie de vos machines</li><li>limiter les effets sur l&rsquo;environnement<br></li></ul></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Electricité" src="/IND/English/Images/teaser_90x90_energy_industry.jpg" longdesc="" border="0" alt="Electricité"><h3><a title="" href="yourindustry_energy.aspx">secteur de l&rsquo;énergie</a></h3><p>Au service des industries de production des énergies traditionnelles et renouvelables : les centrales à charbon, les turbines ou moteurs à gaz, les<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;centrales nucléaires ou les<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;éoliennes.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a title="" href="yourindustry_energy.aspx">En savoir plus &gt;</a><br></p></div><div class="item right"><img title="fabrication " src="/IND/English/Images/teaser_90x90_manufacturing_industry.jpg" longdesc="" border="0" alt="fabrication "><h3><a title="" href="yourindustry_manufacturing.aspx">fabrication</a></h3><p>Stimulez la productivité de vos usines &mdash; qu&rsquo;il s&rsquo;agisse d&rsquo;agroalimentaire, d&rsquo;injection plastique, d&rsquo;usinage ou autre.<br><a title="" href="yourindustry_manufacturing.aspx">En savoir plus &gt;</a><br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Carrières, mines, travaux publics" src="/IND/English/Images/teaser_90x90_mining_off_highway.jpg" longdesc="" border="0" alt="Carrières, mines, travaux publics"><h3><a title="" href="yourindustry_mining_offhighway.aspx">carrières, mines, cimenteries et travaux publics</a></h3><p>Pour faire face aux conditions d&rsquo;utilisation très exigeantes des industries extractives, des cimenteries et des travaux publics,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;les lubrifiants industriels Mobil&trade;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;fournissent une protection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;exceptionnelle.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a title="" href="yourindustry_mining_offhighway.aspx">En savoir plus &gt;</a></p><p></p></div><div class="item right"><img title="Papeterie, pâte à papier" src="/IND/English/Images/teaser_90x90_pulp_and_paper.jpg" longdesc="" border="0" alt="Papeterie, pâte à papier"><h3><a title="" href="yourindustry_pulpandpaper.aspx">pâte à papier et papeterie</a></h3><p>Que vous produisiez du papier journal, du papier fin ou du carton ondulé, les lubrifiants industriels Mobil&trade; vous permettent d&rsquo;assurer le bon fonctionnement de vos<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;machines.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a title="" href="yourindustry_pulpandpaper.aspx">En savoir plus &gt;</a></p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Métallurgie et sidérurgie &nbsp;" src="/IND/English/Images/teaser_90x90_primary_metals.jpg" longdesc="" border="0" alt="Métallurgie et sidérurgie &nbsp;"><h3><a title="" href="yourindustry_primarymetals.aspx">métallurgie et sidérurgie</a></h3><p>Les professionnels des industries métallurgique et sidérurgique peuvent compter sur des lubrifiants industriels Mobil&trade; pour produire mieux et plus vite avec ue<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;plus grande efficacité énergétique.&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a title="" href="yourindustry_primarymetals.aspx">En savoir plus &gt;</a></p><p></p></div><div class="item right"><img title="Transformation" src="/IND/English/Images/teaser_90x90_process.jpg" longdesc="" border="0" alt="Transformation"><h3><a title="" href="yourindustry_process.aspx">transformation</a></h3><p>Quel que soit le type d&rsquo;usine de transformation, nous offrons des produits hautes performances associés à des services innovants. &nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;<a title="" href="yourindustry_process.aspx">En savoir plus &gt;</a></p><p></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry2.aspx">2</a></li><li><a href="yourindustry2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>