
				<%@ Page Language="C#"%>
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
				<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>ICCI FUARI  2018 / Mobil Endüstriyel Ya&#287;lar&#305;</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="ICCI, ICCI2018, mobil, endüstriyel, ya&#287;, ya&#287;lar&#305;, mobil shc, enerji, rüzgar, ya&#287;lama çözümleri, üretkenlik, veririmlilik, mobil grease, türbin, di&#351;li"/><meta name="description" content="i&#351;letmelerde üretkenli&#287;i art&#305;ran ve rüzgar türbinlerindeki di&#351;liler için garanti sunan ürünlerimiz ile tan&#305;&#351;mak ve Mobil Endüstriyel Ya&#287;lar&#305;n&#305;n sundu&#287;u avantajlarla ilgili bilgi almak isterseniz"/><meta name="date" content="04-2018"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/imports/js/xom.js"></script>
						<script type="text/javascript" src="/imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="10/9/2018 6:47:26 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/lubricationsolutions_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><img xmlns="" title="ICCI 2017" src="Images/150x68_icci_callout.jpg" longdesc="" border="0" alt="ICCI 2017"><p xmlns=""></p><p xmlns="">ICCI 2018<br><a title="This link will open a new window." target="_new" href="http://www.icci.com.tr/en/visitors/online-registration">Rüzgara güç veriyoruz.<br>
Geli&#351;ime güç veriyoruz.</a></p></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a></p><p xmlns="">Nereden sat&#305;n al&#305;nabilir<br><a title="This link will open a new window." target="_new" href="https://www.mobil.com/en/industrial/lubricants-distributors/externallocator?culture=tr-tr&amp;rendermap=true&amp;renderbutton=false">Size yak&#305;n bir distribütör bulun</a></p></a></div></div></div><div id="mainContent"><br/><img xmlns="" title="Mobil Endüstriyel Ya&#287;lar&#305; ICCI 2018 fuar&#305;nda" src="Images/495x326_ICCI-top-banner.jpg" longdesc="" border="0" alt="Mobil Endüstriyel Ya&#287;lar&#305; ICCI 2018 fuar&#305;nda"><p xmlns=""></p><p xmlns=""><a title="This link will open a new window." target="_new" href="https://www.mobil.com/en/industrial/lubricant-expertise/categories/mobil-serv?q=&amp;pageSize=10&amp;pageNumber=2&amp;selectedFacets=)">Daha fazla bilgi için...</a></p><div class="imgns left"><img xmlns="" title="Mobil SHC Gear 320 WT" src="Images/250x250_SHC-Gear-320-WT.jpg" longdesc="" border="0" alt="Mobil SHC Gear 320 WT"></div><p xmlns=""><br><br><br>
&nbsp;</p><p xmlns=""></p><p xmlns=""><a title="This link will open a new window." target="_new" href="/IND/Turkish/Files/PP-Mobil-SHC-Gear-WT-320.pdf">Rüzgar enerjisi sektöründe öncü Mobil SHC Gear 320 WT sentetik di&#351;li ya&#287;&#305;n&#305;n 7 y&#305;l garantisi ile tan&#305;&#351;&#305;n.<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></p><p xmlns=""><br><br><br><br>
&nbsp;</p><div class="imgns left"><img xmlns="" title="Mobil SHC Pegasus" src="Images/250x250_SHC-Pegasus.jpg" longdesc="" border="0" alt="Mobil SHC Pegasus"></div><p xmlns=""><br><br><br>
&nbsp;</p><p xmlns=""></p><p xmlns=""><a title="" target="" href="/IND/Turkish/products_mobil-shc_mobil-shc-pegasus-series.aspx">Optimum do&#287;al gaz motoru korumas&#305; için geli&#351;tirilmi&#351; ve CO2 emisyonlar&#305;n&#305; azaltmaya yard&#305;mc&#305; olurken yak&#305;t verimlili&#287;ini %1,5*'e kadar artt&#305;rabilen Mobil SHC Pegasus'u ke&#351;fedin.</a></p><p xmlns=""><br><br><br><br>
&nbsp;</p><div class="img150 left"><img xmlns="" title="Mobil DTE 800" src="Images/150x150_DTE-800.jpg" longdesc="" border="0" alt="Mobil DTE 800"></div><p xmlns=""><br><br><br>
&nbsp;</p><p xmlns=""></p><p xmlns=""><a title="" target="" href="products_mobil-dte-800-series.aspx">Mobil DTE&trade; 800 Serisi Yüksek performansl&#305; türbin ya&#287;&#305;n&#305; ke&#351;fedin.</a><br><br><br><br><br>
&nbsp;</p><img xmlns="" title="ICCI 2018" src="Images/495x282_ICCI-bottom-banner.jpg" longdesc="" border="0" alt="ICCI 2018"><p xmlns=""><br><br><br>
&nbsp;</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>