
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>Endüstriyel Uzmanlar | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="sanayi uzmanlar&#305;, petrol endüstrisi uzmanlar&#305;, endüstriyel ya&#287;lama uzmanlar, petrol uzmanlar"/><meta name="description" content="Mobil&trade; markal&#305; endüstriyel ya&#287;lar makinelerden en yüksek performans&#305; almak üzere ya&#287; endüstrisinde lider bir kapasite sunar. Ya&#287; uzmanlar&#305;m&#305;z&#305;n beklentileri nas&#305;l a&#351;t&#305;&#287;&#305;n&#305; ö&#287;renin."/><meta name="date" content="11/2013"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:00 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/ourbusiness_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/Search.aspx?chooseLanguage=tr">Ürün veri sayfas&#305; (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Malzeme güvenlik veri sayfas&#305; (MSDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Nereden sat&#305;n al&#305;nabilir<br><a title="" target="" href="distributorlocator.aspx">Size yak&#305;n bir distribütör bulun</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/Apps/ILS/Default_EN.aspx"><img xmlns="" title="Looble" src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx"></a>Looble<sup>SM</sup> ürün seçici (EN)<br><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx">Uygulaman&#305;z için do&#287;ru ya&#287;&#305; bulun</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Endüstriyel Uzmanlar" src="/IND/English/Images/article_150x150_productivity-expertise.jpg" longdesc="" border="0" alt="Endüstriyel Uzmanlar"></div><p xmlns=""><span style=" font-size: x-large;"><b>Endüstriyel Ya&#287; ve Ya&#287;lama</b></span></p><p xmlns=""><span style=" font-size: x-large;"><b>Uzmanlar&#305;</b></span><br><br>
Medeniyet g&#305;dadan ta&#351;&#305;mac&#305;l&#305;&#287;a ve in&#351;aat malzemelerine kadar sanayi ürünlerine ba&#287;l&#305;d&#305;r. Üreticiler bu talebi kar&#351;&#305;lamak için makinelere güvenirler. Yüksek performansl&#305; ya&#287;lar ve s&#305;n&#305;f&#305;n&#305;n en iyisi olan ya&#287;lama uygulamalar&#305; makinelerin güvenilir &#351;ekilde ve en üst düzeyde çal&#305;&#351;mas&#305;n&#305; sa&#287;lamakta büyük önem ta&#351;&#305;r.</p><p xmlns="">Hem yüksek performansl&#305; ya&#287;lar geli&#351;tirerek size sunmada hem de sa&#287;l&#305;kl&#305; ya&#287;lama uygulamalar&#305;n&#305; kullanarak makinelerinizden yüksek performans elde etmenize destek olmada mükemmeliz.</p><p xmlns="">Mühendislerimizin, ekipman üreticileriyle yak&#305;ndan çal&#305;&#351;ma yoluyla elde etti&#287;i bilgiler ya&#287; formülleri ve programlar&#305;m&#305;za entegre edilir.</p><ul xmlns=""><li>Mevcut ve gelecekteki ya&#287; gereksinimlerinin yan&#305;s&#305;ra ekipman trendlerini de anlamak</li><li>Ya&#287;lama sistemi tasar&#305;m&#305; konusunda dan&#305;&#351;mak</li><li>Saha ya&#287;lama sorunlar&#305;n&#305;n giderilmesine yard&#305;m etmek</li></ul><p xmlns="">Ara&#351;t&#305;rma mühendislerimizin ekipman üreticileriyle yak&#305;n i&#351;birli&#287;i içerisinde çal&#305;&#351;arak elde etti&#287;i bilgiler ya&#287; formülasyonlar&#305;m&#305;za aktar&#305;l&#305;r.</p><p xmlns="">Bilgili Saha Mühendisli&#287;i Hizmetleri (FES) ekibimiz, mü&#351;terilerimizi çal&#305;&#351;malar&#305; geli&#351;tirecek ve bak&#305;m uygulamalar&#305;n&#305; kolayla&#351;t&#305;racak programlar ve uygulamalar&#305;n hayata geçirilmesinde desteklemeye yard&#305;mc&#305; olur. Daha aç&#305;k bir ifadeyle, mü&#351;terilerin a&#351;a&#287;&#305;daki hedefleri gerçekle&#351;tirerek, rekabetçiliklerini geli&#351;tirmesi ve i&#351; hedeflerine ula&#351;mas&#305;n&#305; sa&#287;lamak için a&#351;a&#287;&#305;daki konularda yard&#305;mc&#305; olurlar:</p><ul xmlns=""><li>Ekipman ömrünün uzat&#305;lmas&#305;</li><li>Hizmet d&#305;&#351;&#305; kalma süresinin, özellikle de plans&#305;z olanlar&#305;n, azalt&#305;lmas&#305;</li><li>Ya&#287; de&#287;i&#351;im aral&#305;klar&#305;n&#305;n uzat&#305;lmas&#305;</li><li>Ya&#287;, enerji ve ekipman israf&#305;n&#305;n minimuma indirilmesi</li></ul><p xmlns=""><br>
&nbsp;</p><p xmlns="">&nbsp;</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>