
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>ExxonMobil Endüstriyel Ya&#287;lar&#305; Hakk&#305;nda | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Mobil marka ya&#287;lar, yüksek performansl&#305; ya&#287;lar, ileri teknoloji ya&#287;lar, endüstriyel verimlilik, endüstriyel verimlilik, endüstriyel ya&#287;lama"/><meta name="description" content="Mobil&trade; markal&#305; endüstriyel ya&#287;lar endüstriyel ekipman üretkenli&#287;inize yard&#305;mc&#305; olmak üzere yüksek performansl&#305; ya&#287;lar ve endüstri deneyimi sa&#287;lar."/><meta name="date" content="11/2013"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:28:19 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/ourbusiness_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/Search.aspx?chooseLanguage=tr">Ürün veri sayfas&#305; (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Malzeme güvenlik veri sayfas&#305; (MSDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Nereden sat&#305;n al&#305;nabilir<br><a title="" target="" href="distributorlocator.aspx">Size yak&#305;n bir distribütör bulun</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/Apps/ILS/Default_EN.aspx"><img xmlns="" title="Looble" src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx"></a>Looble<sup>SM</sup> ürün seçici (EN)<br><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx">Uygulaman&#305;z için do&#287;ru ya&#287;&#305; bulun</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Mobil markal&#305; endüstriyel ya&#287;lar hakk&#305;nda" src="/IND/English/Images/article_150x150_our_business.jpg" longdesc="" border="0" alt="Mobil markal&#305; endüstriyel ya&#287;lar hakk&#305;nda"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobil&trade; markal&#305; endüstriyel</b></span></p><p xmlns=""><span style=" font-size: x-large;"><b>ya&#287;lar hakk&#305;nda</b></span><br><br><span style=" font-size: large;"><b>Mobil markal&#305; endüstriyel ya&#287;lar ile üretkenli&#287;i uçurun<br></b></span><br>
Dünya çap&#305;nda endüstri deneyimiyle desteklenen yüksek performansl&#305; ya&#287;lar.</p><p xmlns="">On y&#305;llard&#305;r mü&#351;terilere yeni ekipman üretkenli&#287;i seviyeleri getirmeye yard&#305;mc&#305; olmak üzere önde gelen ya&#287;lar ve derinlemesine endüstri deneyimi konular&#305;nda iyi tan&#305;n&#305;r hale geldik.</p><p xmlns="">Oldukça deneyimli mühendislerimiz, ekipman trendleri ve ya&#287;lama gereksinimleri hakk&#305;nda lider ekipman üreticileriyle beraber çal&#305;&#351;&#305;rlar. Bu bilgiler ara&#351;t&#305;rmac&#305; kimyagerlerimiz ve ya&#287; formülü geli&#351;tiricilerimize en zorlu uygulamalardan baz&#305;lar&#305; için etkin, en son teknolojiye sahip ya&#287;lar konusunda yön göstermeye yard&#305;mc&#305; olur.</p><p xmlns="">Saha Mühendisli&#287;i Hizmetleri (FES) tak&#305;m&#305;m&#305;z size yerinde ya&#287;lama uygulamalar&#305;, do&#287;ru ya&#287; seçimi, ekipman sorun giderme ve ekipman&#305;n&#305;z&#305;n daha uzun süre çal&#305;&#351;mas&#305;n&#305; sa&#287;layabilecek di&#287;er ya&#287;lama hizmetleri üzerine tavsiye verir.</p><p xmlns="">ExxonMobil Yak&#305;tlar&#305; ve Ya&#287;lar&#305; (F&amp;L) bölümünün bir parças&#305; olarak Mobil markal&#305; endüstriyel ya&#287;lar ekibi günümüzün global pazar&#305;nda yenilikçi ya&#287; ve özel ürünler ve sürdürülebilirlikle ilgili faydalar&#305; desteklemeye yard&#305;mc&#305; olan hizmetlerle sürdürülebilirlik taahhüdünü payla&#351;&#305;r.</p><p xmlns=""><a target="" href="http://www.exxonmobil.com/lubes/sustainability.aspx">ExxonMobil'in sürdürülebilirlik taahhüdü hakk&#305;nda daha fazla bilgi.</a></p><p xmlns="">&nbsp;</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>