
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>Mobilgrease XHP&trade; 681 Mine - Madencilik Endüstrisi | Mobil Endüstriyel Ya&#287;lar&#305;</title><meta name="keywords" content="Mobilgrease XHP, Mobilgrease XHP 681 Mine, Mobilgrease mine serisi, lityum kompleksli gres, madencilik endüstrisi, mobilgrease ya&#287;lar, gres ya&#287;lamas&#305;"/><meta name="description" content="Mobilgrease XHP&trade;  681 Mine, zorlu yol d&#305;&#351;&#305;, madencilik ortam&#305;nda uzmanla&#351;m&#305;&#351; gres ya&#287;lamas&#305; için Mobilgrease&trade; markas&#305;n&#305;n önde gelen bir üyesidir."/><meta name="date" content="10/2013"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="7/24/2014 8:36:32 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=tr&amp;CountryValue=">Ürün veri sayfas&#305; (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Malzeme güvenlik veri sayfas&#305; (MSDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a><br>
Nereden sat&#305;n al&#305;nabilir<br><a title="" target="" href="distributorlocator.aspx">Size yak&#305;n bir distribütör bulun</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="https://www.mobil.com/en/industrial/lubricants/search"><img xmlns="" title="Looble" src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><a title="This link will open a new window." target="_new" href="https://www.mobil.com/en/industrial/lubricants/search"></a><br>
Looble<sup>SM</sup> ürün seçici (EN)<br><a title="This link will open a new window." target="_new" href="https://www.mobil.com/en/industrial/lubricants/search">Uygulaman&#305;z için do&#287;ru ya&#287;&#305; bulun</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Mobilgrease XHP 681 mine ya&#287;&#305; di&#351;liler etraf&#305;nda s&#305;çr&#305;yor" src="/IND/English/Images/article_150x150_mobil-xhp-681.jpg" longdesc="" border="0" alt="Mobilgrease XHP 681 mine ya&#287;&#305; di&#351;liler etraf&#305;nda s&#305;çr&#305;yor"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobilgrease XHP&trade; 681 Mine</b></span></p><p xmlns=""><span style=" font-size: large;"><b>Madencilik endüstrisinde kullan&#305;lan yol d&#305;&#351;&#305; ekipman için uzman gres</b></span><br><br>
Mobilgrease XHP 681 Mine son teknolojiye sahip yenilik ve mükemmel performansla tan&#305;nm&#305;&#351; Mobilgrease&trade; marka ürünlerin önde gelen bir üyesidir.</p><p xmlns="">En son lityum kompleks teknolojisiyle formüle edilen Mobilgrease XHP 681 Mine a&#287;&#305;r yol d&#305;&#351;&#305; madencilik ortam&#305;nda ba&#351;ar&#305;l&#305; gres ya&#287;lamas&#305; için çok önemli &#305;slak kesme dayan&#305;m&#305; ve su direnci sa&#287;lamak üzere polimerle güçlendirilmi&#351; bir omurga ve ISO 680 viskozitesi kullan&#305;r.</p><p xmlns=""><b>Geni&#351;letilmi&#351; hizmet</b><br>
Mobilgrease XHP 681'in iyi suyla y&#305;kanma, su spreyine direnç &#351;eklinde uzat&#305;lm&#305;&#351; servis kapasitesi ve istisnai durma gücü mevcuttur ve konvansiyonel s&#305;zd&#305;rmazl&#305;k malzemeleri ile uyumludur. Tüm Mobilgrease marka ya&#287;lar gibi dünya çap&#305;nda teknik destek personelimizce desteklenir.</p><p xmlns="">&nbsp;<a title="This link will open a new window." target="_new" href="/IND/English/files/mobilgrease-xhp-mine-series.pdf">Mobilgrease XHP&trade; Di&#351;li veri sayfas&#305;<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)</p><p xmlns="">&nbsp;<a title="This link will open a new window." target="_new" href="/IND/English/files/mining-industry-machinery-efficiency-brochure.pdf">Madencilik Bro&#351;ürü<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>
