
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>Endüstriyel Gresler - Mobilgrease&trade; XTC | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Yüksek performansl&#305; gres, Mobilgrease, Mobilgrease XTC, yüksek s&#305;cakl&#305;kl&#305; di&#351;li, iletken kaplin uygulamalar&#305;, kaplin ya&#287;lamas&#305; , yüksek viskoziteli mineral ya&#287;"/><meta name="description" content="Mobilgrease&trade; XTC yüksek h&#305;zl&#305; ve yüksek s&#305;cakl&#305;kta di&#351;li ve iletken kaplin uygulamalar&#305;n&#305;n mükemmel ya&#287;lanmas&#305;n&#305; sa&#287;lamakla tan&#305;nm&#305;&#351;t&#305;r."/><meta name="date" content="10/2013"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:43 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/Search.aspx?chooseLanguage=tr">Ürün veri sayfas&#305; (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Malzeme güvenlik veri sayfas&#305; (MSDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a>Nereden sat&#305;n al&#305;nabilir<br><a title="" target="" href="distributorlocator.aspx">Size yak&#305;n bir distribütör bulun</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/Apps/ILS/Default_EN.aspx"><img xmlns="" title="Looble" src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx"></a>Looble<sup>SM</sup> ürün seçici (EN)<br><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx">Uygulaman&#305;z için do&#287;ru ya&#287;&#305; bulun</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Mobilgrease XTC ya&#287;&#305; di&#351;li yata&#287;&#305; ya&#287;&#305;na yüklenmi&#351;" src="/IND/English/Images/article_150x150_mobil-xtc.jpg" longdesc="" border="0" alt="Mobilgrease XTC ya&#287;&#305; di&#351;li yata&#287;&#305; ya&#287;&#305;na yüklenmi&#351;"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobilgrease&trade; XTC</b></span><br><br><span style=" font-size: large;"><b>Yüksek h&#305;zl&#305; kaplinler için yüksek performansl&#305; gres<br></b></span><br>
Mobilgrease XTC AGMA CG-1 ve CG-2 spesifikasyonlar&#305; dahil, yüksek h&#305;zl&#305; ve yüksek s&#305;cakl&#305;kta di&#351;li ve iletken kaplin uygulamalar&#305;n&#305;n mükemmel ya&#287;lamas&#305;n&#305; sa&#287;lamakla tan&#305;nm&#305;&#351;t&#305;r. Mobilgrease XTC'nin üstün kalitesi özellikle performans temel bir endi&#351;e oldu&#287;unda birçok kullan&#305;c&#305;n&#305;n tercihi haline gelmesine neden olmu&#351;tur.<br><br><b>Dü&#351;ük bula&#351;ma ve yüksek s&#305;cakl&#305;k stabilitesi</b><br>
Yüksek viskoziteli mineral bazl&#305; ya&#287; ve çok verimli bir kat&#305;k paketiyle üretilen Mobilgrease XTC modern kaplin ya&#287;lamas&#305; ve korunmas&#305; için çok önemli özellikleri olan dü&#351;ük s&#305;zma ve ayr&#305;ca yüksek s&#305;cakl&#305;k stabilitesi sa&#287;lamak üzere tasarlanm&#305;&#351;t&#305;r.</p><p xmlns="">Orijinal ekipman üreticileriyle (OEM'ler) ve son kullan&#305;c&#305;larla yak&#305;n temas&#305;m&#305;z Mobilgrease XTC'nin kritik uygulama gereksinimlerinizi kar&#351;&#305;lamas&#305;n&#305; garanti eder.</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>