
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="tr" lang="tr"><head><title>Endüstriyel Ya&#287;lar - Mobil Dynagear&trade; Serisi | Mobil&trade; Endüstriyel Ya&#287;lar&#305;</title><meta name="keywords" content="Mobil markal&#305; ya&#287;lar, yüksek performans ya&#287;lar&#305;, di&#351;li ya&#287;lar&#305;, di&#351;li ya&#287;&#305;"/><meta name="description" content="Mobil Dynagear&trade; yüksek performans ya&#287;lar&#305; çok çe&#351;itli çal&#305;&#351;ma ko&#351;ullar&#305;na maruz kalan a&#287;&#305;r yüklü aç&#305;k di&#351;li setlerine koruma sa&#287;lamak üzere tasarlanm&#305;&#351;t&#305;r."/><meta name="date" content="10/2013"/><meta name="language" content="tr"/><meta http-equiv="Content-Language" content="tr"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
            <script type="text/javascript" src="/Imports/js/swfobject.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="7/24/2014 9:14:09 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/products_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="products_mobil-shc.aspx"><img xmlns="" title="Mobil SHC" src="/IND/English/Images/150x68_sidecallouts_mobilshc.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><a title="" target="" href="products_mobil-shc.aspx"></a> Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/search.aspx?chooseLanguage=tr&amp;CountryValue=">Ürün veri sayfas&#305; (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Malzeme güvenlik veri sayfas&#305; (MSDS)</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="distributorlocator.aspx"><img xmlns="" title="Nereden sat&#305;n al&#305;nabilir" src="/IND/English/Images/150x68_sidecallouts_where_to_buy.jpg" longdesc="" border="0" alt="Nereden sat&#305;n al&#305;nabilir"><p xmlns=""><a title="" target="" href="distributorlocator.aspx"></a><br>
Nereden sat&#305;n al&#305;nabilir<br><a title="" target="" href="distributorlocator.aspx">Size yak&#305;n bir distribütör bulun</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="/Apps/ILS/Default_EN.aspx"><img xmlns="" title="Looble" src="/IND/English/Images/150x68_sidecallouts_looble1.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx"></a><br>
Looble<sup>SM</sup> ürün seçici (EN)<br><a title="This link will open a new window." target="_new" href="/Apps/ILS/Default_EN.aspx">Uygulaman&#305;z için do&#287;ru ya&#287;&#305; bulun</a></p></a></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Madencilik endüstrisi için Mobil Dynagear serisi kepçeli kamyon" src="/IND/English/Images/article_150x150-mobil-dynagear-series.jpg" longdesc="" border="0" alt="Madencilik endüstrisi için Mobil Dynagear serisi kepçeli kamyon"></div><p xmlns=""><span style=" font-size: x-large;"><b>Mobil Dynagear&trade; Serisi</b></span></p><p xmlns=""><span style=" font-size: large;"><b>Aç&#305;k di&#351;liler için çok amaçl&#305; ya&#287;<br></b></span><br>
Mobil Dynagear yüksek performansl&#305; aç&#305;k di&#351;li ya&#287;lar&#305; özellikle madencilik endüstrisinde görülenler olmak üzere çok çe&#351;itli çal&#305;&#351;ma ko&#351;ullar&#305;na maruz kalan a&#287;&#305;r yüklü aç&#305;k di&#351;li setlerine ola&#287;anüstü koruma sa&#287;lamak üzere tasarlanm&#305;&#351;t&#305;r.</p><p xmlns=""><b>A&#351;&#305;r&#305; performans</b><br>
Bu ya&#287;lar ola&#287;anüstü a&#351;&#305;r&#305; bas&#305;nç/ a&#351;&#305;nma önleme performans&#305; sunar ve zorlu su spreyi, toz ve kir ve yüksek ve dü&#351;ük s&#305;cakl&#305;klar ko&#351;ullar&#305;nda bile yerinde kal&#305;r. Mobil Dynagear Serisinin tüm ürünleri solvent içermeyen &#351;ekilde formüle edilmi&#351;tir ve herhangi bir klorin veya hidrokarbon çözücü kullan&#305;lmadan mükemmel da&#287;&#305;t&#305;labilirlik sunar.</p><p xmlns="">&nbsp;<a title="This link will open a new window." target="_new" href="/IND/English/files/mining-industry-machinery-efficiency-brochure.pdf">Madencilik Bro&#351;ürü<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>