<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Endüstriyel Ya&#287;lar ve Teknik Deste&#287;i | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Makine bak&#305;m&#305;, endüstriyel ya&#287; teknik çözümleri, endüstriyel ya&#287; teknik problemleri, endüstriyel ya&#287; teknik deste&#287;i, endüstriyel ya&#287; teknik yard&#305;m&#305;"><meta name="description" content="Makine bak&#305;m&#305;, olas&#305; problemler ve Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar&#305;n nas&#305;l gereksinimlerinizi çözümleyecek &#351;ekilde formüle edildi&#287;i hakk&#305;nda daha fazla bilgi."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:10 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/technicalresources_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1><span style=" font-size: x-large;"><b>Size çal&#305;&#351;mak için deneyimlerimizi sunuyoruz&nbsp;</b></span></h1><p>Makineleriniz, olas&#305; problemler ve Mobil&trade; markal&#305; endüstriyel ya&#287;lar'&#305;n nas&#305;l gereksinimlerinizi çözümleyecek &#351;ekilde formüle edildi&#287;i hakk&#305;nda daha fazla bilgi.</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Endüstriyel ya&#287;lar vaka çal&#305;&#351;malar&#305;" src="/IND/English/Images/teaser_90x90_case_study_videos.jpg" longdesc="" border="0" alt="Endüstriyel ya&#287;lar vaka çal&#305;&#351;malar&#305;"><h3><a title="" href="technicalresources_case-studies.aspx">vaka çal&#305;&#351;malar&#305;</a></h3><p>Endüstrinin zorluklar&#305; için nas&#305;l çözümler yaratt&#305;&#287;&#305;m&#305;z&#305; ö&#287;renin.</p><p></p></div><div class="item right"><img title="Endüstriyel ya&#287; uzman&#305; teknik deste&#287;i" src="/IND/English/Images/teaser_90x90_technical_topics.jpg" longdesc="" border="0" alt="Endüstriyel ya&#287; uzman&#305; teknik deste&#287;i"><h3><a title="" href="technicalresources_technical-topics.aspx">teknik konular</a></h3><p>Makineleriniz ve Mobil&trade; endüstriyel ya&#287;lar&#305;n&#305;n nas&#305;l gereksinimlerinizi çözümleyecek &#351;ekilde formüle edildi&#287;i hakk&#305;nda daha fazla bilgi.</p><p></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img title="&#351;emalar" src="/IND/English/Images/teaser_90x90_schematics.jpg" longdesc="" border="0" alt="&#351;emalar"><h3><a title="" href="technicalresources_schematics.aspx">&#351;emalar</a></h3><p>Endüstriniz için ayr&#305;nt&#305;l&#305; &#351;emay&#305; seçin</p></div><div class="item right"><h3></h3></div></div><p></p></div><p><br>
&nbsp;</p><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("technicalresources2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="technicalresources2.aspx">2</a></li><li><a href="technicalresources2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>