<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Endüstriniz için &#350;emalar | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="&#351;emalar, endüstriyel &#351;emalar, mobil endüstriyel &#351;emalar&#305;, mobil endüstriyel ya&#287; &#351;emalar&#305;"><meta name="description" content="Endüstriniz için ayr&#305;nt&#305;l&#305; &#351;emay&#305; seçin ve her uygulama için hangi Mobil ürünlerinin önerildi&#287;ini olas&#305; faydalar&#305; ile birlikte görün."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:31 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/technicalresources_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><span style=" font-size: x-large;"><b>&#350;emalar</b></span></p><p>Endüstriniz için ayr&#305;nt&#305;l&#305; &#351;emay&#305; seçin</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3><p><b>Enerji</b><br><a title="" href="yourindustry_energy_coal.aspx">kömür yak&#305;tl&#305; termik santral</a><br><a title="" href="yourindustry_energy_gasengine_heatschematic.aspx">kombine &#305;s&#305; ve güç santrali</a><br><a title="" href="yourindustry_energy_gasengine_gasschematic.aspx">do&#287;algaz bas&#305;nçland&#305;rma istasyonu</a><br><a title="" href="yourindustry_energy_gasengine_bioschematic.aspx">biyogaz elektrik üretim tesisi</a><br><a title="" href="yourindustry_energy_gasturbines_schematic.aspx">gaz ve buhar türbini santrali</a><br><a title="" href="yourindustry_energy_nuclear_schematic.aspx">nükleer santral</a><br><a title="" href="yourindustry_energy_oilandgas_fpsoschematic.aspx">FPSO gemisi</a><br><a title="" href="yourindustry_energy_oilandgas_offshoreschematic.aspx">aç&#305;k deniz sondaj kulesi</a><br><a title="" href="yourindustry_energy_oilandgas_onshoreschematic.aspx">karada sondaj tesisi</a><br><a title="" href="yourindustry_energy_wind_schematic.aspx">rüzgar türbini<br></a>&nbsp;</p><p><b>Ka&#287;&#305;t hamuru ve ka&#287;&#305;t</b><br><a title="" href="yourindustry_pulpandpaper_plant_schematic.aspx">ka&#287;&#305;t hamuru ve ka&#287;&#305;t tesisi</a></p></div><div class="item right"><h3></h3><p><b>G&#305;da ve içecek</b><br><a title="" href="yourindustry_manufacturing_food_bakery_schematic.aspx">unlu mamul</a><br><a title="" href="yourindustry_manufacturing_food_dairy_schematic.aspx">süt ürünleri tesisi</a><br><a title="" href="yourindustry_manufacturing_food_meat_schematic.aspx">et i&#351;leme tesisi</a><br>
&nbsp;</p><p><b>Üretim</b><br><a title="" href="yourindustry_manufacturing_machining_schematic.aspx">hassas i&#351;leme tesisi</a><br><a title="" href="yourindustry_manufacturing_plastics_schematic.aspx">plastik tesisi</a></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("technicalresources_schematics2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="technicalresources_schematics2.aspx">2</a></li><li><a href="technicalresources_schematics2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>