<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Ka&#287;&#305;t ve Ka&#287;&#305;t Hamuru Endüstrisi Ya&#287;lar&#305; | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar </title><meta name="keywords" content="ka&#287;&#305;t ve ka&#287;&#305;t hamuru endüstrisi, ka&#287;&#305;t makine ya&#287;&#305;, endüstriyel ya&#287;lar, Mobil endüstriyel ya&#287;lar&#305;, Mobil SHC PM serisi, Mobilith SHC, Mobilgear, Mobilith SHC"><meta name="description" content="Mobil SHC sentetik Ka&#287;&#305;t Makinesi ya&#287;lar&#305; çok çe&#351;itli ka&#287;&#305;t hamuru ve ka&#287;&#305;t endüstrisi uygulamalar&#305;nda tatminkar performans göstermek üzere tasarlanm&#305;&#351; yüksek performansl&#305; ya&#287;lar sa&#287;lar."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:26:55 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_pulpandpaper_link.html"--></p><p><span style=" font-size: x-large;"><b>Üretkenli&#287;i ka&#287;&#305;t hamuruna ve ka&#287;&#305;da çevirin</b></span></p><p><span style=" font-size: large;"><b>Mobil SHC&trade; sentetik Ka&#287;&#305;t Makinesi (PM) ya&#287;lar&#305;</b></span></p><p>&#304;ster gazete ka&#287;&#305;d&#305;, ister birinci hamur ka&#287;&#305;t, ya da oluklu mukavva üretin, ekipmanlar&#305;n kullan&#305;labilir durumda bulunabilirli&#287;i üretkenli&#287;in maksimize edilmesinde hayati öneme sahiptir. Makinelerinizin sürekli olarak üretmesine ihtiyac&#305;n&#305;z vard&#305;r. Ve, 2.000 m/dk üzerinde h&#305;zlarda ve 200°C&rsquo;yi (392°F) a&#351;an buhar s&#305;cakl&#305;klar&#305;nda çal&#305;&#351;an ka&#287;&#305;t makineleri ile, ka&#287;&#305;t hamuru ve ka&#287;&#305;t endüstrisindeki ekipman&#305;n&#305;z büyük bir bask&#305; alt&#305;ndad&#305;r.</p><p><b>Mobil SHC&trade; PM Serisi ve Mobilith SHC&trade; PM Serisi &nbsp;</b><br>
Üstün performansl&#305; sentetik sirkülasyon ya&#287;&#305; ve gresleri ailemizin tamam&#305; geni&#351; ka&#287;&#305;t hamuru ve ka&#287;&#305;t uygulamalar&#305; ve ko&#351;ullar&#305; aral&#305;&#287;&#305;nda tatminkar performans verecek &#351;ekilde tasarlanm&#305;&#351;t&#305;r.</p><p>En son sentetik ya&#287; teknolojisi ve uygulama uzmanl&#305;&#287;&#305; ile formüle edilen bu ürünler, ar&#305;za nedeniyle çal&#305;&#351;amama süresini ve i&#351;letim giderlerini minimuma indirebilirler. Geleneksel mineral ya&#287;a göre çok daha uzun süre i&#351;ba&#351;&#305;nda kalacak &#351;ekilde tasarlanm&#305;&#351;lard&#305;r.</p><p>Ayr&#305;ca hepsi ka&#287;&#305;t hamuru ve ka&#287;&#305;t i&#351;leme için çe&#351;itli çal&#305;&#351;t&#305;rma ortamlar&#305; için tasarlanm&#305;&#351; olarak hidrolik, kompresör ve di&#351;li ya&#287;lar&#305; dahil ka&#287;&#305;t makineleri için güçlü bir sentetik ve üstün mineral ya&#287; bazl&#305; ya&#287; serisi sunar&#305;z.*</p><p>&bull; <b>Mobil SHC&trade; PM Serisi</b> kurutma bölümleri ve kalender uygulamalar&#305; için üstün performansl&#305; sentetik sirkülasyon ya&#287;lar&#305;<br>
&bull; <b>Mobil DTE&trade; PM Serisi</b> ya&#351; ve kuru k&#305;s&#305;m sirkülasyon sistemleri için üst s&#305;n&#305;f mineral ya&#287; bazl&#305; ka&#287;&#305;t makinesi ya&#287;lar&#305;<br>
&bull; <b>Mobil DTE Excel&trade; Serisi </b>kalender ve pres bölümleri için üstün performansl&#305; a&#351;&#305;nma önleyici sirkülasyon ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobilith-shc-pm-series.aspx">Mobilith SHC&trade; PM Serisi</a></b> ya&#351; ve kuru k&#305;s&#305;m yatak uygulamalar&#305; için sentetik yüksek performansl&#305; ka&#287;&#305;t makinesi gresleri<br>
&bull; <b>Mobilgear SHC&trade; XMP Serisi</b> di&#351;li, yatak ve s&#305;zd&#305;rmazl&#305;k elemanlar&#305; korumas&#305; için ekstra-yüksek performansl&#305; sentetik di&#351;li ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; 600 Serisi</a></b> geni&#351; bir yelpazedeki kritik uygulamalar için üstün performansl&#305; di&#351;li ve sirkülasyon ya&#287;lar&#305;<br>
&bull; <b>Mobilgear SHC&trade; Serisi</b> sentetik yüksek performansl&#305; a&#351;&#305;r&#305; bas&#305;nç kat&#305;kl&#305; di&#351;li ya&#287;&#305;<br>
&bull; <b><a title="" href="products_mobilgear-600-xp-series.aspx">Mobilgear&trade; 600 XP Serisi</a></b> di&#351;li, yatak ve s&#305;zd&#305;rmazl&#305;k elemanlar&#305; korumas&#305; için yüksek performansl&#305; di&#351;li ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel&trade; Serisi</a></b> yüksek viskozite indeksi, kesme dayan&#305;m&#305;, hidrolik sistemler için a&#351;&#305;nma önleyici ya&#287;lar<br>
&bull; <b><a title="" href="products_mobil-dte-20-series.aspx">Mobil DTE&trade; 20 Serisi</a></b> hidrolik sistemler için üstün kaliteli a&#351;&#305;nma önleyici ya&#287;lar</p><p><span style=" font-size: x-small;">*Ekipman ve i&#351;letim &#351;artlar&#305; de&#287;i&#351;iklik gösterdi&#287;inden, tercih edilen ya&#287;lama önerileri için ekipman üreticisinin elkitab&#305;na ba&#351;vurun.</span></p><p><b>Dünya çap&#305;nda deneyim ve ekipman üreticisi onaylar&#305;</b><br>
Deneyimli mühendislerimiz yeni teknoloji ve ya&#287;lama gereksinimlerinin içyüzünü anlamak için mü&#351;teriler ve önde gelen ekipman üreticileriyle birlikte çal&#305;&#351;arak, ürün geli&#351;tirmeye yön vermemize yard&#305;mc&#305; olurlar. Mobil SHC&trade; sentetik ya&#287;lar&#305; önde gelen OEM&rsquo;ler taraf&#305;ndan endüstride sürekli olarak güvenilir performans ve maksimum ekipman koruma sa&#287;lamas&#305;yla tan&#305;n&#305;r.</p><p><b>Gereksinim duydu&#287;unuz deste&#287;i sa&#287;lar&#305;z</b><br>
Güvenilir destek hizmetlerimiz asla yaln&#305;z olmad&#305;&#287;&#305;n&#305;z anlam&#305;na gelir:**</p><p><b>ExxonMobil Teknik Destek</b> &ndash; Teknik uzmanlar ekibimizin tesisiniz için rehberlik ve tavsiyeler sa&#287;layabilen yard&#305;m&#305; telefonla veya online olarak hizmetinizdedir.</p><p><b>E&#287;itimli distribütör sat&#305;&#351; temsilcileri</b> &ndash; Tesisinizin üretkenli&#287;ini ve verimlili&#287;ini artt&#305;rmaya yard&#305;mc&#305; olmak üzere ya&#287; seçimi konusunda çal&#305;&#351;ma yerinde rehberlik.</p><p><b>Saha Mühendisli&#287;i Hizmetleri (FES)</b>&ndash; Ya&#287; performans&#305;n&#305; ve ekipmanda sorun gidermeyi optimize eden ak&#305;lc&#305; ya&#287;lama uygulamalar&#305; hakk&#305;nda profesyonel tavsiyeler ve ayr&#305;ca makinelerinizi daha uzun süre ve daha verimli kullanman&#305;za yard&#305;m edecek sistem muayeneleri ve proaktif izlemeden kar edin.</p><p><b>Son teknolojiye sahip Signum</b><sup><b>SM</b></sup><b> Ya&#287; Analizi program&#305; </b>&ndash; Ekipman ömrünü ve güvenilirli&#287;ini art&#305;rmaya ve bak&#305;m maliyetlerini dü&#351;ürmeye yard&#305;m etmek için ya&#287; ve ekipman durumunuzu izler. Kullan&#305;lm&#305;&#351; ya&#287;da kritik göstergeleri analiz ederek program &#351;irketinizin ya&#287; ve ekipman durumunu daha iyi anlaman&#305;z için ihtiyac&#305;n&#305;z olan bilgileri sa&#287;lar.</p><p><span style=" font-size: x-small;">**Bölgenizde bulunabilirli&#287;i aç&#305;s&#305;ndan yerel ExxonMobil sat&#305;&#351; temsilcinize ba&#351;vurun.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Ka&#287;&#305;t üretim makineleri" src="/IND/English/Images/teaser_60x60_explore_pulp_and_paper_plant.jpg" longdesc="" border="0" alt="Ka&#287;&#305;t üretim makineleri"><h3></h3><p><a title="" href="yourindustry_pulpandpaper_plant_schematic.aspx">ka&#287;&#305;t hamuru ve ka&#287;&#305;t tesisi ke&#351;fetmek</a>&nbsp;<br>
Lütfen hamuru ve ka&#287;&#305;t fabrikas&#305;nda verimlili&#287;i art&#305;rmak için yollar&#305;n&#305; ö&#287;renin</p><p></p></div><div class="item right"><img title="Mobil SHC PM bilgi formu" src="/IND/English/Images/teaser_60x60_mobilSCH_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobil SHC PM bilgi formu"><h3></h3><p><a target="_new" href="/IND/English//files/ss_shc_pm.pdf">Mobil SHC&trade; PM bilgi formu<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Endüstriyel ka&#287;&#305;t makineleri korunmas&#305;na yard&#305;mc&#305; ya&#287;lama ke&#351;fedin</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatl&#305; Ka&#287;&#305;t Endüstrisi üretim süreci" src="/IND/English/Images/teaser_60x60_pulp_and_paper_brochure.jpg" longdesc="" border="0" alt="Pegasus kanatl&#305; Ka&#287;&#305;t Endüstrisi üretim süreci"><h3></h3><p><a target="_new" href="/IND/English/files/br_pulp_and_paper.pdf">ka&#287;&#305;t hamuru ve ka&#287;&#305;t bro&#351;ür<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Biz en forma bitki tutmak nas&#305;l yard&#305;mc&#305; olabilece&#287;ini ke&#351;fedin</p><p></p></div><div class="item right"><img title="Mobil DTE PM bilgi formu&nbsp;" src="/IND/English/Images/teaser_60x60_mobilDTE_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobil DTE PM bilgi formu&nbsp;"><h3></h3><p><a target="_new" href="/IND/English/files/ss_dte_pm.pdf">Mobil DTE&trade; PM bilgi formu<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Ka&#287;&#305;t makine sistemleri dola&#351;an için tasarlanm&#305;&#351; ya&#287;lar hakk&#305;nda bilgi al&#305;n</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Mobilith SHC PM bilgi formu" src="/IND/English/Images/teaser_60x60_mobilithSHC_PM_fact_sheet.jpg" longdesc="" border="0" alt="Mobilith SHC PM bilgi formu"><h3></h3><p><a target="_new" href="/IND/English/files/ss_mobilith_shc_pm.pdf">Mobilith SHC&trade; PM bilgi formu<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Bizim gresler ka&#287;&#305;t makine reach yüksek performans&#305; nas&#305;l yard&#305;mc&#305; oldu&#287;unu ö&#287;renin</p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_pulpandpaper2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_pulpandpaper2.aspx">2</a></li><li><a href="yourindustry_pulpandpaper2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>