<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Üretim Endüstriyel Ya&#287;lar&#305; | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Mobil marka ya&#287;lar, endüstriyel ya&#287;lar, imalat sanayi, g&#305;da ve içecek sanayi, plastik sanayi, hassas i&#351;leme, Mobil endüstriyel, Mobil endüstriyel ya&#287;lar"><meta name="description" content="Üretim endüstri tesisinizin - g&#305;da ve içecek endüstrisi, plastik veya tala&#351;l&#305; imalat üretkenlik ve verimlili&#287;ini Mobil&trade; markal&#305; endüstriyel ya&#287;lar ile serbest b&#305;rak&#305;n"><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:47 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Pegasus kanatl&#305; endüstriyel verimlilikte üretim tesisi" src="/IND/English/Images/article_150x150_plant_productivity.jpg" longdesc="" border="0" alt="Pegasus kanatl&#305; endüstriyel verimlilikte üretim tesisi"></div><h1><b><span style=" font-size: x-large;">Üretim tesisi üretkenli&#287;ini tepelere ç&#305;kar&#305;n</span></b></h1><p><span style=" font-size: large;"><b>Üretim ekipman&#305;nda ba&#351;ar&#305;s&#305; ispatlanm&#305;&#351; performans</b></span>&nbsp;</p><p>Üretti&#287;iniz ne olursa olsun, verimlilik i&#351;letme kârl&#305;l&#305;&#287;&#305;n&#305;zda kilit bir role sahiptir. Ekipman ar&#305;zalar&#305; rekabetçi kalabilmek için çok önemli olan üretiminizi yava&#351;latabilir.</p><p>Hepsi toplam i&#351;letim maliyetinizi dü&#351;ürebilmeniz ve ekipman&#305;n&#305;z&#305; en verimli durumda çal&#305;&#351;&#305;r olarak tutabilmeniz için tasarlanan yenilikçi hizmetler ve e&#287;itimli sat&#305;&#351; temsilcileri ile mühendisler taraf&#305;ndan uygulanan programlarla desteklenen, yüksek performansl&#305; ürünler sunuyoruz.<br>
Üretim tesisinizin &mdash; ister g&#305;da ve içecek i&#351;leme, plastik, tala&#351;l&#305; imalat veya di&#287;er i&#351;lemler olsun &mdash;Mobil&trade; markal&#305; endüstriyel ya&#287;lar ile üretkenlik ve verimlili&#287;ini serbest b&#305;rak&#305;n.</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatl&#305; g&#305;da ve içecek Endüstrisi so&#287;utucu" src="/IND/English/Images/teaser_90x90_food_and_beverage.jpg" longdesc="" border="0" alt="Pegasus kanatl&#305; g&#305;da ve içecek Endüstrisi so&#287;utucu"><h3><a title="" href="yourindustry_manufacturing_food.aspx">g&#305;da ve içecek endüstrisi</a></h3><p>Ya&#287;lar&#305;m&#305;z bu endüstrinin benzersiz zorluklar&#305;n&#305;n üstesinden gelir.<br><a title="" href="yourindustry_manufacturing_food.aspx">Daha fazla bilgi &gt;</a></p><p></p></div><div class="item right"><img title="Pegasus kanatl&#305; plastik sandalye" src="/IND/English/Images/teaser_90x90_plastics.jpg" longdesc="" border="0" alt="Pegasus kanatl&#305; plastik sandalye"><h3><a title="" href="yourindustry_manufacturing_plastics.aspx">plastik</a></h3><p>Mobil&trade; markal&#305; endüstriyel ya&#287;lar plastik endüstrisinde üretimi artt&#305;rabilir.<br><a title="" href="yourindustry_manufacturing_plastics.aspx">Daha fazla bilgi &gt;</a></p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatl&#305; i&#351;leme kol saati" src="/IND/English/Images/teaser_90x90_machine.jpg" longdesc="" border="0" alt="Pegasus kanatl&#305; i&#351;leme kol saati"><h3><a title="" href="yourindustry_manufacturing_machining.aspx">tala&#351;l&#305; &#304;malat</a></h3><p>Hassas i&#351;leme için yenilikçi çözümler ve hizmetler sunar&#305;z.<br><a title="" href="yourindustry_manufacturing_machining.aspx">Daha fazla bilgi &gt;</a></p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_manufacturing2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_manufacturing2.aspx">2</a></li><li><a href="yourindustry_manufacturing2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>