
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Gaz Türbinli Motor Endüstriyel Ya&#287;lar&#305; &ndash; Enerji Endüstrisi | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Gaz türbinli Elektrik santralinizin üretkenli&#287;ini &trade; Markal&#305; Endüstriyel ya&#287;lar&#305;n sa&#287;lad&#305;&#287;&#305; artt&#305;r&#305;lm&#305;&#351; güvenilirlik H&#304;ZMET süresiyle artt&#305;r&#305;n ettik verimlili&#287;ini Mobil Türbin ettik."><meta name="description" content="Gaz türbinli elektrik santralinizin üretkenli&#287;ini ve türbin verimlili&#287;ini Mobil&trade; markal&#305; endüstriyel ya&#287;lar&#305;n sa&#287;lad&#305;&#287;&#305; artt&#305;r&#305;lm&#305;&#351; güvenilirlik ve hizmet süresiyle artt&#305;r&#305;n."><meta name="date" content="02/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/9/2015 10:49:22 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_energy_gasturbines_link.html"--></p><p><span style=" font-size: x-large;"><b>Elektrik santrallerinde üretkenli&#287;i serbest b&#305;rak&#305;n</b></span></p><p><span style=" font-size: large;"><b>Santral türbinlerini uçurun<br></b></span><br>
Santrallerinizin üretkenli&#287;ini ve türbin verimlili&#287;ini Mobil&trade; markal&#305; endüstriyel ya&#287;lar&#305;n sa&#287;lad&#305;&#287;&#305; art&#305;r&#305;lm&#305;&#351; güvenilirlik ve hizmet süresi ile artt&#305;r&#305;n. Ekipman&#305;n&#305;zdan en verimli &#351;ekilde yararlanman&#305;z&#305; sa&#287;lamak için üretilen bu yüksek performansl&#305; sentetik ya&#287;lar&#305;n arkas&#305;nda 100 y&#305;ll&#305;k endüstrisi deneyimi ve uzmanl&#305;&#287;&#305; vard&#305;r. Sisteminizin sadece çal&#305;&#351;mas&#305;n&#305; sa&#287;lamak için de&#287;il &ndash; uçmas&#305;n&#305; sa&#287;lamak için tasarlanm&#305;&#351;t&#305;r.</p><p>Önemli ekipman ihtiyaçlar&#305;n&#305;z için özel olarak üretilen, geni&#351; bir ya&#287; yelpazesi sunmaktay&#305;z. Kesintisiz bir çal&#305;&#351;ma ve uzun hizmet ömrü için tasarlanm&#305;&#351; üstün kaliteli türbin ya&#287;lar&#305;ndan, son derece zorlu &#351;artlarda çal&#305;&#351;mak için tasarlanm&#305;&#351; üstün sentetik ya&#287;lar ve greslere, Mobil markal&#305; endüstriyel ya&#287;lar&#305; ve gresleri elektrik santrallerinizin üstün performansla çal&#305;&#351;mas&#305;na yard&#305;mc&#305; olacakt&#305;r.</p><p><b>Kapsaml&#305; üretici onay&#305; onaylar&#305; ve ispatlanm&#305;&#351; saha performans&#305;.</b><br>
Üretime geçilmeden önce detayl&#305; testlerden geçirilen Mobil markal&#305; endüstriyel ya&#287;lar&#305; ve gresleri ekipman üreticilerinin onaylar&#305;yla desteklenir. Örne&#287;in, üstün kaliteli türbin ya&#287;lar&#305;m&#305;z olan <a title="" href="products_mobil-dte-800-series.aspx">Mobil DTE&trade; 800 Serisi</a> belirli yüksek verimli kombine çevrimli türbin kullan&#305;m yerleri için üretilmi&#351;tir. Yeni <a title="" href="products_mobil-dte-700-series.aspx">Mobil DTE&trade; 700 Serisi</a>, gaz ve buhar türbinleri için 17 endüstri ve ekipman üretici &#351;artnamesini kar&#351;&#305;lar veya geçer.</p><p><b>Türbin &#304;&#351;letime Alma Program&#305;m&#305;z* i&#351;inizi kolayla&#351;t&#305;rmaya yard&#305;mc&#305; olur.</b><br>
Bu yenilikçi hizmet, türbin ya&#287;lama sisteminizi ve türbin ya&#287;&#305;n&#305;z&#305; bir revizyon sonras&#305;nda veya yeni bir kurulum için zaman&#305;nda bir ilk çal&#305;&#351;ma ve güvenilir bir çal&#305;&#351;maya haz&#305;rlamaya yard&#305;mc&#305; olur. Ekipman üretici gereksinimlerini kar&#351;&#305;laman&#305;z ve tesisinizde kapsaml&#305; bir ya&#287;lama program&#305; uygulaman&#305;z için size ürün önerileri, türbin ya&#287;lama sistemi, ya&#287; haz&#305;rl&#305;&#287;&#305; ve i&#351;letim sonras&#305; ya&#287;lamaya yönelik ek hizmetler sunabiliriz.</p><p>Standart belirleyen ürünler ve hizmetler için Mobil markal&#305; endüstriyel türbin ya&#287;lar&#305;m&#305;z ekibine kat&#305;l&#305;n. Çal&#305;&#351;man&#305;z&#305;n üretkenli&#287;ini artt&#305;rmak için lider teknolojimizden ve e&#351;siz endüstriyel uzmanl&#305;&#287;&#305;m&#305;zdan faydalan&#305;n.</p><p><a target="_new" href="http://www.youtube.com/watch?v=Z4MWDrFPkx4">Mobil SHC 824'ün Solar Gaz Türbinini 90,000 saatten daha fazla korumas&#305;: Bir Mobil SHC Ba&#351;ar&#305; Hikayesi</a> (EN)</p><p><span style=" font-size: x-small;">*Bölgenizde bulunabilirli&#287;i aç&#305;s&#305;ndan ExxonMobil temsilcinizle irtibat kurun.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Gaz ve buhar türbinli elektrik santrali" title="Gaz ve buhar türbinli elektrik santrali" longdesc="" src="/IND/English/Images/teaser_60x60-explore-the-gas-and-steam-turbine-power-plant.jpg" border="0"></img><h3><a title="" href="yourindustry_energy_gasturbines_schematic.aspx">gaz ve buhar türbinli elektrik santralini ke&#351;fedin</a></h3><p>Tura kat&#305;l&#305;n<br></p></div><div class="item right"><img alt="Santral türbinlerinizi nas&#305;l koruyabilece&#287;imizi ö&#287;renin" title="Santral türbinlerinizi nas&#305;l koruyabilece&#287;imizi ö&#287;renin" longdesc="" src="/IND/English/Images/teaser_60x60-gas-turbine-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/Turkish/files/br_gas_turbine_tr.pdf">gaz türbini bro&#351;ürü<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Santral türbinlerinizi nas&#305;l koruyabilece&#287;imizi ö&#287;renin<br><br>
&nbsp;</p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Gaz ve buhar türbinli elektrik santrali &#351;emas&#305;" title="Gaz ve buhar türbinli elektrik santrali &#351;emas&#305;" longdesc="" src="/IND/English/Images/teaser_60x60-gas-turbine-schematic.jpg" border="0"></img><h3><a target="_new" href="/IND/Turkish/files/schm_gas_turbine_tr.pdf">gaz türbini &#351;emas&#305;<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Santralinizin üretkenli&#287;ini artt&#305;r&#305;n<br></p></div><div class="item right"><img alt="Gaz ve buhar türbinleri için Mobil DTE 700 serisi türbin ya&#287;&#305; &nbsp;bilgi formu" title="Gaz ve buhar türbinleri için Mobil DTE 700 serisi türbin ya&#287;&#305; &nbsp;bilgi formu" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-dte-700-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/Turkish/files/ss_dte_700_tr.pdf">Mobil DTE&trade; 700 Bilgi Formu<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Yüksek performansl&#305; türbin ya&#287;&#305;m&#305;z&#305;n sizin için neler yapabilece&#287;ini ö&#287;renin<br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Gaz ve buhar türbinleri için Mobil DTE 800 serisi bilgi formu" title="Gaz ve buhar türbinleri için Mobil DTE 800 serisi bilgi formu" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-dte-800-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/Turkish/files/ss-mobil-dte-800-tr.pdf">Mobil DTE&trade; 800 Bilgi Formu<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Gaz ve buhar türbinleri için maksimum koruma<br></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_energy_gasturbines2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_energy_gasturbines2.aspx">2</a></li><li><a href="yourindustry_energy_gasturbines2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>