<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Madencilik ve yol d&#305;&#351;&#305; Endüstriyel Ya&#287;lar - Madencilik Endüstrisi | Mobil&trade; Endüstriyel Ya&#287;lar&#305;</title><meta name="keywords" content="Madencilik endüstrisi, endüstriyel ya&#287;lar, sentetik ya&#287;lar, Mobil markal&#305; endüstriyel ya&#287;lar, madencilik ya&#287;lar&#305;"><meta name="description" content="Zorlu ko&#351;ullarda bile ola&#287;anüstü performans sa&#287;lamak için madencilik endüstrisinde geli&#351;mi&#351; teknolojili Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar&#305;na güvenin."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="7/24/2014 8:47:25 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_mining_offhighway.html"--></p><p><br><span style=" font-size: x-large;"><b>Kaya gibi sa&#287;lam koruma elde edin</b></span></p><p><span style=" font-size: large;"><b>Madencilik/yol d&#305;&#351;&#305; için premium performans</b></span></p><p>Madencilik endüstrisinde ekipman bozulmalar&#305; çok ciddidir. Operasyonunuzun karl&#305; olabilmesi için ekipman&#305;n&#305;z verimli bir &#351;ekilde çal&#305;&#351;mal&#305;d&#305;r ve bu do&#287;ru ya&#287;lar&#305;n kullan&#305;lmas&#305;n&#305; gerektirir.</p><p>&#304;ster yüzeyde ister yeralt&#305;nda madencilik yap&#305;n, ister mineral ya&#287; kumlar&#305; veya kömür için kaz&#305;yor olun, ister ta&#351;&#305;ma kamyonlar&#305; ve kürekler veya ö&#287;ütücüler ve matkaplar kullan&#305;yor olun, geli&#351;mi&#351; teknolojili Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar&#305;na &nbsp;güvenin. Zorlu ko&#351;ullarda bile ola&#287;anüstü performans sa&#287;lamak üzere formüle edilmi&#351;lerdir.</p><p><b>Premium çözümler</b><br><a title="" href="products_mobil-shc.aspx">Mobil SHC&trade;</a> ve <a href="http://www.mobil.us/USA-English-LCW/heavydutyengineoils_products_engine-oils_mobil-delvac-1-esp-5w40.aspx">Mobil Delvac&trade;</a> madencilik endüstrisi için ola&#287;anüstü performans sa&#287;lamak üzere tasarlanm&#305;&#351;t&#305;r. Hem mobil hem tesis ekipman&#305; için sentetik ya&#287;lar ve gresler geli&#351;tirmekte tan&#305;nm&#305;&#351; bir lider olarak konvansiyonel ya&#287;lar&#305;m&#305;z&#305;n kapasitelerinin ötesinde yenilikler sunar&#305;z. Ko&#351;ullar zorlu oldu&#287;unda Mobil markal&#305; sentetik ya&#287;lar a&#351;a&#287;&#305;dakiler dahil olmak üzere mineral ya&#287;lara göre önemli olas&#305; avantajlar sa&#287;lamak için formüle edilmi&#351;tir.</p><p>&bull; daha uzun ya&#287; ömrü<br>
&bull; daha uzun ekipman ömrü<br>
&bull; azalm&#305;&#351; enerji tüketimi</p><p>Madencilik endüstrisinde çe&#351;itli uygulamalar için geni&#351; bir sentetik ve premium mineral ya&#287; tabanl&#305; ya&#287; serisi sunuyoruz. Tesisinizde derinlere kazmaya devam edebilmeniz için Mobil markal&#305; ürünler hakk&#305;nda daha fazla bilgi al&#305;n.</p><p>&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; 600</a></b> di&#351;li ve sirkülasyon ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC&trade; Gear</a></b> di&#351;li ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-rarus-shc-1020-series.aspx">Mobil Rarus SHC&trade; </a>&nbsp;</b>hava kompresörleri ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-oh-series.aspx">Mobil SHC&trade; Gear OH</a></b> karayolu d&#305;&#351;&#305; &nbsp;tahrik uygulamalar&#305; için<br>
&bull; <b><a title="" href="products_greases_mobil-dynagear-series.aspx">Mobil Dynagear&trade;</a></b> çok amaçl&#305; ya&#287; aç&#305;k di&#351;liler için<br>
&bull; <b>Mobilgrease XHP&trade; Mine</b> lityum kompleksli gresler<br>
&bull; <b><a href="http://www.mobil.us/USA-English-LCW/heavydutyengineoils_products_engine-oils_mobil-delvac-1-esp-5w40.aspx">Mobil Delvac&trade;</a></b> dizel motor ya&#287;lar&#305;<br>
&bull; <b>Mobiltrans&trade;</b> transmisyon ve aktrama organlar&#305; ya&#287;&#305;<br>
&bull; <b><a href="http://www.mobil.us/USA-English-LCW/heavydutyengineoils_products_transmission-fluid_mobil-delvac-synthetic-atf.aspx">Mobil Delvac&trade; Synthetic Transmission Fluid</a></b>&nbsp;<br>
&bull; <a href="http://www.mobiloil.com/USA-English/MotorOil/Other_Products/Mobilube_HD_Plus_80W-90.aspx"><b>Mobilube&trade; HD</b></a> çok amaçl&#305; di&#351;li ve aks ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel&trade;</a></b> gelecek jenerasyon, yüksek viskozite indeksli hidrolik ya&#287;lar</p><p>&nbsp;<br><a target="_new" href="/IND/English/files/mobilgrease-xhp-mine-series.pdf">Mobilgrease XHP&trade; Di&#351;li veri sayfas&#305;<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)</p><p>&nbsp;<a target="_new" href="/IND/English/files/mining-industry-machinery-efficiency-brochure.pdf">Madencilik Bro&#351;ürü<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Madencilik endüstrisi &#351;emas&#305;" src="/IND/English/Images/teaser_60x60-explore-a-mining-operation.jpg" longdesc="" border="0" alt="Madencilik endüstrisi &#351;emas&#305;"><h3><a target="_new" href="/IND/english/files/mining-machinery-schematic.pdf">bir madencilik operasyonunu inceleyin<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Madencilik operasyonunuzun nas&#305;l verimli bir &#351;ekilde çal&#305;&#351;mas&#305;na yard&#305;m<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; edebilece&#287;inizi ö&#287;renin<br>
&nbsp;</p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_mining_offhighway2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_mining_offhighway2.aspx">2</a></li><li><a href="yourindustry_mining_offhighway2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>