<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Demir ve Çelik Endüstrisi Ya&#287;lar&#305; | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="demir sanayi, çelik sanayi, endüstriyel gres, endüstriyel ya&#287;lar, endüstriyel makine, Mobil marka ya&#287;lar"><meta name="description" content="Demir ve çelik endüstrisi için makinalar&#305;n&#305;z&#305;n kesintisiz ve plans&#305;z duru&#351; olmadan çal&#305;&#351;malar&#305;na yard&#305;mc&#305; olmak için Mobil&trade; markal&#305; Endüstriyel Ya&#287;lara güvenin."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:29 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_primarymetals_link.html"--></p><p><span style=" font-size: x-large;"><b>Kesintisiz üretkenli&#287;i</b></span></p><p><b><span style=" font-size: large;">Demir ve çelik endüstrisi için çözümler ve hizmetler</span></b></p><p>Global demir çelik endüstrisinde üretkenlik talepleri hiç bu kadar fazla olmam&#305;&#351;t&#305;. Mümkün oldu&#287;unca verimli ve karl&#305; kalabilmek için en zorlu ortamlarda yüksek s&#305;cakl&#305;klar ve a&#287;&#305;r yükler dahil olmak üzere &mdash; ekipman&#305;n&#305;zdan yeni bir üretkenlik düzeyi elde etmenize yard&#305;mc&#305; olan makine ya&#287;lamas&#305;na gereksiniminiz var. Makinalar&#305;n&#305;z&#305; kesintisiz ve plans&#305;z duru&#351; olmadan çal&#305;&#351;malar&#305;na yard&#305;mc&#305; olmak için Mobil&trade; markal&#305; endüstriyel ya&#287;lara güvenin.</p><p><b>Enerji verimlili&#287;ini hissedilir&nbsp;&#351;ekilde&nbsp;ele alma</b><br>
Endüstrinizin güvenilir, sürdürülebilir bir &#351;ekilde çelik talebini kar&#351;&#305;lama taahhüdünü payla&#351;&#305;yoruz. Mobil markal&#305; birçok ürün a&#351;a&#287;&#305;dakiler yoluyla azalm&#305;&#351; enerji tüketimi ve kaynak kullan&#305;m&#305;na katk&#305;da bulunmaya yard&#305;mc&#305; olabilir:<br>
&bull; enerji verimlili&#287;i<br>
&bull; uzun ya&#287; ömrü<br>
&bull; uzun ekipman ömrü</p><p>Demir ve çelik makinalar&#305; için kapsaml&#305; sentetik ve premium ya&#287;lar serimiz &#351;unlar&#305; içerir:*<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; 600</a></b> yeni jenerasyon sirkülasyon ve di&#351;li ya&#287;lar&#305;, enerji verimlili&#287;i faydalar&#305; sunar**<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC&trade; Gear</a></b> yeni jenerasyon üstün di&#351;li ya&#287;lar&#305;, enerji verimlili&#287;i faydalar&#305; sunar**<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-rarus-shc-1020-series.aspx">Mobil Rarus SHC&trade; 1020</a></b> hava kompresör ya&#287;lar&#305;<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-polyrex-series.aspx">Mobil SHC Polyrex&trade;</a> &nbsp;</b>yüksek performansl&#305; yatak gresi<br>
&bull; <b><a title="" href="products_greases_mobilith-shc-grease-series.aspx">Mobilith SHC&trade;</a> &nbsp;</b>yataklar için sentetik yüksek s&#305;cakl&#305;kl&#305; gresler<br>
&bull; <b>Mobil Centaur&trade; XHP</b> kalsiyum sülfonat gres, çelik ve fabrika ekipman&#305; için<br>
&bull; <b>Mobilgrease XHP&trade;&nbsp;</b>lityum kompleksli gres, çoklu uygulamalar için<br>
&bull; <b>Mobil Vacuoline&trade; 100</b> sirkülasyon sistem ya&#287;lar&#305;, haddelerde düz yataklar için<br>
&bull; <b>Mobil Vacuoline&trade; 500</b> dayan&#305;kl&#305; sirkülasyon ya&#287;lar&#305;, bükülmesiz çubuk haddeleri için</p><p><b>Dünya çap&#305;nda endüstri uzmanl&#305;&#287;&#305;n&#305; sunüyoruz</b><br>
Demir ve çelik fabrikas&#305; ya&#287;lar&#305;m&#305;z ve greslerimizi endüstri ve orijinal ekipman üreticisi beklentilerini kar&#351;&#305;layacak veya a&#351;acak &#351;ekilde tasarlar&#305;z. Piyasaya verilmeden önce,iyice test edilen Mobil markal&#305; endüstriyel ya&#287;lar global kalite standartlar&#305;n&#305; kar&#351;&#305;lar ve üretim, mü&#351;teri hizmetleri, laboratuarlar, güvenlik, sa&#287;l&#305;k ve çevre için çok s&#305;k&#305; olan ExxonMobil yönetim sistemleriyle uyumludur.</p><p><b>Gereksinim duydu&#287;unuz deste&#287;i sa&#287;lar</b><br>
Yenilikçi destek hizmetlerimiz her gerek &nbsp;duydu&#287;unuzda yard&#305;m alman&#305;z&#305; sa&#287;lar.&dagger;</p><p><b>ExxonMobil Teknik Deste&#287;i </b>&ndash; Teknik uzmanlar ekibimizden yard&#305;m telefon veya çevrim içi olarak sa&#287;lanabilir.</p><p><b>Kendini adam&#305;&#351; sat&#305;&#351; temsilcileri</b> &ndash; Tesisinizin üretkenli&#287;ini artt&#305;rmaya yard&#305;mc&#305; olmak üzere çelik fabrikas&#305; uzmanlar&#305;ndan çal&#305;&#351;ma yerinde rehberlik.</p><p><b>Saha Mühendisli&#287;i Servisleri (FES)</b>&ndash; Ya&#287;lama uygulamalar&#305; konusunda uzman öneriler, ya&#287; performans&#305;n&#305; optimize etme ve ekipmanda sorun giderme ve ayr&#305;ca makinalar&#305;n&#305;z&#305; daha uzun ve daha verimli çal&#305;&#351;t&#305;rman&#305;za yard&#305;mc&#305; olmak üzere sistem incelemeleri ve proaktif izleme.</p><p><b>Signum</b><sup><b>SM</b></sup><b> Ya&#287; Analizi program&#305; </b>&ndash; Ekipman ömrü ve güvenilirli&#287;ini artt&#305;rmak ve bak&#305;m maliyetlerini azaltmak için ya&#287; ve ekipman durumunu izler. Kullan&#305;lm&#305;&#351; ya&#287;da kritik göstergeleri de&#287;erlendirmek üzere özellikle haz&#305;rlanm&#305;&#351; olan program ya&#287; ve ekipman durumunuzu daha iyi anlaman&#305;z için gerekli bilgiyi sa&#287;lar.</p><p>Makinalar&#305;n&#305;z&#305;n daha fazla ekipman, çal&#305;&#351;ma ve enerji verimlili&#287;i ile daha fazlas&#305;n&#305; daha h&#305;zl&#305; ve daha güvenli olarak üretmelerine yard&#305;mc&#305; olmak üzere seçilmi&#351; Mobil markal&#305; endüstriyel ya&#287;lar&#305;n arkas&#305;ndaki teknoloji liderleri ve uygulama uzmanl&#305;&#287;&#305;na güvenin.</p><p><span style=" font-size: x-small;">*Ekipman ve çal&#305;&#351;t&#305;rma ko&#351;ullar&#305; farkl&#305;l&#305;k gösterdi&#287;inden lütfen tercih edilen ya&#287;lama önerileri için ekipman üreticisi el kitab&#305;na ba&#351;vurun.&nbsp;<br>
** Azalm&#305;&#351; enerji tüketimi sadece ExxonMobil&rsquo;in standart s&#305;v&#305;lar&#305;yla kar&#351;&#305;la&#351;t&#305;r&#305;ld&#305;&#287;&#305;nda s&#305;v&#305; performans&#305;yla ili&#351;kilidir. Bu ürün için enerji verimlili&#287;i iddias&#305; geçerli endüstri standartlar&#305; ve protokolleriyle uyumlu olarak yap&#305;lan testlerin sonuçlar&#305;n&#305; temel al&#305;r.&nbsp;<br>
&dagger; Bölgenizde bulunabilirli&#287;i aç&#305;s&#305;ndan ExxonMobil temsilcinizle irtibat kurun.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Demir ve Çelik Endüstrisi s&#305;cak taraf do&#287;rudan azaltma &#351;emas&#305;" src="/IND/English/Images/teaser_60x60_hot_side_plant_schematic.jpg" longdesc="" border="0" alt="Demir ve Çelik Endüstrisi s&#305;cak taraf do&#287;rudan azaltma &#351;emas&#305;"><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelhotside.pdf">demir çelik hot side tesisi &#351;emas&#305; (PDF)<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
S&#305;cak taraf tesisinizi nas&#305;l yüksek performansa ula&#351;abilece&#287;inizi bulun</p><p></p></div><div class="item right"><img title="Demir ve Çelik Endüstrisi sinter üretim &#351;emas&#305;" src="/IND/English/Images/teaser_60x60_handling_plant_schematic.jpg" longdesc="" border="0" alt="Demir ve Çelik Endüstrisi sinter üretim &#351;emas&#305;"><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelmaterialhandling.pdf">demir çelik muamele tesisi &#351;emas&#305; (PDF)<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Muamele tesisinizi nas&#305;l en iyi durumda tutabilece&#287;inizi bulun</p><p></p><p>&nbsp;</p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Demir ve Çelik Endüstrisi so&#287;uk hadde &#351;emas&#305;" src="/IND/English/Images/teaser_60x60_forming_plant_schematic.jpg" longdesc="" border="0" alt="Demir ve Çelik Endüstrisi so&#287;uk hadde &#351;emas&#305;"><h3></h3><p><a target="_new" href="/IND/English/Files/schm_primarymetals_steelforming.pdf">demir ve çelik &#351;ekillendirme tesisi &#351;emas&#305; (PDF)<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
&#350;ekillendirme tesisinizde üretkenli&#287;i nas&#305;l artt&#305;raca&#287;&#305;n&#305;z&#305; ke&#351;fedin</p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><h3></h3></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_primarymetals2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_primarymetals2.aspx">2</a></li><li><a href="yourindustry_primarymetals2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>