<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>&#304;&#351;leme Tesisi Endüstriyel Ya&#287;lar&#305; | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Mobil marka ya&#287;lar, endüstriyel ya&#287;lar, i&#351;leme tesisi, i&#351;leme makineleri, Mobil ya&#287;lar&#305;, i&#351;leme tesisi için endüstriyel ya&#287;lama"><meta name="description" content="Her tür i&#351;leme tesisi için Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar yenilikçi hizmetler ve programlarla desteklenen yüksek performansl&#305; ürünler sunar. "><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:27:48 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Pegasus kanatlarla &#304;&#351;leme Tesisi fabrikas&#305;" src="/IND/English/Images/article_150x150_industry_process.jpg" longdesc="" border="0" alt="Pegasus kanatlarla &#304;&#351;leme Tesisi fabrikas&#305;"></div><h1><span style=" font-size: x-large;"><b>&#304;&#351;leme tesisinizi serbest b&#305;rak&#305;n</b></span></h1><p><span style=" font-size: large;"><b>Üretkenli&#287;i artt&#305;r&#305;n</b></span>&nbsp;</p><p>Her tür i&#351;leme tesisi için yenilikçi hizmetler ve programlarla desteklenen yüksek performansl&#305; ürünler sunar&#305;z. Saha mühendisli&#287;i hizmetleri ekibimiz uygulamalar&#305;n&#305;z için do&#287;ru Mobil&trade; markal&#305; endüstriyel ya&#287;lar&#305; seçmenizde yard&#305;mc&#305; olabilir ve tesisinizin üretkenli&#287;ini serbest b&#305;rakabilir.</p><p><br><br><b>Petrokimyasallar</b><br>
Petrokimya endüstrisi ekipman a&#287;&#305;rl&#305;kl&#305;d&#305;r ve en üst düzey performansa ula&#351;mak için neler gerekti&#287;ini anlayan bizler, ekipman&#305;n&#305;zdan daha fazlas&#305;n&#305; kazanman&#305;za yard&#305;m edebiliriz. &#304;&#351;letmenizin üretkenli&#287;ini daha da artt&#305;rmak için, hayati kompresör, mekanik salmastra, pompa ve di&#287;er yard&#305;mc&#305; makine parçalar&#305; için mükemmel koruma sa&#287;lamak üzere çok çe&#351;itli ya&#287;lar ve benzersiz sentetik ürünler sunar&#305;z.</p><p><b>Ta&#351; Ocakç&#305;l&#305;&#287;&#305; ve Çimento</b><br>
Ta&#351; ocakç&#305;l&#305;&#287;&#305; ve çimento endüstrilerinin çal&#305;&#351;ma &#351;artlar&#305; zorludur. A&#287;&#305;r yük ve yüksek s&#305;cakl&#305;k alt&#305;ndaki uygulamalar&#305;n&#305;zda üstün koruma için yenilikçi Mobil markal&#305; ya&#287; ve greslerine güvenin.</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="&#304;&#351;leme Endüstrisi kimyasal referans tablosu" src="/IND/English/Images/teaser_60x60_chemical_reference_chart.jpg" longdesc="" border="0" alt="&#304;&#351;leme Endüstrisi kimyasal referans tablosu"><h3></h3><p><a target="_new" href="/IND/English//files/st_chemical.pdf">kimya endüstrisi ürün referans tablosu (PDF)<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
&#304;htiyaçlar&#305;n&#305;z için do&#287;ru endüstriyel ya&#287; bulun<br></p></div><div class="item right"><img title="&#304;&#351;leme Endüstrisi çimento referans tablosu" src="/IND/English/Images/teaser_60x60_cement_reference_chart.jpg" longdesc="" border="0" alt="&#304;&#351;leme Endüstrisi çimento referans tablosu"><h3></h3><p><a target="_new" href="/IND/English/files/st_cement.pdf">çimento endüstrisi ürün referans tablosu (PDF)<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Hangi ya&#287;lar&#305;n uygulamalar&#305;n&#305;za en iyi uydu&#287;unu bulun<br></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_process2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_process2.aspx">2</a></li><li><a href="yourindustry_process2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>