<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xml:lang="tr" lang="tr" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Endüstriniz için Endüstriyel Makine Ya&#287;lar&#305; | Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar</title><meta name="keywords" content="Mobil marka ya&#287;lar&#305;, endüstriyel ya&#287;lar, endüstriyel ya&#287;lama, endüstriyel ya&#287;, endüstriyel makine, Mobil endüstriyel, Mobil endüstriyel ya&#287;lar"><meta name="description" content="Mobil&trade; markal&#305; endüstriyel ya&#287;lar ekipman güvenilirli&#287;ini artt&#305;rarak ve çok daha fazlas&#305;yla operasyonunuzu düzgün çal&#305;&#351;&#305;r &#351;ekilde tutman&#305;za yard&#305;mc&#305; olmak üzere tasarlanm&#305;&#351;t&#305;r."><meta name="date" content="11/2013"><meta name="language" content="tr"><meta http-equiv="Content-Language" content="tr"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
			<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
			<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
			<script language="Javascript" src="/Imports/js/xom.js"></script>
			<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
<![endif]--> 	<!--[if lte IE 6]>
				<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
				<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/30/2014 5:26:56 PM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img title="Pegasus kanatlarla endüstriyel ya&#287;lar fabrikas&#305;" src="/IND/English/Images/article_150x150_Flying-Industry.jpg" longdesc="" border="0" alt="Pegasus kanatlarla endüstriyel ya&#287;lar fabrikas&#305;"></div><h1><b><span style=" font-size: large;">Neden uçan bir operasyon olabilecekken sadece çal&#305;&#351;an&#305;na raz&#305; olas&#305;n&#305;z?</span></b></h1><p>Endüstriyel ya&#287;lamadaki 100 y&#305;l&#305; a&#351;k&#305;n geçmi&#351; deneyimlerimiz, bize çal&#305;&#351;man&#305;z&#305; sorunsuz &#351;ekilde devam ettirmenizi sa&#287;layacak tecrübe ve bilgiyi vermeye yard&#305;mc&#305; olmaktad&#305;r. &nbsp;Mobil&trade; markal&#305; ya&#287;lar ile çal&#305;&#351;mak size &#351;u konularda yard&#305;mc&#305; olacak &#351;ekilde tasarlanm&#305;&#351;t&#305;r:</p><p>&bull; Ekipman güvenilirli&#287;ini artt&#305;rmak<br>
&bull; Çal&#305;&#351;an güvenli&#287;ini artt&#305;rma iyile&#351;tirme<br>
&bull; Operasyon maliyetini azaltma<br>
&bull; Ekipman dayan&#305;kl&#305;l&#305;&#287;&#305;n&#305; artt&#305;rma<br>
&bull; Olas&#305; çevresel etkileri minimuma indirme<br>
&nbsp;</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatlarla Enerji Endüstrisi güç hatlar&#305; kulesi" src="/IND/English/Images/teaser_90x90_energy_industry.jpg" longdesc="" border="0" alt="Pegasus kanatlarla Enerji Endüstrisi güç hatlar&#305; kulesi"><h3><a title="" href="yourindustry_energy.aspx">enerji endüstrisi</a></h3><p>Kömür, gaz türbini ve motor gaz motoru , nükleer ve rüzgar dahil hem geleneksel hem yenilenebilir enerji üreticilerine hizmet verir.<br><a title="" href="yourindustry_energy.aspx">Daha fazla bilgi &gt;</a><br></p></div><div class="item right"><img title="Pegasus kanatlarla Üretim Endüstrisi fabrikas&#305;" src="/IND/English/Images/teaser_90x90_manufacturing_industry.jpg" longdesc="" border="0" alt="Pegasus kanatlarla Üretim Endüstrisi fabrikas&#305;"><h3><a title="" href="yourindustry_manufacturing.aspx">üretim endüstrisi</a></h3><p>tesisinizin üretkenli&#287;ini serbest b&#305;rak&#305;n &mdash; ister g&#305;da ve içecek i&#351;leme, ister plastik, ister i&#351;leme tala&#351;l&#305; imalat veya ister ba&#351;ka bir operasyon olsun.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_manufacturing.aspx">Daha fazla bilgi &gt;</a><br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatlarla Madencilik Endüstrisi kepçeli kamyon" src="/IND/English/Images/teaser_90x90_mining_off_highway.jpg" longdesc="" border="0" alt="Pegasus kanatlarla Madencilik Endüstrisi kepçeli kamyon"><h3><a title="" href="yourindustry_mining_offhighway.aspx">madencilik/karayolu d&#305;&#351;&#305; in&#351;aat</a></h3><p>Ta&#351; oca&#287;&#305; ve çimento endüstrilerinin zorlu ko&#351;ullar&#305; için Mobil&trade; markal&#305; Endüstriyel Ya&#287;lar üstün koruma sa&#287;lar.<br><a title="" href="yourindustry_mining_offhighway.aspx">Daha fazla bilgi &gt;</a></p><p></p></div><div class="item right"><img title="Pegasus kanatlarla Ka&#287;&#305;t üretimi" src="/IND/English/Images/teaser_90x90_pulp_and_paper.jpg" longdesc="" border="0" alt="Pegasus kanatlarla Ka&#287;&#305;t üretimi"><h3><a title="" href="yourindustry_pulpandpaper.aspx">ka&#287;&#305;t hamuru ve ka&#287;&#305;t</a></h3><p>&#304;ster gazete, ince ka&#287;&#305;t veya korügasyonlu oluklu mukavva üretiyor olun, Mobil&trade; markal&#305; endüstriyel ya&#287;lar ekipman&#305;n&#305;z&#305; düzgün çal&#305;&#351;&#305;r durumda tutabilir.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_pulpandpaper.aspx">Daha fazla bilgi &gt;</a></p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img title="Pegasus kanatlarla Demir Çelik Endüstrisi kova" src="/IND/English/Images/teaser_90x90_primary_metals.jpg" longdesc="" border="0" alt="Pegasus kanatlarla Demir Çelik Endüstrisi kova"><h3><a title="" href="yourindustry_primarymetals.aspx">demirçelik</a></h3><p>Demir ve çelik üretiminde daha yüksek enerji verimlili&#287;iyle daha h&#305;zl&#305; ve daha fazla üretime yard&#305;mc&#305; olmak üzere seçili MobilTM markal&#305; endüstriyel ya&#287;lara güvenin.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_primarymetals.aspx">Daha fazla bilgi &gt;</a></p><p></p></div><div class="item right"><img title="Pegasus kanatlarla &#304;&#351;leme Tesisi fabrikas&#305;" src="/IND/English/Images/teaser_90x90_process.jpg" longdesc="" border="0" alt="Pegasus kanatlarla &#304;&#351;leme Tesisi fabrikas&#305;"><h3><a title="" href="yourindustry_process.aspx">proses</a></h3><p>Herhangi bir türde i&#351;leme tesisi için yenilikçi servislerle desteklenen yüksek performansl&#305; ürünler sunar&#305;z.<br><a title="" href="yourindustry_process.aspx">Daha fazla bilgi &gt;</a></p><p></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry2.aspx">2</a></li><li><a href="yourindustry2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>