
				<%@ Page Language="C#"%>
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
				<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="it" lang="it"><head><title>Per contattarci &ndash; Lubrificanti Industriali |  Mobil&trade; Industrial Lubricants</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="Oli sintetici per barriere di tenuta, oli per catene e lubrificanti per forni, oli per compressori, liquidi refrigeranti, lubrificanti per accoppiamenti, fluidi da taglio, lubrificanti per motori elettrici, oli motore - lubrificanti per ingranaggi industriali, a gas, grassi, oli per il trasferimento termico, oli per il trattamento termico, oli idraulici, oli per guide e per macchine utensili, oli nebulizzatori, oli per macchine continue, oli per trasmissioni pneumatiche, oli per pompe a vuoto, oli refrigeranti, oli per laminatoi, antiruggine, oli per fusi, oli per cilindri di macchine a vapore, oli turbina, oli motore - grassi automobilistici, per telai e cuscinetti, filtri olio - lubrificanti per motori diesel, per binari, oli per cambi, differenziali e ponti"/><meta name="description" content="Contattate il nostro Help Desk Tecnico per richiedere assistenza tecnica su come  risolvere eventuali  problemi di lubrificazione o come migliorare la produttività dei vostri macchinari."/><meta name="date" content="09-2014"/><meta name="language" content="it"/><meta http-equiv="Content-Language" content="it"/><link type="text/css" rel="stylesheet" media="all" href="/imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/imports/js/xom.js"></script>
						<script type="text/javascript" src="/imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="4/12/2017 9:05:36 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/contactus_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Mobil SHC" src="Images/150x68_sidecallouts_mobilshc_image.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><br>
Mobil SHC&trade;<br><a target="" href="https://www.exxonmobil.com/pds?language=it">Schede tecniche dei prodotti (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/psims/psims.aspx">Schede &nbsp;di igiene e sicurezza dei prodotti (MSDS)</a></p></div></div><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Dove acquistare" src="Images/150x68_sidecallouts_where_to_buy_image.jpg" longdesc="" border="0" alt="Dove acquistare"><p xmlns=""><br>
Dove acquistare<br><a title="" target="" href="distributorlocator.aspx">Trovate l&rsquo;Authorized Distributor della ExxonMobil più vicino a voi</a></p></div></div><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Looble" src="Images/150x68_sidecallouts_looble1_image.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><br>
Selettore prodotti Looble<sup>SM</sup> (EN)<br><a title="This link will open a new window." target="_new" href="/Apps/ILS/default_EN.aspx">Trovate il lubrificante giusto per le vostre esigenze</a></p></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Informazioni sui lubrificanti industriali Mobil" src="Images/article_150x150-contact-us.jpg" longdesc="" border="0" alt="Informazioni sui lubrificanti industriali Mobil"></div><p xmlns=""><b><span style=" font-size: x-large;">Per contattarci</span></b></p><p xmlns="">Quando utilizzate i &nbsp;lubrificanti industriali Mobil&trade;, potete contattarci per richiedere assistenza tecnica su come risolvere eventuali problemi di lubrificazione o come migliorare la produttività dei vostri macchinari.</p><p xmlns="">Con un&rsquo;esperienza di oltre 150 anni nel settore della lubrificazione, supportata dalla nostra ampia banca dati e dal nostro Help Desk Tecnico, disponiamo degli strumenti necessari per assistervi i nelle seguenti aree:</p><ul xmlns=""><li>Richieste di informazioni su lubrificanti e lubrificazione in generale</li><li>Richieste di informazioni su specifiche, applicazioni e prestazioni dei prodotti industriali Mobil</li><li>Consigli sui lubrificanti più adatti in relazione all'utilizzo del macchinario &nbsp;e/o ai requisiti dei costruttori di &nbsp;macchinari (OEM)</li><li>Assistenza per richiesta di informazioni sul prodotto in tema di &nbsp;sicurezza, salute e ambiente</li><li>Come passare ai lubrificanti industriali Mobil</li><li>Assistenza sul programma &ldquo;Signum<sup>SM</sup> Oil Analysis&rdquo; della ExxonMobil</li><li>Fonti locali di approvvigionamento e contatti per grassi e lubrificanti industriali Mobil</li></ul><p xmlns="">Completate <a title="This link will open a new window." target="_new" href="http://www.mobil.com/contact-us?lang=IT">questo modulo </a>per contattarci via email (prima dell&rsquo;invio del modulo, vi verrà richiesto di accettare le nostre &ldquo;Note Legali&rdquo;), oppure chiamare il nostro <a title="" target="" href="contactus_technical-help-desks.aspx">Help Desk Tecnico</a>.</p><p xmlns=""></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>
