
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") || hostname.Contains("acptwip.mobil.com") )
							{		
								domain = "";
								
							
								
							} 
						else   
							{
								domain = "";
							}
						return domain;
					}
				</script>			
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
				<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="it" lang="it"><head><title>Advancing Productivity &ndash; Soluzioni per la sostenibilità del tuo business</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="Advancing Productivity, affidabilità dei macchinari, cura dell'ambiente, soluzioni per la sostenibilità, impegno per la sostenibilità, soluzioni di lubrificazione, lubrificanti industriali Mobil"/><meta name="description" content="Advancing Productivity è il nostro impegno a trovare soluzioni per la sostenibilità del business, basate su prodotti ad alte prestazioni, su servizi di lubrificazione e sulla competenza nel settore."/><meta name="date" content="03-2015"/><meta name="language" content="it"/><meta http-equiv="Content-Language" content="it"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/Imports/js/xom.js"></script>
						<script type="text/javascript" src="/Imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="12/9/2016 10:39:01 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/lubricationsolutions_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Mobil SHC" src="Images/150x68_sidecallouts_mobilSHC1.jpg" longdesc="" border="0" alt="Mobil SHC"><p xmlns=""><br>
Mobil SHC&trade;<br><a target="" href="http://www.exxonmobil.com/pdssearch/Search.aspx?chooseLanguage=it">Schede tecniche dei prodotti (PDS)</a><br><a title="This link will open a new window." target="_new" href="http://www.msds.exxonmobil.com/IntApps/psims/psims.aspx">Schede di igiene e sicurezza dei prodotti (MSDS)</a></p></div></div><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Where to buy" src="Images/150x68_sidecallouts_where_to_buy_image.jpg" longdesc="" border="0" alt="Where to buy"><p xmlns=""><br>
Dove acquistare<br><a title="This link will open a new window." target="_new" href="/ind/italian/distributorlocator.aspx">Trovate l&rsquo;Authorized Distributor della ExxonMobil più vicino a voi</a></p></div></div><div class="related"><div class="relatedimg150X68"><img xmlns="" title="Looble" src="Images/150x68_sidecallouts_looble1_image.jpg" longdesc="" border="0" alt="Looble"><p xmlns=""><br>
Selettore prodotti Looble<sup>SM</sup> (EN)<br><a title="This link will open a new window." target="_new" href="/ind/english/productselector.aspx">Trovate il lubrificante giusto per le vostre esigenze</a></p></div></div></div><div id="mainContent"><br/><div class="img150 left"><img xmlns="" title="Advancing Productivity" src="Images/150x150_top-productivity.jpg" longdesc="" border="0" alt="Advancing Productivity"></div><p xmlns=""><b><span style=" font-size: x-large;">Advancing Productivity</span></b><span style=" line-height: 24px;"><b><span style=" font-size: x-large;">&nbsp;</span></b></span></p><p xmlns=""><b><span style=" font-size: large;">Soluzioni di lubrificazione sostenibili per il tuo business</span></b></p><p xmlns="">Per le industrie di tutto il mondo, migliorare la produttività è una priorità assoluta. Molti fornitori di lubrificanti si limitano semplicemente a considerare questo aspetto, ma il team dei lubrificanti industriali Mobil&trade; riconosce che il successo di un'azienda richiede anche operazioni sostenibili.</p><p xmlns="">Oltre che sulla Produttività, c&rsquo;è da concentrarsi sulla Sicurezza, perchè nessuno si faccia male sul posto di lavoro oltre che sugli obiettivi di Rispetto per l'Ambiente per ridurre al minimo l'impatto della vostra attività.</p><p xmlns="">Noi chiamiamo &ldquo;<b>Advancing Productivity</b>&rdquo; questa visione tridimensionale della sostenibilità delle operazioni.</p><p xmlns="">Questi tre princìpi di <b>Advancing Productivity</b> sono in linea con il nostro impegno per la sostenibilità - bilanciare la crescita economica, lo sviluppo sociale e la tutela dell'ambiente in modo che le generazioni future non siano compromesse da azioni intraprese oggi. <b>Advancing Productivity</b> mette la sostenibilità in movimento.</p><p xmlns="">Abbiamo sviluppato per voi il concetto di <b>Advancing Productivity</b> con soluzioni di lubrificazione e di servizio tecnico che possono fornire vantaggi in tre aree fondamentali:</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial safety helmet, eye glasses and ear bud protection" src="Images/industrial-safety-helmet-eye-glasses-ear-protection.jpg" longdesc="" border="0" alt="Industrial safety helmet, eye glasses and ear bud protection"></div><p xmlns=""><b>Sicurezza</b><br>
La maggiore affidabilità dei macchinari e la lunga durata dei lubrificanti possono contribuire a limitare sia i potenziali rischi per i dipendenti sia la possibilità di perdite e fuoriuscite derivanti dal contatto diretto con le apparecchiature, fornendo lunghi intervalli di rilubrificazione e limitando la necessità di manutenzione rispetto agli oli convenzionali.</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial environmental care with two hands holding the world" src="Images/industrial-environmental-care-two-hands-world.jpg" longdesc="" border="0" alt="Industrial environmental care with two hands holding the world"></div><p xmlns=""><b>Rispetto per l'Ambiente<br></b>Rispetto agli oli convenzionali, i nostri lubrificanti con formule avanzate possono offrire benefici in termini di efficienza energetica che contribuiscono a ridurre i costi energetici e le emissioni di gas a effetto serra. Inoltre, molti di questi lubrificanti con formulazioni avanzate, offrono intervalli di manutenzione più lunghi che possono contribuire a ridurre la produzione di oli usati. Anche i grassi estendono la vita dei componenti, e ció riduce lo smaltimento delle attrezzature e la relativa manutenzione.</p><p xmlns=""></p><div class="imgns left"><img xmlns="" title="Industrial productivity with equipment gears" src="Images/industrial-productivity-equipment-gears.jpg" longdesc="" border="0" alt="Industrial productivity with equipment gears"></div><p xmlns=""><b>Produttività</b><br>
Rispetto agli oli convenzionali, la maggiore operatività ed efficienza delle apparecchiature può aumentare il vantaggio competitivo, contribuendo a ridurre i costi di produzione, le spese di manutenzione e di sostituzione delle apparecchiature.</p><p xmlns=""> Aiutarti a raggiungere gli obiettivi di sicurezza, di cura dell&rsquo;ambiente e di produttività con le nostre innovative soluzioni di lubrificazione è una delle nostre massime priorità. Questo è quello che intendiamo per Advancing Productivity. Ed è così che vi aiutiamo a raggiungere la visione più ampia di successo.</p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>