
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") || hostname.Contains("acptwip.mobil.com") )
							{		
								domain = "";
								
							
								
							} 
						else   
							{
								domain = "";
							}
						return domain;
					}
				</script>			
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
				<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="it" lang="it"><head><title>Efficienza Energetica | Mobil&trade; Industrial Lubricants</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="efficienza energetica, efficienza energetica industriale, prodotti per efficienza energetica"/><meta name="description" content="L&rsquo;innovazione del marchio Mobil in ambito industriale continua ad evolversi grazie ai nuovi progressi fatti nel campo dell&rsquo;efficienza energetica, attraverso lo sviluppo di lubrificanti che contribuiscono a migliorare le prestazioni dei macchinari e la produzione di energia riducendo, al tempo stesso, le emissioni di anidride carbonica."/><meta name="date" content="09/2014"/><meta name="language" content="it"/><meta http-equiv="Content-Language" content="it"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/Imports/js/xom.js"></script>
						<script type="text/javascript" src="/Imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="10/6/2016 5:02:37 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/lubricationsolutions_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--></div><div id="mainContent"><br/><p xmlns=""><b><span style=" font-size: large;">Prestazioni ottimali ed efficienza energetica.</span></b></p><p xmlns=""><b><span style=" font-size: small;">Un doppio vantaggio per la produttività.</span></b></p><p xmlns="">Da oltre 100 anni, i nostri prodotti innovativi hanno portato la tecnologia della lubrificazione in tutto il mondo. I lubrificanti industriali Mobil&trade; soddisfano le esigenze di macchinari e industrie in continua in evoluzione e sono supportati da un team globale che mette a disposizione la propria creatività, esperienza e soluzioni lungimiranti per aiutare le aziende ad ottenere il massimo dai macchinari.</p><p xmlns="">Questa innovazione continua ancora oggi con nuovi progressi nel campo di prodotti per il risparmio energetico, con lo sviluppo di lubrificanti che non solo aiutano i macchinari ad operare al massimo delle prestazioni, ma che contribuiscono anche a migliorare la produzione di energia riducendo, al tempo stesso, le emissioni di anidride carbonica.</p><p xmlns=""><br>
Tra i nostri lubrificanti a tecnologia avanzata figurano, ad esempio:</p><p xmlns=""><b><i><a title="" target="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel &trade; Serie</a></i></b>&mdash; oli idraulici all&rsquo;avanguardia che aiutano a raggiungere nuove vette di pulizia ed efficienza.</p><p xmlns=""><i><b><a title="" target="" href="products_mobil-shc_mobil-shc-pegasus-series.aspx">Mobil SHC Pegasus</a></b><b><a title="" target="" href="products_mobil-shc_mobil-shc-pegasus-series.aspx">&trade;</a></b></i><b><i>**</i></b> &mdash; uno degli oli per motori a gas migliori al mondo in termini di efficienza energetica e durata, che offre anche ottimi vantaggi in termini di risparmio di carburante.</p><p xmlns=""><i><b><a title="" target="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC</a></b><b><a title="" target="" href="products_mobil-shc_mobil-shc-600-series.aspx">&trade; serie </a><a title="" target="" href="products_mobil-shc_mobil-shc-600-series.aspx">600</a></b></i>&mdash; oli per sistemi di circolazione e ingranaggi le cui viscosità e proprietà, su un&rsquo;ampia gamma di applicazioni, migliorano in presenza di basse temperature.</p><p xmlns=""><i><b><a title="" target="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC</a></b><b><a title="" target="" href="products_mobil-shc_mobil-shc-gear-series.aspx">&trade; </a><a title="" target="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Gear </a></b></i>&mdash; lubrificanti per ingranaggi di ultimissima generazione dalle straordinarie prestazioni, che assicurano una lunga durata dell&rsquo;olio negli ingranaggi anche in condizioni estreme.</p><p xmlns=""><i><b><a title="" target="" href="products_mobil-shc_mobil-shc-500-series.aspx">Mobil SHC</a></b><b><a title="" target="" href="products_mobil-shc_mobil-shc-500-series.aspx">&trade; serie </a><a title="" target="" href="products_mobil-shc_mobil-shc-500-series.aspx">500</a></b></i>&mdash; oli idraulici a tecnologia avanzata per un&rsquo;eccellente protezione dall&rsquo;usura anche a diverse temperature e per tutti i settori industriali.</p><p xmlns=""><i><b><a title="" target="" href="products_mobil-shc_mobil-shc-cibus-series.aspx">Mobil SHC Cibus&trade; Serie</a></b></i>&mdash; lubrificanti per macchinari alimentari certificati NSF H1 che aiutano ad assicurare la qualità dei prodotti e, al tempo stesso, a migliorare la produttività degli impianti.</p><p xmlns=""><br>
Nel corso di test accurati, i lubrificanti industriali Mobil hanno dimostrato di essere in grado di offrire un significativo risparmio energetico rispetto agli oli convenzionali.* Anche un piccolo risparmio di energia può tradursi in un importante risparmio a livello economico e di risorse, ecco perchè l&rsquo;efficienza energetica in ambito industriale rappresenta un fattore importante per il futuro di tutti. Una protezione ottimale dei macchinari determina un miglioramento significativo dell&rsquo;efficienza energetica. Questo è solo un altro dei modi in cui i lubrificanti industriali Mobil possono far &ldquo;decollare&rdquo; la produttività e &ldquo;volare&rdquo; la vostra azienda!<br>
&nbsp;</p><div class="imgns left"><img xmlns="" title="Energy Efficiency Logo" src="Images/129x138_Energy_Efficiency_Logo.jpg" longdesc="" border="0" alt="Energy Efficiency Logo"></div><p xmlns=""><br><br><br><br><br><br><br><br>
&nbsp;</p><p xmlns=""><br><span style=" font-size: 8px;">Il simbolo &ldquo;energy efficiency&rdquo; è un marchio registrato della Exxon Mobil Corporation o di una delle società da questa direttamente e/o indirettamente possedute o controllate.&nbsp;</span></p><p xmlns=""><span style=" font-size: 8px;">* L&rsquo;efficienza energetica si riferisce soltanto alle prestazioni dei fluidi rispetto agli altri fluidi idraulici ExxonMobil. I test effettuati in applicazioni idrauliche standard, hanno mostrato che la tecnologia utilizzata consente di ottenere&nbsp;fino al 6% in più di efficienza energetica nelle pompe idrauliche rispetto ai prodotti Mobil DTE&trade; serie 20. L&rsquo;efficienza energetica dichiarata per questo prodotto si basa sui risultati di test sull&rsquo;uso di fluidi condotti in ambiente di laboratorio controllato, in conformità agli standard e ai protocoli industriali. I risultati effettivi possono variare a seconda delle condizioni operative. Per ulteriori informazioni si prega di contattare <a title="" target="" href="contactus_technical-help-desks.aspx">l&rsquo;Help Desk Tecnico ExxonMobil.</a></span></p><p xmlns=""><span style=" font-size: 8px;">**Il risparmio di carburante dei prodotti Mobil SHC Pegasus&trade; si riferisce &nbsp;solamente alle prestazioni dei fluidi rispetto agli oli convenzionali SAE&trade; 40 della ExxonMobil per motori a gas naturale . Come risulta da test effettuati su motori a gas naturale, in condizioni controllate, la tecnologia utilizzata consente di ottenere fino all&rsquo;1,5% in più in termini di risparmio di carburante rispetto ai prodotti Mobil Pegasus&trade; serie 1005 e &nbsp;serie 805. I miglioramenti a livello di risparmio di carburante possono variare a seconda delle condizioni operative. L&rsquo;efficienza energetica dichiarata per questo prodotto si basa sui risultati di test condotti sull&rsquo;uso di fluidi &nbsp;in conformità con gli standard e i protocolli industriali.</span></p></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>