
			
			<%@ Page Language="C#" AutoEventWireup="false" Inherits="XOM.Common.Web.XOMPage" %>
			<%@ Register TagPrefix="XOM" Namespace="XOM.Common.Web" Assembly="XOMCommon" %>
			
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
			<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" xml:lang="it" lang="it"><head><title>Mobil&trade; Industrial Lubricants prodotti sintetici, specifici per il settore industria</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="keywords" content="Sintetico, lubrificanti, energia, settore manifatturiero, prodotti della silvicoltura, carta, trasformazione, metalli, impianti per generare energia, prodotti alimentari e bevande, settore automobilistico, parti di ricambio, materie plastiche, Mobil SHC, Mobil DTE, Rarus, Mobilgear, industria, produttività, prestazioni, profitti, stabilimento, cemento"/><meta name="description" content="Sottolinea l'applicazione dei Mobil&trade; Industrial Lubricants- prodotti sintetici per specifici settori industriali. Descrive come i lubrificanti sintetici Mobil contribuiscono ad ottimizzare le prestazioni, ad aumentare la produttività ed a massimizzare i profitti."/><meta name="date" content="05-2009"/><meta name="language" content="it"/><meta http-equiv="Content-Language" content="it"/><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"/><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"/><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"/><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"/><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css"/>	
						<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
						<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
						<script language="Javascript" src="/Imports/js/xom.js"></script>
						<script type="text/javascript" src="/Imports/js/swfobject.js"></script>
						<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
							<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]--> 	<!--[if lte IE 6]>
							<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
						<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="5/26/2015 9:27:12 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body class="article"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/mobilshc_left_navigation.aspx"--><div id="toolbar"><!--#include virtual="Services/Toolbox.aspx"--><div class="related"><div class="relatedimg150X68"><a href="yourindustry.aspx"><img xmlns="" title="settore di attività " src="/IND/English/Images/150x68_sidecallouts_industry.jpg" longdesc="" border="0" alt="settore di attività "><p xmlns=""><a title="" target="" href="yourindustry.aspx"></a></p><p xmlns="">settori industriali<br><a title="" target="" href="yourindustry.aspx">Incrementate il potenziale delle macchine</a></p></a></div></div><div class="related"><div class="relatedimg150X68"><a href="productivity.aspx"><img xmlns="" title="produttività" src="/IND/English/Images/150x68_sidecallouts_productivity.jpg" longdesc="" border="0" alt="produttività"><p xmlns=""><a title="" target="" href="productivity.aspx"></a></p><p xmlns="">produttività<br><a title="" target="" href="productivity.aspx">Fate decollare la produttività</a></p></a></div></div></div><div id="mainContent"><h1><p xmlns=""><span style=" font-size: x-large;"><b>I sintetici e l'industria</b></span><b><br><span style=" font-size: medium;">Mobil SHC</span></b>&trade;<span style=" font-size: medium;"><b>: adatti a soddisfare le diverse esigenze</b></span></p></h1><br/><div class="img150 right"><img xmlns="" title="Mobil SHC products" src="/IND/English/Images/150x197_mobilSHC_products.jpg" longdesc="" border="0" alt="Mobil SHC products"></div><p xmlns="">Dal settore dell&rsquo;energia a quello manifatturiero, dalla produzione della carta alla trasformazione dei metalli, ogni settore può utilizzare e trarre vantaggio dai sintetici. Selezionate il settore in cui operate e scoprite i lubrificanti Mobil SHC più adatti alle vostre esigenze.</p><p xmlns=""><i><span style=" font-size: small;"><b>Energia<br></b></span></i>I Mobil SHC sono formulati per aiutare a rendere più produttivi gli impianti per la generazione di energia elettrica. Più le vostre macchine sono produttive, maggiore è il loro rendimento. Più è alto il rendimento, maggiore è il ritorno economico.</p><p xmlns="">I prodotti:<br>
Mobil SHC&trade; 600, Mobil SHC&trade; Gear, Mobilith SHC&trade;, Mobil SHC&trade; Rarus Serie 1020, e Mobil Rarus&trade; Serie 800</p><p xmlns="">Cliccate sui link riportati qui di seguito per avere maggiori informazioni sui prodotti:<br><a title="" target="" href="yourindustry_energy_wind_schematic.aspx">Turbina eolica</a><br><a title="" target="" href="yourindustry_energy_gasturbines_schematic.aspx">Impianto a turbine a gas ed a vapore</a><br><a title="" target="" href="yourindustry_energy_gasengine_gasschematic.aspx">Impianto di cogenerazione</a><br><a title="" target="" href="yourindustry_energy_gasengine_gasschematic.aspx">Impianto di compressione metano</a><br><a title="" target="" href="yourindustry_energy_gasengine_bioschematic.aspx">Centrale elettrica a biogas<br></a><a title="" target="" href="yourindustry_energy_coal_schematic.aspx">Centrale elettrica a carbone</a></p><p xmlns=""><i><b>Settore manifatturiero e alimentare<br></b></i>Che si tratti di prodotti alimentari e bevande, di macchine utensili o di materie plastiche fate &ldquo;decollare&rdquo; la produttività dei vostri impianti con l&rsquo;aiuto dei lubrificanti Mobil SHC.</p><p xmlns="">I prodotti:<br>
I Mobil SHC Serie 600, Mobil SHC&trade; Serie 500, Mobilith SHC, Mobiltemp SHC&trade;, Mobil SHC Rarus Serie 1020, Mobil Rarus Serie 800 e Mobil Synthetic Chain sono lubrificanti formulati per essere reciprocamente compatibili e vantano l'esperienza pluridecennale Mobil nella gestione dei fluidi.</p><p xmlns="">Cliccate sui link qui di seguito per avere maggiori informazioni sui prodotti:<br><a title="" target="" href="yourindustry_manufacturing_food.aspx">Industria dei prodotti alimentari e delle bevande</a><br><a title="" target="" href="yourindustry_manufacturing_machining.aspx">industria manifatturiera e alimentare<br></a><a title="" target="" href="yourindustry_manufacturing_plastics.aspx">Industria delle materie plastiche</a></p><p xmlns=""><i><b>Industrie di processo<br></b></i>Non importa il tipo di ciclo produttivo, i Mobil SHC sono prodotti che offrono elevate prestazioni formulati per aiutare a far &ldquo;decollare&rdquo; la produttività.</p><p xmlns="">I prodotti:<br>
Mobil SHC Serie 600, Mobil SHC Serie 500, Mobil SHC Gear e Mobil SHC Rarus Serie 1020</p><p xmlns="">Cliccate sui link qui di seguito per avere maggiori informazioni sui prodotti:<br><a title="This link will open a new window." target="_new" href="/IND/English/files/st_cement.pdf">Industria del cemento<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br><a title="This link will open a new window." target="_new" href="/IND/English/files/st_chemical.pdf">Industria chimica<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
&nbsp;</p><p xmlns=""><i><b>Produzione della carta<br></b></i>Raggiungere prestazioni ottimali ed ottimizzare la resa degli impianti sono fattori chiave per essere competitivi nell'industria della carta. I lubrificanti Mobil SHC possono aiutarvi a raggiungere questi obiettivi.</p><p xmlns="">I prodotti:<br>
Mobil SHC Serie 600, Mobil SHC&trade; Gear, Mobilith SHC, Mobil SHC Rarus Serie 1020 ed i Mobil Rarus Serie 800 aiutano a ridurre al massimo i tempi di manutenzione e l'esigenza di accedere a punti di lubrificazione difficili da raggiungere.</p><p xmlns="">Cliccate sul link qui di seguito per avere maggiori informazioni sui prodotti:<br><a title="This link will open a new window." target="_new" href="/IND/English/files/st_paper.pdf">Industria della carta<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</p><p xmlns=""><i><b>Metalli<br></b></i>La produzione dei metalli presenta alcune delle sfide più impegnative della lubrificazione. I lubrificanti Mobil SHC sono formulati per essere utilizzati in qualsiasi situazione, dai forni a colata continua ai laminatoi e agli organi di sollevamento, in condizioni di temperature elevate, carichi pesanti e contaminazioni.</p><p xmlns="">I prodotti:<br>
Mobil SHC Serie 600, Mobil SHC Gear, Mobilith SHC, Mobil SHC Rarus Serie 1020 ed i Mobil Rarus Serie 800</p><p xmlns="">Cliccate sul link qui di seguito per avere maggiori informazioni sui prodotti:<br><a title="This link will open a new window." target="_new" href="/IND/English/files/st_steel.pdf">Industria dell'acciaio<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
&nbsp;</p><div class="quicklinks"><div class="headerbar"><h3 class="nolink">approfondimenti</h3></div><ul><li><a xmlns="" title="This link will open a new window." target="_new" href="/IND/english/files/br_mobil_shc.pdf">brochure Mobil SHC&trade;<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</li><li><a xmlns="" title="This link will open a new window." target="_new" href="/IND/english/files/schm_gearbox.pdf">schema riduttore<img src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</li></ul></div></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>