
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="it" lang="it" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrificanti e grassi per macchine per panificazione | Mobil&trade;-Branded Industrial Lubricants</title><meta name="keywords" content="Macchinari latte, lubrificanti macchinari latte, lavorazione latte, lubrificanti lavorazione latte"><meta name="description" content="I Mobil&trade; Industrial Lubricants sono efficaci per le macchine per la lavorazione del latte, ed apportano benefici in termini di durata in servizio delle macchine, riduzione dei costi di manutenzione e diminuzione dei cambi d'olio."><meta name="date" content="08/2014"><meta name="language" content="it"><meta http-equiv="Content-Language" content="it"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/1/2015 11:27:04 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_manufacturing_food_dairy_link.html"--></p><p><span style=" font-size: x-large;"><b>Lavorazione dei derivati del latte</b></span></p><p>I lubrificanti <a title="" href="products_mobil-shc_mobil-shc-cibus-series.aspx">Mobil SHC Cibus&trade;</a> i grassi Mobilgrease&trade; FM, <a title="" href="products_mobil-shc_mobil-shc-polyrex-series.aspx">Mobil SHC Polyrex&trade;</a> ed altri lubrificanti Mobil&trade; per macchine alimentari sono particolarmente efficaci per l'impiego nell'industria della lavorazione del latte, e molti di essi offrono innovazioni e benefici in termini di prestazioni che vanno oltre le potenzialità degli oli minerali. Data la rigidità delle condizioni che caratterizzano molti aspetti delle attività di lavorazione del latte - come calore, freddo e umidità estremi - i lubrificanti Mobil per macchine alimentari sono stati sviluppati con specifiche proprietà per contribuire al miglioramento della produttività. Esse contribuiscono a prolungare la durata in servizio dei componenti delle macchine e a ridurre i cambi olio, nonché a diminuire o eliminare i guasti alle attrezzature e i fermi non programmati.</p><p>Che produciate formaggio o yogurt, panna, burro o latte scremato, i lubrificanti Mobil per macchine alimentari - utilizzati su componenti come cuscinetti a sfere o a rulli, slitte, catene o convogliatori - &nbsp;contribuiscono, insieme al vostro sistema di gestione e analisi dei rischi HACCP (Hazard Analysis and Critical Control Points), a una produzione alimentare sicura.</p><p><b>Lubrificanti macchine alimentari</b><br>
I lubrificanti Mobil SHC Cibus sono a base di oli sintetici e offrono quindi lubrificazione di qualità con possibili vantaggi di durata prolungata, costi di manutenzione inferiori e risparmi energetici rispetto agli oli minerali convenzionali. Inoltre, gli stessi lubrificanti Mobil SHC Cibus possono essere utilizzati a monte e a valle della gamma di lavorazione, contribuendo così a contenere le giacenze e a ridurre al minimo il rischio di utilizzo di lubrificanti non registrati nella categoria NSF H1 in applicazioni alimentari sensibili.</p><p>Per la lubrificazione a grasso, Mobil SHC Polyrex e Mobilgrease FM offrono eccellente tolleranza all'acqua, protezione anticorrosione e stabilità strutturale per intervalli di lubrificazione prolungati e protezione a lungo termine delle attrezzature.</p><p>Le serie Mobil SHC Cibus, Mobil SHC Polyrex e Mobilgrease FM sono prodotti all&rsquo;interno di stabilimenti certificati ISO 21469, un&rsquo;ulteriore conferma del fatto che questi lubrificanti rispondono agli standard di sicurezza alimentare della vostra azienda. &nbsp;</p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Diagramma per conoscere un caseificio" title="Diagramma per conoscere un caseificio" longdesc="" src="/IND/English/Images/teaser_60x60_explore-a-dairy-plant.jpg" border="0"></img><h3><a title="" href="yourindustry_manufacturing_food_dairy_schematic.aspx">alla scoperta di un caseificio</a></h3><p>Scoprite come migliorare la produttività del vostro caseificio<br></p></div><div class="item right"><img alt="Stabilimento per la lavorazione di prodotti caseari" title="Stabilimento per la lavorazione di prodotti caseari" longdesc="" src="/IND/English/Images/teaser_60x60_dairy-plant-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/schm_food_dairy.pdf">stabilimento per la lavorazione di prodotti caseari<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scopri come possiamo aiutare a mantenere il vostro impianto di<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; trasformazione lattiero-casearia al top<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; della forma<br></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img alt="Brochure lubrificanti per macchinari del settore caseario" title="Brochure lubrificanti per macchinari del settore caseario" longdesc="" src="/IND/English/Images/teaser_60x60-food-machinery-lubricants-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/italian/files/br_food_it.pdf">brochure lubrificanti per macchinari del settore alimentare<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Scoprite come possiamo aiutarvi a proteggere il vostro clienti e la vostra<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; azienda<br></p></div><div class="item right"><img alt="Scheda tecnica lubrificanti Mobil SHC Cibus Serie per il settore della lavorazione di prodotti caseari" title="Scheda tecnica lubrificanti Mobil SHC Cibus Serie per il settore della lavorazione di prodotti caseari" longdesc="" src="/IND/English/Images/teaser_60x60-mobil-shc-cibus-series-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/italian/files/ss_shc_cibus_it.pdf">scheda tecnica Mobil SHC Cibus Serie&trade;<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a></h3><p>Scoprite i lubrificanti che aiutano a proteggere i macchinari alimentari<br></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img alt="Scheda tecnica lubrificanti Mobilgrease FM Serie per il settore caseario e alimentare" title="Scheda tecnica lubrificanti Mobilgrease FM Serie per il settore caseario e alimentare" longdesc="" src="/IND/English/Images/teaser_60x60_mobilgrease-fm-series-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/ss_mobilgrease_fm.pdf">scheda tecnica Mobilgrease&trade; FM Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite come i nostri grassi possono aiutare i vostri macchinari a raggiungere<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;il massimo delle prestazioni<br></p></div><div class="item right"><img alt="Scheda tecnica lubrificanti Mobil Gargoyle Arctic SHC Serie per impianti industriali di refrigerazione " title="Scheda tecnica lubrificanti Mobil Gargoyle Arctic SHC Serie per impianti industriali di refrigerazione " longdesc="" src="/IND/English/Images/teaser_60x60_mobil-gargoyle-arctic-shc-series-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/ss_gargoyle_arctic_shc.pdf">scheda tecnica Mobil Gargoyle Arctic SHC&trade; Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite come proteggere i vostri impianti industriali per la refrigerazione<br></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img alt="Scheda tecnica lubrificanti Mobil EAL Arctic Serie per impianti industriali di refrigerazione per caseifici" title="Scheda tecnica lubrificanti Mobil EAL Arctic Serie per impianti industriali di refrigerazione per caseifici" longdesc="" src="/IND/English/Images/teaser_60x60_mobil-eal-arctic-series-fact-sheet.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/ss_eal_arctic.pdf">scheda tecnica Mobil EAL Arctic&trade; Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite i lubrificanti che aiutano gli impianti di refrigerazione a funzionare in<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;maniera efficiente e nel rispetto<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;dell&rsquo;ambiente<br></p></div><div class="item right"><img alt="Tabella per la selezione degli oli per la refrigerazione degli impianti industriali caseari &nbsp;" title="Tabella per la selezione degli oli per la refrigerazione degli impianti industriali caseari &nbsp;" longdesc="" src="/IND/English/Images/teaser_60x60-refrigeration-oils-selector-chart.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/sc_refrigeration.pdf">oli per la refrigerazione &ndash; tabella per la selezione<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Trovate il lubrificante industriale per la refrigerazione più adatto alle vostre<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; esigenze<br></p></div></div><p></p><div class="itemgroup clrfix"><div class="item left"><img alt="Oli industriali per la refrigerazione per il settore caseario - Argomento tecnico" title="Oli industriali per la refrigerazione per il settore caseario - Argomento tecnico" longdesc="" src="/IND/English/Images/teaser_60x60_refrigeration-oils-tech-topic.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/tt_refrigeration.pdf">oli per la refrigerazione &ndash; argomento tecnico<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite come scegliere il lubrificante giusto per il vostro impianto di<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;refrigerazione<br></p></div><div class="item right"><img alt="Oli industriali per la refrigerazione per il settore caseario - Argomento tecnico" title="Oli industriali per la refrigerazione per il settore caseario - Argomento tecnico" longdesc="" src="/IND/English/Images/teaser_60x60-food-machinery-lubricants-selection-guide.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/mobil-food-machinery-lubricants-guide.pdf">brochure caseifici<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite come possiamo aiutarvi a mantenere i vostri impianti caseari in perfette condizioni<br></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_manufacturing_food_dairy2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_manufacturing_food_dairy2.aspx">2</a></li><li><a href="yourindustry_manufacturing_food_dairy2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>