
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="it" lang="it" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Esplorazione e Estrazione di Petrolio e Gas &ndash; Settore Energetico | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="Esplorazione di petrolio e gas, estrazione di petrolio e gas, lubrificanti Mobil SHC a base di olio, esplorazione e estrazione di energia, lubrificanti sintetici"><meta name="description" content="I lubrificanti industriali Mobil&trade; per il settore energetico dell&rsquo;esplorazione e dell&rsquo;estrazione sono formulati per gli ambienti operativi dell&rsquo;industria dell&rsquo;esplorazione e l&rsquo;estrazione di petrolio e gas."><meta name="date" content="08/2014"><meta name="language" content="it"><meta http-equiv="Content-Language" content="it"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/1/2015 11:22:07 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_energy_oilandgas_link.html"--></p><p><span style=" font-size: x-large;"><b>Aumentare la produttività</b></span></p><p><span style=" font-size: large;"><b>Soluzioni e servizi per l&rsquo;esplorazione e l&rsquo;estrazione di petrolio e gas<br></b></span><br>
Mettiamo a vostra disposizione oltre 100 anni di competenza, una gamma completa di soluzioni all'avanguardia e di servizi che non si limitano a far funzionare le macchine. Anche in condizioni operative estreme, i lubrificanti Mobil SHC&trade; hanno dimostrato di contribuire ad allungare la durata dei componenti dei macchinari e di ridurre i cambi d&rsquo;olio, offrendo così un potenziale per diminuire o eliminare &nbsp;guasti e fermi macchina non programmati rispetto agli oli convenzionali.</p><p>La nostra gamma &nbsp;di lubrificanti premium sintetici e a base minerale &nbsp;per i macchinari del settore energetico dell&rsquo;esplorazione e dell&rsquo;estrazione, compresi gli oli per motori, gli oli idraulici, gli oli per turbine, per compressori e per ingranaggi, è stata formulata per la grande &nbsp;varietà ambienti operativi di questo settore di attività:*</p><p>&bull; <b><a title="" href="products_mobil-shc_mobil-shc-pegasus-series.aspx">Mobil SHC Pegasus&trade;</a> &nbsp;</b>olio per motori a gas che offre vantaggi di efficienza energetica<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobill SHC&trade; serie 600</a></b>oli per ingranaggi e sistemi di circolazione dalle prestazioni eccezionali<br>
&bull; <b><a title="" href="products_greases_mobilith-shc-grease-series.aspx">Mobilith SHC&trade; Serie</a></b> grassi sintetici per applicazioni esigenti<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-polyrex-series.aspx">Mobil SHC Polyrex&trade; Serie</a></b> grasso sintetico per applicazioni a temperature estreme<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-gear-series.aspx">Mobil SHC&trade; Gear Serie</a></b> oli per ingranaggi e cuscinetti dalle prestazioni eccellenti<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-rarus-shc-1020-series.aspx">Mobil Rarus SHC&trade; serie 1020</a></b> oli sintetici per pompe ausiliarie e compressori d&rsquo;aria &nbsp;<br>
&bull; <b><a title="" href="products_mobil-dte-800-series.aspx">Mobil DTE&trade; serie 800</a></b>oli ad alte prestazioni per turbine a gas<br>
&bull; <b><a title="" href="products_mobil-pegasus-1005.aspx">Mobil Pegasus&trade; 1005</a> &nbsp;</b>oli ad alte prestazioni per motori a gas naturale<br>
&bull; <b><a title="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel&trade; Serie</a>**</b> oli per sistemi idraulici che offrono vantaggi di efficienza energetica<br>
&bull; <b>Mobilgard&trade;</b> oli per motori diesel per la marina e l&rsquo;industria<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-800-series.aspx">Mobil SHC&trade; serie 800</a></b> oli dalle prestazioni eccezionali per turbine a gas<br>
&bull; <a href="http://www.mobil.us/USA-English-LCW/heavydutyengineoils_products_engine-oils_mobil-delvac-1-esp-5w40.aspx"><b>Mobil Delvac&trade;</b></a> olio per motori diesel ad alte prestazioni per applicazioni estreme</p><p><span style=" font-size: x-small;">* Consultate il manuale del costruttore per la scelta del lubrificante più adatto in funzione del macchinario e delle condizioni operative.<br>
**L&rsquo;efficienza energetica si riferisce soltanto alle prestazioni dei fluidi rispetto ai fluidi idraulici convenzionali della ExxonMobil. &nbsp;I test effettuati in applicazioni idrauliche standard, hanno mostrato che &nbsp;la tecnologia utilizzata consente di ottenere &nbsp;fino al 6% in più di efficienza energetica nelle pompe idrauliche rispetto ai prodotti Mobil DTE&trade; serie 20. L&rsquo;efficienza energetica dichiarata per questo prodotto si basa sui risultati di test sull&rsquo;uso di i fluidi&nbsp;condotti in ambiente di laboratorio controllato, in conformità agli standard e ai protocoli industriali. I risultati effettivi possono variare a seconda delle condizioni operative. Per ulteriori informazioni si prega di contattare <a title="" href="contactus_technical-help-desks.aspx">l&rsquo;Help Desk Tecnico ExxonMobil</a>. &nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;&nbsp;&nbsp;</p><p><b>Raccomandazioni di alcuni dei principali costruttori di macchinari a livello globale e prestazioni comprovate sul campo.</b><br>
Accuratamente testati prima di essere commercializzati, i lubrificanti e i grassi industriali Mobil&trade; godono di un&rsquo;ampia gamma di approvazioni di &nbsp;alcuni dei principali costruttori di macchinari. Soddisfano gli standard di qualità a livello globale e sono compatibili con i rigorosi sistemi interni di gestione relativi alla produzione, al servizio clienti, ai laboratori, alla sicurezza, alla salvaguardia della salute e al rispetto dell&rsquo;ambiente.</p><p><b>Forniamo il supporto di cui avete bisogno</b><br>
Grazie all&rsquo;affidabilità dei nostri servizi non sarete mai soli :***</p><p><b>Help Desk Tecnico ExxonMobil </b>&ndash; Un'adeguata assistenza da parte del nostro team di ingegneri, disponibile telefonicamente oppure on-line, in grado di offrire indicazioni e consulenza specifiche.</p><p><b>Distributor Sales Representatives (DSR) </b>&ndash; Un aiuto sul campo per la scelta del lubrificante più adatto che può contribuire ad aumentare la produttività dello stabilimento.</p><p><b>Team di ingegneri della ExxonMobil (LFE- Lubes Field Engineer) </b>&ndash; Una consulenza professionale sulle pratiche di lubrificazione, per contribuire ad ottimizzare le prestazioni del lubrificante e risolvere eventuali problemi dei macchinari. Ispezioni degli impianti e monitoraggio proattivo per aiutarvi a far funzionare i macchinari più a lungo e in modo più efficiente.</p><p><b>Programma Signum<sup>SM</sup> Oil Analysis </b>&ndash; Controlla le condizioni dei lubrificanti e dei macchinari per contribuire ad aumentarne la durata, l'affidabilità e a ridurre i costi di manutenzione. Appositamente studiato per il settore delle lavorazioni meccaniche, per la misurazione degli indicatori critici dell'olio usato, il programma offre le conoscenze specifiche necessarie per conoscere meglio i lubrificanti e le condizioni dei macchinari.</p><p>Scegliete la tecnologia d&rsquo;avanguardia e l&rsquo;esperienza nelle applicazioni dei lubrificanti industriali Mobil per aiutare i vostri macchinari a produrre di più, meglio e più velocemente, contribuendo a prolungarne la durata operativa e aumentarne l&rsquo;efficienza.</p><p><span style=" font-size: x-small;">*** Consultate il vostro referente di zona della ExxonMobil (DBC) per verificare la disponibilità nella vostra area.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Brochure sull&rsquo;esplorazione e l&rsquo;estrazione di petrolio e gas" title="Brochure sull&rsquo;esplorazione e l&rsquo;estrazione di petrolio e gas" longdesc="" src="/IND/English/Images/teaser_60x60-oil-and-gas-exploration-and-production-brochure.jpg" border="0"></img><h3><a target="_new" href="/IND/English/files/br_oilandgas.pdf">brochure sulla esplorazione e estrazione di gas e petrolio<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)</h3><p>Scoprite come possiamo aiutarvi<br></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_energy_oilandgas2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_energy_oilandgas2.aspx">2</a></li><li><a href="yourindustry_energy_oilandgas2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>