
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="it" lang="it" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrificanti per l&rsquo;Industria della Cellulosa e della Carta | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="industria della carta e della pasta, olio per macchine carta , lubrificanti industriali , lubrificanti industriali Mobil , serie Mobil SHC PM , Mobilith SHC , Mobilgear , Mobilith SHC"><meta name="description" content="I lubrificanti sintetici Mobil SHC&trade; per macchinari dell&rsquo;industria della carta forniscono oli ad alte prestazioni, formulati per soddisfare la vasta gamma di applicazioni dell&rsquo;industria della cellulosa e della carta."><meta name="date" content="09/2014"><meta name="language" content="it"><meta http-equiv="Content-Language" content="it"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/1/2015 11:34:16 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><h1></h1><p><!-- #include virtual="yourindustry_pulpandpaper_link.html"--></p><p><span style=" font-size: x-large;"><b>Al servizio della produttività nell&rsquo;industria della cellulosa</b></span></p><p><span style=" font-size: x-large;"><b>e della carta</b></span></p><p><span style=" font-size: large;"><b>Mobil SHC&trade; - &nbsp;Lubrificanti sintetici per macchinari dell&rsquo;industria della carta</b></span></p><p>Sia che stiate producendo carta da giornale, carta fine o cartone ondulato, l&rsquo;efficienza dei macchinari è fondamentale per massimizzare la produttività. Le tue macchine devono mantenere un&rsquo;operatività continua e, nel settore della cellulosa e della carta dove i macchinari lavorano a una velocità di oltre 2.000 m/min e con temperature che superano i 200°C (392°F), i &nbsp;macchinari sono costantemente sotto pressione.</p><p><b>Mobil SHC&trade; PM Serie e Mobilith SHC&trade; PM Serie&nbsp;</b>&nbsp;<br>
La nostra intera gamma di grassi e oli sintetici per sistemi di circolazione ad alte prestazioni è formulata per soddisfare l&rsquo;ampia serie di applicazioni e condizioni dell&rsquo;industria della cellulosa e della carta.</p><p>Formulati con tecnologia sintetica all&rsquo;avanguardia e competenza applicativa, questi prodotti possono aiutare ad aumentare l&rsquo;efficienza dei macchinari, riducendo al minimo i tempi d&rsquo;inattività e le spese operative. Sono concepiti per durare più a lungo rispetto agli oli minerali convenzionali.</p><p>Inoltre, offriamo &nbsp;un&rsquo;ampia &nbsp;gamma di lubrificanti premium sintetici e a base minerale per macchinari dell&rsquo;industria della carta, tra cui oli per circuiti idraulici, compressori e ingranaggi, tutti formulati per i diversi ambienti operativi di lavorazione della cellulosa e della carta.*</p><p>&bull; <b>Mobil SHC&trade; PM Serie</b> oli sintetici ad alte prestazioni per sistemi di circolazione per applicazioni su asciugatrici e calandre<br>
&bull; <b>Mobil DTE&trade; PM Serie</b> oli premium per macchinari da cartiera a base d&rsquo;olio minerale per sistemi di circolazione in condizioni di asciutto o bagnato<br>
&bull; <b>Mobil DTE Excel&trade; Serie </b>oli premium per sistemi di circolazione antiusura per calandre e sessioni di stampa<br>
&bull; <b><a title="" href="products_mobil-shc_mobilith-shc-pm-series.aspx">Mobilith SHC&trade; PM Serie</a></b> grassi sintetici ad alte prestazioni per macchinari da cartiera e per applicazioni su cuscinetti in condizioni di asciutto o bagnato<br>
&bull; <b>Mobilgear SHC&trade; XMP Serie</b> oli sintetici ad altissime prestazioni per ingranaggi, cuscinetti e guarnizioni<br>
&bull; <b><a title="" href="products_mobil-shc_mobil-shc-600-series.aspx">Mobil SHC&trade; serie 600</a></b> oli per sistemi di circolazione e ingranaggi ad alte prestazioni per una vasta gamma di applicazioni critiche<br>
&bull; <b>Mobilgear SHC&trade; Serie</b> olio sintetico ad alte prestazioni a pressioni estreme per ingranaggi<br>
&bull; <b><a title="" href="products_mobilgear-600-xp-series.aspx">Mobilgear&trade; 600 XP Serie</a></b> oli premium per ingranaggi, cuscinetti e guarnizioni<br>
&bull; <b><a title="" href="products_mobil-dte-10-excel-series.aspx">Mobil DTE 10 Excel&trade; Serie</a></b> oli antiusura con resistenza al taglio e con un alto indice di viscosità per impianti idraulici<br>
&bull; <b><a title="" href="products_mobil-dte-20-series.aspx">Mobil DTE&trade; 20 Serie</a></b> oli antiusura per impianti idraulici</p><p><span style=" font-size: x-small;">* Consultate il manuale del costruttore per la scelta del lubrificante più adatto in funzione del macchinario e delle condizioni operative.</span></p><p><b>Competenza di livello mondiale e approvazione dei costruttori di macchinari</b><br>
Il nostro team di ingegneri (FES - Field Engineering Services) collabora con i clienti e i principali costruttori di macchinari per acquisire le informazioni necessarie per lo sviluppo di prodotti in linea con le nuove tecnologie e i requisiti di lubrificazione. I lubrificanti sintetici Mobil SHC&trade; sono approvati dai principali OEM del settore e apprezzati per le loro prestazioni affidabili e il loro contributo alla massima protezione dei macchinari.</p><p><b>Forniamo il supporto di cui avete bisogno</b><br>
Grazie all&rsquo;affidabilità dei nostri servizi non sarete mai soli.**</p><p><b>Help Desk Tecnico ExxonMobil</b> &ndash; Un'adeguata assistenza da parte del nostro team di ingegneri, disponibile telefonicamente oppure on-line, in grado di offrire indicazioni e consulenza specifiche.</p><p><b>Distributor Sales Representatives (DSR)</b> &ndash; Un aiuto sul campo per la scelta del lubrificante più adatto che può contribuire ad aumentare la produttività dello stabilimento.</p><p><b>Team di ingegneri della ExxonMobil (LFE- Lubes Field Engineer)</b>&ndash; Una consulenza professionale sulle pratiche di lubrificazione, per contribuire ad ottimizzare le prestazioni del lubrificante e risolvere eventuali problemi dei macchinari. &nbsp;Ispezioni degli impianti e monitoraggio proattivo per aiutarvi a far funzionare i macchinari più a lungo e in modo più efficiente.</p><p><b>Programma Sygnum</b><sup><b>SM</b></sup><b> Oil Analysis </b>&ndash; Controlla le condizioni dei lubrificanti e dei macchinari per contribuire ad aumentarne la durata, l'affidabilità e a ridurre i costi di manutenzione. Appositamente studiato per il settore delle lavorazioni meccaniche, per la misurazione degli indicatori critici dell'olio usato, il programma offre le conoscenze specifiche necessarie per conoscere meglio i lubrificanti e le condizioni dei macchinari.</p><p><span style=" font-size: x-small;">**Consultate il vostro referente di zona della ExxonMobil (DBC) per verificare la disponibilità nella vostra area.</span></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Macchinari per la produzione della carta" title="Macchinari per la produzione della carta" longdesc="" src="/IND/English/Images/teaser_60x60_explore_pulp_and_paper_plant.jpg" border="0"></img><h3></h3><p><a href="/ind/english/yourindustry_pulpandpaper_plant_schematics.aspx">visitate l&rsquo;impianto della cellulosa e della carta</a>&nbsp; (EN)<br>
Scoprite come migliorare la produttività dell&rsquo;impianto della cellulosa e della<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;carta</p><p></p></div><div class="item right"><img alt="Scheda tecnica Mobil SHC PM Serie" title="Scheda tecnica Mobil SHC PM Serie" longdesc="" src="/IND/English/Images/teaser_60x60_mobilSCH_PM_fact_sheet.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English//files/ss_shc_pm.pdf">scheda tecnica Mobil SHC&trade; PM &nbsp;Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a> (EN)<br>
Scoprite come i nostri lubrificanti aiutano a proteggere i macchinari</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Processo di produzione dell&rsquo;industria della carta " title="Processo di produzione dell&rsquo;industria della carta " longdesc="" src="/IND/English/Images/teaser_60x60_pulp_and_paper_brochure.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/files/br_pulp_and_paper.pdf">brochure dell&rsquo;industria della cellulosa e della carta<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Scoprite come possiamo aiutarvi a mantenere il vostro impianto al top della<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;forma</p><p></p></div><div class="item right"><img alt="Scheda tecnica Mobil DTE PM Serie" title="Scheda tecnica Mobil DTE PM Serie" longdesc="" src="/IND/English/Images/teaser_60x60_mobilDTE_PM_fact_sheet.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/files/ss_dte_pm.pdf">scheda tecnica Mobil DTE&trade; PM Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp; (EN)<br>
Ulteriori informazioni sui lubrificanti &nbsp;formulati per sistemi di circolazione dei<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;macchinari per l&rsquo;industria della carta</p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Scheda tecnica Mobilith SHC PM Serie" title="Scheda tecnica Mobilith SHC PM Serie" longdesc="" src="/IND/English/Images/teaser_60x60_mobilithSHC_PM_fact_sheet.jpg" border="0"></img><h3></h3><p><a target="_new" href="/IND/English/files/ss_mobilith_shc_pm.pdf">scheda tecnica Mobilith SHC&trade; PM Serie<img style="display:inline; float:none; margin:0 0 -3px 0; width:auto;" src="/Images/Icons/icon_pdf_whitespace.jpg" border="0" alt=""></a>&nbsp;(EN)<br>
Scoprite come i nostri grassi aiutano i macchinari dell&rsquo;industria della carta a<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;raggiungere il massimo delle loro<br>
&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;prestazioni</p><p></p></div><div class="item right"><h3></h3></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry_pulpandpaper2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry_pulpandpaper2.aspx">2</a></li><li><a href="yourindustry_pulpandpaper2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>