
			
				<%@ Page Language="C#"%>
				<script runat=server>
					protected String GetDomain()
					{
						string hostname = Request.ServerVariables.Get("SERVER_NAME");
						string domain = string.Empty;
						if (hostname.Contains("www.mobilindustrial.com") )
							{
								domain = "http://www.mobil.com.cn";
							} 
						else
							{
								domain = "";
							}
						return domain;
					}
				</script>					
				<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			
		<html xml:lang="it" lang="it" xmlns="http://www.w3.org/1999/xhtml"><head xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format"><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><meta http-equiv="X-UA-Compatible" content="IE=8"><title>Lubrificanti Industriali per i Macchinari del Vostro Settore | Mobil&trade; Industrial Lubricants</title><meta name="keywords" content="produttività, resa, mantenere un funzionamento regolare, aumentare l'affidabilità dei macchinari, ridurre i costi di esercizio, prolungare la durata delle macchine, energia, general manifacturing, prodotti petrolchimici, trasformazione, cemento, alimentari, bevande, carta, prodotti forestali, metalli primari, acciaio, competenza nel settore, esperti, requisiti di lubrificazione, lubrificanti all'avanguardia, gamma completa di applicazioni industriali, lubrificanti all'avanguardia, applicazioni industriali, pratiche sulla lubrificazione, selezione di lubrificanti adeguati, ricerca e riparazione dei guasti, servizi di lubrificazione, massima produttività"><meta name="description" content="I lubrificanti industriali Mobil&trade; sono concepiti per aiutarvi a mantenere il funzionamento ottimale dei macchinari,migliorare la loro affidabilità e molto altro ancora."><meta name="date" content="08/2014"><meta name="language" content="it"><meta http-equiv="Content-Language" content="it"><link type="text/css" rel="stylesheet" media="all" href="/Imports/mobil_ind.css"><link type="text/css" rel="stylesheet" media="print" href="/Imports/xom_print.css"><link type="text/css" title="medium" rel="stylesheet" href="/Imports/xom_web_medium.css"><link type="text/css" title="large" rel="alternate stylesheet" href="/Imports/xom_web_large.css"><link type="text/css" title="small" rel="alternate stylesheet" href="/Imports/xom_web_small.css">	
					<script type="text/javascript" src="/Imports/js/styleswitcher.js"></script>
					<script type="text/javascript" src="/Imports/js/footnotelinks.js"></script>
					<script language="Javascript" src="/Imports/js/xom.js"></script>
					<script type="text/javascript" src="/Imports/js/search.js"></script> <!--[if IE 7.0]>
					<link href="/Imports/mobil_ind_ie7.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]--> 	<!--[if lte IE 6]>
					<link href="/Imports/mobil_ind_ie.css" rel="stylesheet" type="text/css" media="all" />
					<![endif]-->	<!--[if gte IE 5.1]>
				<script type="text/javascript">
					try 
					{
						document.execCommand("BackgroundImageCache", false, true);
					} 
					catch(err) {}
				</script><![endif]--><!-- Set 'expires' in http header, start --><% string cacheExpireDateStr="6/1/2015 11:10:33 AM";
        DateTime cacheExpireDate = Convert.ToDateTime(cacheExpireDateStr); 
        Response.AddHeader("Expires",cacheExpireDate.ToUniversalTime().ToString("ddd, dd MMM yyyy HH:mm:ss 'GMT'")); %><!-- end --></head><body xmlns:xalan-nodeset="org.apache.xalan.xslt.extensions.Nodeset" xmlns:java="http://xml.apache.org/xslt/java" xmlns:fo="http://www.w3.org/1999/XSL/Format" class="list gn01ne"><a href="#mainContent" class="skip">Skip to Main Content</a><div id="container"><!--#include virtual="Navigation/Header.aspx"--><div id="mainPanel" class="clrfix"><!--#include virtual="Navigation/yourindustry_left_navigation.aspx"--><div id="mainContent"><div class="layoutRow clrfix"><div class="img150 left"><img alt="Stabilimento di lubrificanti industriali, la produttività &ldquo;spicca il volo&rdquo; con le ali di Pegaso" title="Stabilimento di lubrificanti industriali, la produttività &ldquo;spicca il volo&rdquo; con le ali di Pegaso" longdesc="" src="/IND/English/Images/article_150x150_Flying-Industry.jpg" border="0"></img></div><h1><b><span style=" font-size: large;">Perché accontentarsi di far funzionare i macchinari quando invece si possono far rendere al massimo?</span></b></h1><p>Con oltre 100 anni di esperienza e competenza nel settore della lubrificazione industriale, i lubrificanti industriali Mobil&trade; aiutano a mantenere il funzionamento ottimale dei vostri macchinari. &nbsp;I lubrificanti industriali Mobil sono stati studiati per aiutarvi a:</p><p>&bull; Aumentare l'affidabilità delle macchine<br>
&bull; Migliorare la sicurezza sul lavoro<br>
&bull; Ridurre i costi operativi<br>
&bull; Prolungare la durata di vita dei macchianari<br>
&bull; Minimizzare i potenziali impatti sull&rsquo;ambiente&nbsp;</p><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Traliccio elettrico del settore energetico, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " title="Traliccio elettrico del settore energetico, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_energy_industry.jpg" border="0"></img><h3><a title="" href="yourindustry_energy.aspx">settore energetico</a></h3><p>Siamo al servizio dei produttori di energia, tradizionale o rinnovabile, incluso il settore del carbone, delle turbine e motori a gas, il nucleare e l&rsquo;eolico.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a title="" href="yourindustry_energy.aspx">Scoprite di più &gt;</a><br></p></div><div class="item right"><img alt="Stabilimento del settore manifatturiero, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " title="Stabilimento del settore manifatturiero, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_manufacturing_industry.jpg" border="0"></img><h3><a title="" href="yourindustry_manufacturing.aspx">settore manifatturiero</a></h3><p>Fate &ldquo;decollare&rdquo; la produttività dei vostri impianti, sia che operiate nell&rsquo;industria alimentare, delle materie plastiche o in qualsiasi altro comparto.&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_manufacturing.aspx">Scoprite di più &gt;</a><br></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Escavatrice per settore minerario, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " title="Escavatrice per settore minerario, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_mining_off_highway.jpg" border="0"></img><h3><a title="" href="yourindustry_mining_offhighway.aspx">settore minerario/macchine movimento terra</a></h3><p>I lubrificanti industriali Mobil&trade; offrono una protezione superlativa anche nelle difficili condizioni di servizio in cui operano le industrie &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; del settore minerario e del<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cemento.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<a title="" href="yourindustry_mining_offhighway.aspx">Scoprite di più &gt;</a></p><p></p></div><div class="item right"><img alt="Cartiera, la produttività &ldquo;spicca il volo&rdquo; con le ali di Pegaso " title="Cartiera, la produttività &ldquo;spicca il volo&rdquo; con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_pulp_and_paper.jpg" border="0"></img><h3><a title="" href="yourindustry_pulpandpaper.aspx">settore cellulosa e carta</a></h3><p>Sia che la vostra azienda produca giornali, carte speciali o cartone ondulato, i lubrificanti industriali Mobil&trade; possono aiutarvi a mantenere il funzionamento<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;ottimale dei vostri macchinari.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_pulpandpaper.aspx">Scoprite di più &gt;</a></p><p></p></div></div><p></p></div><div class="mc2column"><div class="itemgroup clrfix"><div class="item left"><img alt="Benna per settore metallurgico, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " title="Benna per settore metallurgico, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_primary_metals.jpg" border="0"></img><h3><a title="" href="yourindustry_primarymetals.aspx">settore metalli primari</a></h3><p>Per la produzione di ferro e acciaio potete contare sui lubrificanti industriali Mobil&trade; per aiutarvi ad aumentare la produzione, in minor tempo, in modo più sicuro e con<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;maggior efficienza energetica.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a title="" href="yourindustry_primarymetals.aspx">Scoprite di più &gt;</a></p><p></p></div><div class="item right"><img alt="Stabilimento di trasformazione, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " title="Stabilimento di trasformazione, la produttività &ldquo;spicca il volo&rdquo; &nbsp;con le ali di Pegaso " longdesc="" src="/IND/English/Images/teaser_90x90_process.jpg" border="0"></img><h3><a title="" href="yourindustry_process.aspx">settore trasformazione</a></h3><p>Per qualsiasi genere di impianto di trasformazione, possiamo offrire prodotti ad alte prestazioni, supportati da servizi innovativi.<br><a title="" href="yourindustry_process.aspx">Scoprite di più &gt;</a></p><p></p></div></div><p></p></div><%if(File.Exists(Server.MapPath("yourindustry2.aspx"))){%><div class="paging"><ul><li class="label">page 1 of 2</li><li>1</li><li><a href="yourindustry2.aspx">2</a></li><li><a href="yourindustry2.aspx">next</a></li></ul></div><%}%></div></div><!--#include virtual="Navigation/Footer.aspx"--></div></body></html>